#!/usr/bin/env perl

use strict;
use warnings;

use lib 'lib';

# Start command line interface for application
require Mojolicious::Commands;
my $app = Mojolicious::Commands->start_app('Comments');

$app->config(hypnotoad => {listen => ['http://*:3001']});


