
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>Definition of Attributes</h2>
              <p>Attributes of quality represent our measurement goals for the given context. The first step when defining attributes is to gather quality requirements, in this case both for the Eclipse foundation and the PolarSys working group. These have been summarised <a href="https://polarsys.org/wiki/EclipseQualityRequirements">on a dedicated page of the wiki</a>. We relied on different standards and norms to formalise them: ISO 9126 and 250xx for the product, CMMi for the process, and open-source quality models for the community. </p><br />
        

              <ul class="list-group">
                <li class="list-group-item"><p id="QM_ACTIVITY"><strong>Activity</strong> ( QM_ACTIVITY )</p>
<p class="desc">How active is the project ecosystem? Are there a lot of actions and events happening?</p>

                </li>
                <li class="list-group-item"><p id="QM_ANA"><strong>Analysability</strong> ( QM_ANA )</p>
<p class="desc">Degree of effectiveness and efficiency with which it is possible to assess the impact on a product or system of an intended change to one or more of its parts, or to diagnose a product for deficiencies or causes of failures, or to identify parts to be modified. (ISO/IEC 25010)</p>

                </li>
                <li class="list-group-item"><p id="QM_CHA"><strong>Changeability</strong> ( QM_CHA )</p>
<p class="desc">Degree to which a product or system can be effectively and efficiently modified without introducing defects or degrading existing product quality. (ISO/IEC 25010)</p>

                </li>
                <li class="list-group-item"><p id="QM_DIVERSITY"><strong>Diversity</strong> ( QM_DIVERSITY )</p>
<p class="desc">How diverse is the project ecosystem? Are there enough different actors to ensure its sustainability?</p>

                </li>
                <li class="list-group-item"><p id="QM_ECOSYSTEM"><strong>Ecosystem</strong> ( QM_ECOSYSTEM )</p>
<p class="desc">The degree of maturity for the ecosystem evolving around the project: is it active, diversified, responsive?</p>

                </li>
                <li class="list-group-item"><p id="QM_FEEDBACK"><strong>User feedback</strong> ( QM_FEEDBACK )</p>
<p class="desc">How do the users of the software evaluate the project and product?</p>

                </li>
                <li class="list-group-item"><p id="QM_IP"><strong>Intellectual Property Management</strong> ( QM_IP )</p>
<p class="desc">How is intellectual property handled in the project? Is there an IP log? Are the project and the Eclipse Foundation safe regarding IP?</p>

                </li>
                <li class="list-group-item"><p id="QM_ITS"><strong>Change Management</strong> ( QM_ITS )</p>
<p class="desc">Do the project applies best practices regarding change management?</p>

                </li>
                <li class="list-group-item"><p id="QM_PLAN"><strong>Planning Management</strong> ( QM_PLAN )</p>
<p class="desc">Is the project behaviour predicable? Are outputs delivered on planned time and quality?</p>

                </li>
                <li class="list-group-item"><p id="QM_PROCESS"><strong>Process</strong> ( QM_PROCESS )</p>
<p class="desc">The maturity of the process: is it predictable, are good practices enforced, etc.</p>

                </li>
                <li class="list-group-item"><p id="QM_PRODUCT"><strong>Product</strong> ( QM_PRODUCT )</p>
<p class="desc">The software product produced by the project, i.e. the source code, binaries, tests.</p>

                </li>
                <li class="list-group-item"><p id="QM_QUALITY"><strong>Project Quality</strong> ( QM_QUALITY )</p>
<p class="desc">The overall quality of the project. In the context of embedded software, this is often assimilated to Maturity.</p>

                </li>
                <li class="list-group-item"><p id="QM_REL"><strong>Reliability</strong> ( QM_REL )</p>
<p class="desc">Degree to which a system, product or component performs specified functions under specified conditions for a specified period of time. (ISO/IEC 25010)</p>

                </li>
                <li class="list-group-item"><p id="QM_RESPONSIVENESS"><strong>Responsiveness</strong> ( QM_RESPONSIVENESS )</p>
<p class="desc">How fast people get an answer when they have a problem working with the project?</p>

                </li>
                <li class="list-group-item"><p id="QM_REU"><strong>Reusability</strong> ( QM_REU )</p>
<p class="desc">Degree to which an asset can be used in more than one system, or in building other assets. (ISO/IEC 25010)</p>

                </li>
                <li class="list-group-item"><p id="QM_SCM"><strong>Configuration Management</strong> ( QM_SCM )</p>
<p class="desc">Do the project applies best practices regarding software configuration management?</p>

                </li>
                <li class="list-group-item"><p id="QM_SUPPORT"><strong>Support</strong> ( QM_SUPPORT )</p>
<p class="desc">What is the amount of knowledge answered when someone requires help?</p>

                </li>
                <li class="list-group-item"><p id="QM_TST"><strong>Test Management</strong> ( QM_TST )</p>
<p class="desc">Is the product thoroughly tested? How many tests are there, what is the code coverage?</p>

                </li>
                <li class="list-group-item"><p id="QM_USAGE"><strong>Usage</strong> ( QM_USAGE )</p>
<p class="desc">The degree of usage of the project: is it widely used, by different people in different context?</p>

                </li>
                <li class="list-group-item"><p id="QM_VISIBILITY"><strong>Visibility</strong> ( QM_VISIBILITY )</p>
<p class="desc">Do people talk about the software? Are there research articles, journal articles, and conference presentations?</p>

                </li>
              </ul>
            </div>
          </div>
        </div>