
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">

              <h3>Maturity Assessment Documentation</h3>

              <p>The full process is self-documented; everything needed to get the most out of the analysis process should be available from this web site. If anything is missing, please do not hesitate to <a href="/contact.html">contact us</a>.</p>
              <p><a href="http://polarsys.org">PolarSys</a> is an Eclipse <a href="http://www.eclipse.org/org/workinggroups/">Industry Working Group</a> created by large industry players and by tools providers to collaborate on the creation and support of Open Source tools for the development of embedded systems. Members of PolarSys started working on a <a href="https://polarsys.org/wiki/Maturity_Assessment_WG">Maturity Assessment task force</a> back in 2013, to provide an evaluation of the quality of software components entering the PolarSys umbrella, and provides advice and guidance to improve it. </p>

              <p>The complete process is fully documented, from <a href="https://polarsys.org/wiki/EclipseQualityRequirements">quality requirements</a> to <a href="/documentation/metrics.html">metrics</a> used to assess them. It leverages the <a href="http://dashboard.eclipse.org">Eclipse Dashboard</a>, the <a href="http://wiki.eclipse.org/Project_Management_Infrastructure">Project Management Infrastructure</a> and <a href="http://wiki.eclipse.org/Sonar">SonarQube</a> instances to take advantage of open development data of projects: mailing lists, configuration management, issue tracking system, source code, and more.</p>
    
              <p>This web site is automatically generated from the definition files stored in a git repository, so it can not be modified directly. Instead, please send your remarks to the <a href="https://dev.eclipse.org/mailman/listinfo/polarsys-iwg">PolarSys mailing list</a> or <a href="/contact.html">contact us</a>.</p>

            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading"><b>Documentation</b></div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="quality_model.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> The full quality model</a>
                    <a href="attributes.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Quality attributes definition</a>
                    <a href="questions.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Questions definition</a>
                    <a href="metrics.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Metrics definition</a>
                    <a href="rules.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Rules (PMD, FindBugs)</a>
                    <a href="references.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> References</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading"><b>Documentation: scales</b></div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="scales.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Scales index</a>
                    <a href="scales_grimoire.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Grimoire Scales</a>
                    <a href="scales_marketplace.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Marketplace Scales</a>
                    <a href="scales_pmi.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> PMI Scales</a>
                    <a href="scales_rulechecking.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Rule Checking Scales</a>
                    <a href="scales_sonarqube.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> SonarQube Scales</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
