
              <h2>Definition of Questions</h2>
              <p>Questions are mapped to quality attributes, on one side, and to metrics on the other side. It acts as a generic definition for measurement, allowing users to analyse different types of projects with the same quality tree. Questions also preserve the semantics and consistency of measures regarding associated the quality attribute, see Basili's Goal-Question-Metric approach [<a href="/documentation/references.html#Basili1994">Basili1994</a>] for more information on this approach.</p><br />
        

              <ul class="list-group">
                <li class="list-group-item"><p id="ALL_DATA"><strong>Access points</strong> ( ALL_DATA )</p>
<p class="desc"></a>
<p class="desc">The average amount of attributes and methods defined on a class, whatever their visibility is.</p>

                </li>
                <li class="list-group-item"><p id="CODE_CLONE"><strong>Code cloning</strong> ( CODE_CLONE )</p>
<p class="desc"></a>
<p class="desc">The amount of duplicated lines in the code.</p>
<p class="desc">Duplication makes changes to the code difficult, because the maintainer has to look for all instances of the modified code to propagate a fix.</p>

                </li>
                <li class="list-group-item"><p id="CODE_DOC"><strong>Code documentation</strong> ( CODE_DOC )</p>
<p class="desc"></a>
<p class="desc">The amount of documentation in the code: comment rate, javadoc, etc.</p>

                </li>
                <li class="list-group-item"><p id="CODE_SIZE"><strong>Code size</strong> ( CODE_SIZE )</p>
<p class="desc"></a>
<p class="desc">The overall size of the code.</p>

                </li>
                <li class="list-group-item"><p id="CPX"><strong>Code complexity</strong> ( CPX )</p>
<p class="desc"></a>
<p class="desc">The computational complexity of the code: control, data, inheritance.</p>

                </li>
                <li class="list-group-item"><p id="CPX_CF"><strong>Control flow complexity</strong> ( CPX_CF )</p>
<p class="desc"></a>
<p class="desc">The computational complexity of the control flow structure in the code functions.</p>

                </li>
                <li class="list-group-item"><p id="CPX_DF"><strong>Data flow complexity</strong> ( CPX_DF )</p>
<p class="desc"></a>
<p class="desc">The complexity of the data flow structure in the code functions.</p>

                </li>
                <li class="list-group-item"><p id="CPX_OO"><strong>OO complexity</strong> ( CPX_OO )</p>
<p class="desc"></a>
<p class="desc">The complexity of the object-oriented architecture and structure. Composed of MDIT (maximum depth of inheritance tree).</p>

                </li>
                <li class="list-group-item"><p id="DOWNLOADS"><strong>Downloads</strong> ( DOWNLOADS )</p>
<p class="desc"></a>
<p class="desc">What is the amount of downloads?</p>

                </li>
                <li class="list-group-item"><p id="INSTALL"><strong>Installations</strong> ( INSTALL )</p>
<p class="desc"></a>
<p class="desc">The level of usage of the product. How much is really used the software? In different contexts, in local or distributed teams, etc.</p>

                </li>
                <li class="list-group-item"><p id="IP_LOG"><strong>IP Log</strong> ( IP_LOG )</p>
<p class="desc"></a>
<p class="desc">Is the intellectual property of contributions checked and enforced?</p>

                </li>
                <li class="list-group-item"><p id="ITS_REL"><strong>ITS Reliability</strong> ( ITS_REL )</p>
<p class="desc"></a>
<p class="desc">The reliability assessment of the project regarding registered bugs.</p>

                </li>
                <li class="list-group-item"><p id="ITS_USAGE"><strong>ITS usage</strong> ( ITS_USAGE )</p>
<p class="desc"></a>
<p class="desc">How much the ITS system was used recently.</p>

                </li>
                <li class="list-group-item"><p id="LIC"><strong>Licensing</strong> ( LIC )</p>
<p class="desc"></a>
<p class="desc">Are licensing issues considered? Is there a list of licences used in the product?</p>

                </li>
                <li class="list-group-item"><p id="MKT_FEEDBACK"><strong>Marketplace feedback</strong> ( MKT_FEEDBACK )</p>
<p class="desc"></a>
<p class="desc">What is the feedback of users of the Eclipse Marketplace on the product?</p>
<p class="desc">If the product is not registered on the marketplace, the measure is set to zero.</p>

                </li>
                <li class="list-group-item"><p id="MLS_DEV_ACTIVITY"><strong>Developer ML activity</strong> ( MLS_DEV_ACTIVITY )</p>
<p class="desc">How active is the developer mailing list?</a>
<p class="desc">Activity on the developer mailing list.</p>

                </li>
                <li class="list-group-item"><p id="MLS_DEV_DIVERSITY"><strong>Developer ML diversity</strong> ( MLS_DEV_DIVERSITY )</p>
<p class="desc">How many users have contributed to the developer mailing list?</a>
<p class="desc">Diversity of users on the developer mailing list.</p>

                </li>
                <li class="list-group-item"><p id="MLS_DEV_RESPONSIVENESS"><strong>Developer ML responsiveness</strong> ( MLS_DEV_RESPONSIVENESS )</p>
<p class="desc">How long have questions on the developer mailing list to wait before being answered?</a>
<p class="desc">The delay of answers on the developer mailing list.</p>

                </li>
                <li class="list-group-item"><p id="MLS_DEV_SUPPORT"><strong>Developer ML support</strong> ( MLS_DEV_SUPPORT )</p>
<p class="desc">What amount of resources can be gathered from the developer mailing list?</a>
<p class="desc">The quantity of information gathered by questions on the developer mailing list.</p>

                </li>
                <li class="list-group-item"><p id="MLS_USR_ACTIVITY"><strong>User ML activity</strong> ( MLS_USR_ACTIVITY )</p>
<p class="desc">How active is the user mailing list?</a>
<p class="desc">Activity on the user mailing list.</p>

                </li>
                <li class="list-group-item"><p id="MLS_USR_DIVERSITY"><strong>User ML diversity</strong> ( MLS_USR_DIVERSITY )</p>
<p class="desc">How many users have contributed to the user mailing list?</a>
<p class="desc">Diversity of users on the user mailing list.</p>

                </li>
                <li class="list-group-item"><p id="MLS_USR_RESPONSIVENESS"><strong>User ML responsiveness</strong> ( MLS_USR_RESPONSIVENESS )</p>
<p class="desc">How long have questions on the user mailing list to wait before being answered?</a>
<p class="desc">The delay of answers on the developer mailing list.</p>

                </li>
                <li class="list-group-item"><p id="MLS_USR_SUPPORT"><strong>User ML support</strong> ( MLS_USR_SUPPORT )</p>
<p class="desc">What amount of resources can be gathered from the user mailing list?</a>
<p class="desc">The quantity of information gathered by questions on the user mailing list.</p>

                </li>
                <li class="list-group-item"><p id="PLAN_ON_TIME"><strong>Plan on time</strong> ( PLAN_ON_TIME )</p>
<p class="desc"></a>
<p class="desc">Is the project on time according to its schedule?</p>

                </li>
                <li class="list-group-item"><p id="PLAN_RELEASES"><strong>Milestones</strong> ( PLAN_RELEASES )</p>
<p class="desc"></a>
<p class="desc">Is the project having regular milestones, do they prove to be effective?</p>

                </li>
                <li class="list-group-item"><p id="PRACTICES_ANA"><strong>Analysability practices</strong> ( PRACTICES_ANA )</p>
<p class="desc"></a>
<p class="desc">What practices (rules checked) related to analysability are violated, and how often?</p>

                </li>
                <li class="list-group-item"><p id="PRACTICES_CHA"><strong>Changeability practices</strong> ( PRACTICES_CHA )</p>
<p class="desc"></a>
<p class="desc">What practices (rules checked) related to changeability are violated, and how often?</p>

                </li>
                <li class="list-group-item"><p id="PRACTICES_REL"><strong>Reliability practices</strong> ( PRACTICES_REL )</p>
<p class="desc"></a>
<p class="desc">What practices (rules checked) related to reliability are violated, and how often?</p>

                </li>
                <li class="list-group-item"><p id="PRACTICES_REU"><strong>Reusability practices</strong> ( PRACTICES_REU )</p>
<p class="desc"></a>
<p class="desc">What practices (rules checked) related to reusability are violated, and how often?</p>

                </li>
                <li class="list-group-item"><p id="PUBLIC_DATA"><strong>Public access points</strong> ( PUBLIC_DATA )</p>
<p class="desc"></a>
<p class="desc">Average number of public classes, interfaces, methods, constructors, annotations and attributes.</p>

                </li>
                <li class="list-group-item"><p id="PUB_CONF"><strong>Visibility in research</strong> ( PUB_CONF )</p>
<p class="desc"></a>
<p class="desc">How well-known is the software project in the academic field?</p>

                </li>
                <li class="list-group-item"><p id="PUB_ITS_INFO"><strong>ITS information access</strong> ( PUB_ITS_INFO )</p>
<p class="desc">Is there some documentation about the ITS process, rules and conventions? How easy is it for a newcomer to use the issue tracking system?</a>
<p class="desc">Measures the availability of information regarding ITS usage, conventions, access.</p>

                </li>
                <li class="list-group-item"><p id="PUB_SCM_INFO"><strong>SCM information access</strong> ( PUB_SCM_INFO )</p>
<p class="desc"></a>
<p class="desc">Measures the availability of information regarding SCM usage, conventions, access.</p>

                </li>
                <li class="list-group-item"><p id="SCM_ACTIVITY"><strong>SCM activity</strong> ( SCM_ACTIVITY )</p>
<p class="desc">How active is the developer mailing list?</a>
<p class="desc">Activity on the software configuration management system.</p>

                </li>
                <li class="list-group-item"><p id="SCM_DIVERSITY"><strong>SCM diversity</strong> ( SCM_DIVERSITY )</p>
<p class="desc">How many users have contributed to the software configuration management system?</a>
<p class="desc">Diversity of users on the software configuration management system.</p>

                </li>
                <li class="list-group-item"><p id="SCM_DOCS"><strong>SCM Documentation</strong> ( SCM_DOCS )</p>
<p class="desc">Is there some documentation about the SCM process, rules and conventions? How easy is it for a newcomer to use the configuration management tool?</a>
<p class="desc">Measures the availability of information regarding SCM usage, conventions, access.</p>

                </li>
                <li class="list-group-item"><p id="SCM_STABILITY"><strong>SCM Stability</strong> ( SCM_STABILITY )</p>
<p class="desc"></a>
<p class="desc">How much the files are stable according to the SCM system. 
A file which has been heavily modified recently lacks experience, tests and feedback. </p>

                </li>
                <li class="list-group-item"><p id="SCM_USAGE"><strong>SCM usage</strong> ( SCM_USAGE )</p>
<p class="desc"></a>
<p class="desc">How much the SCM system was used during last month.</p>

                </li>
                <li class="list-group-item"><p id="TST_COV"><strong>Test coverage</strong> ( TST_COV )</p>
<p class="desc"></a>
<p class="desc">What percentage of the product has tests?</p>

                </li>
                <li class="list-group-item"><p id="TST_SUCCESS"><strong>Test success density</strong> ( TST_SUCCESS )</p>
<p class="desc"></a>
<p class="desc">Are the available tests successful when executed?</p>

                </li>
                <li class="list-group-item"><p id="TST_VOL"><strong>Number of tests</strong> ( TST_VOL )</p>
<p class="desc"></a>
<p class="desc">The overall amount of tests executed for the project.</p>

                </li>
              </ul>