
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>References</h2>
              <p>All refs used in the maturity assessment process are described thereafter, with useful information and references.</p><br />
        

              <ul class="list-group">
                <li class="list-group-item"><p id="Basili1994"><strong>[Basili1994]</strong> Basili, V. R., Caldiera, G., & Rombach, H. D. (1994). The Goal Question Metric approach. In Encyclopedia of Software Engineering. Wiley. <br />See also <a href="http://maisqual.squoring.com/wiki/index.php/The Goal Question Metric Approach">http://maisqual.squoring.com/wiki/index.php/The Goal Question Metric Approach</a></p></li>

                <li class="list-group-item"><p id="Chidamber1994"><strong>[Chidamber1994]</strong> Shyam R. Chidamber, & Chris F. Kemerer. (1994). A Metrics Suite for Object Oriented Design. IEEE Transactions on Software Engineering, 20(6), 476 – 493.</p></li>

                <li class="list-group-item"><p id="Ing2003"><strong>[Ing2003]</strong> Ing, M., & Georgiadou, E. (2003). Software Quality Model Requirements for Software Quality Engineering. In 14th International Conference on the Software Quality Requirement.</p></li>

                <li class="list-group-item"><p id="McCabe1976"><strong>[McCabe1976]</strong> McCabe, T. (1976). A complexity measure. Software Engineering, IEEE Transactions on, 4, 308–320</p></li>

              </ul>
            </div>
          </div>
        </div>