
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">

              <h3>Scales &gt; PMI</h3>

              <p>The PMI (Project Management Infrastructure) maintains a list of Eclipse projects with a set of associated meta data. It includes information about the various documentation pieces for the project (web site, wiki, getting started guide, etc.), the repositories used for development (code, bugzilla), and releases (date, milestones, review, etc.).</p>
              
              <p>To setup the scales, we retrieved the <a href="http://projects.eclipse.org/list-of-projects">complete list of projects</a> registered in the PMI repository (251 at the time of writing), and extracted our metrics on the resulting set. You can download it <a href="/data/metrics_pmi_all.csv">here</a> (CSV format) and play with the data at your wish.</p>
              
              <div class="media">
                <a class="media-left" href="/images/percentage_of_release_reviews_marked_as_successful_for_eclipse_projects.svg">
                  <img width="256px" src="/images/percentage_of_release_reviews_marked_as_successful_for_eclipse_projects.svg"  class="img-responsive" alt="percentage_of_release_reviews_marked_as_successful_for_eclipse_projects" />
                </a>
                <div class="media-body">
                  <h4 class="media-heading">Media heading</h4>
                  <p>This plot shows </p>
                </div>
              </div>
              
            </div>
          </div>
        </div>
