
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h3>About this project</h3>
              
              <p><a href="http://polarsys.org">PolarSys</a> is an Eclipse <a href="http://www.eclipse.org/org/industry-workgroups/">Industry Working Group</a> created by large industry players and by tools providers to collaborate on the creation and support of Open Source tools for the development of embedded systems. Members of PolarSys started working on a <a href="https://polarsys.org/wiki/Maturity_Assessment_WG">Maturity Assessment task force</a> back in 2013, to assess and help improve quality of projects entering the PolarSys umbrella.</p>
    
              <h3>More information</h3>

              <p>A lot of information is available in the <a href="https://polarsys.org/wiki/Maturity_Assessment_WG">PolarSys wiki</a>. All updates are posted on the main page, and we try to keep the wiki updated. More specifically, you should have a look at the following pages:</p>
        
              <ul>
                <li>The main page of the maturity assessment task force, with recent news and more details: <a href="https://polarsys.org/wiki/Maturity_Assessment_WG">https://polarsys.org/wiki/Maturity_Assessment_WG</a></li>
                <li>The overall architecture of the process: <a href="https://polarsys.org/wiki/MaturityAssessmentToolsArchitecture">https://polarsys.org/wiki/MaturityAssessmentToolsArchitecture</a></li>
                <li>A list of sample projects and their data sources: <a href="https://polarsys.org/wiki/MaturityAssessmentProjects">https://polarsys.org/wiki/MaturityAssessmentProjects</a></li>
              </ul>

              <p>The PolarSys mailing list is the place where all this is discussed. You can freely subscribe <a href="https://dev.eclipse.org/mailman/listinfo/polarsys-iwg">here<a/>, or read the public archives <a href="http://dev.eclipse.org/mhonarc/lists/polarsys-iwg/">there</a>.</p>
        
              <h3>Contributing</h3>
              
              Feedback, comments and contributions are welcome. The best place for discussing features and providing feedback is on the PolarSys mailing list.
        
            </div>
          </div>
        </div>
