
              <h3 class="page-header">Example Custom page</h3>
              <p>This page is an example of what could be the home page of this web site. Just add a file with the inc extension in the src directory and it will be transformed and integrated in the generated web site.</p>
        

              <div class="panel panel-default">
                <div class="panel-heading">Panel heading without title</div>
                  <div class="panel-body">
                    Panel content
                    <div class="progress">
                      <div class="progress-bar progress-bar-success progress-bar-striped" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5"  style="width: 60%;">3 / 5</div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"  style="width: 40%;">2 / 5</div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar progress-bar-warning progress-bar-striped" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"  style="width: 80%;">4 / 5</div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar progress-bar-striped" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"  style="width: 60%;">3 / 5</div>
                    </div>
                    <div class="progress">
                      <div class="progress-bar progress-bar-danger progress-bar-striped" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"  style="width: 100%">5 / 5</div>
                    </div>
                  </div>
                </div>
          
          

                <div class="panel panel-default">
                  <div class="panel-heading"><b>Sub-folders</b></div>
                    <div class="panel-body">
                      <div class="list-group">
                        <a href="project_1" class="list-group-item"><span class="glyphicon glyphicon-folder-close" />&nbsp;Project 1</a>
                        <a href="project_2" class="list-group-item"><span class="glyphicon glyphicon-folder-close" />&nbsp;Project 2</a>
                        <a href="project_3" class="list-group-item"><span class="glyphicon glyphicon-folder-close" />&nbsp;Project 3</a>
                      </div>
                    </div>
                  </div>
                  <div class="panel panel-default">
                    <div class="panel-heading"><b>Files</b></div>
                    <div class="panel-body">
                      <div class="list-group">
                        <a href="custom.html" class="list-group-item"><span class="glyphicon glyphicon-file" />&nbsp;custom.html</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
       
