
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">

              <h3>Maturity Assessment Home</h3>
              
              <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                  <span class="sr-only">Close</span>
                </button>
                <strong>Info:</strong> This site is an on-going work. You can <a href="/about.html">participate</a> or tell us what you think. 
              </div>
              
              

              <img src="/images/logo_polarsys.png" class="img-responsive pull-right" style="margin: 5px" alt="PolarSys logo" /> 
              <p>You just landed on the <strong>PolarSys Maturity Assessment dashboard</strong>. <a href="http://polarsys.org">PolarSys</a> is an Eclipse <a href="http://www.eclipse.org/org/industry-workgroups/">Industry Working Group</a> created by large industry players and by tools providers to collaborate on the creation and support of Open Source tools for the development of embedded systems. </p>
              <p>Members of PolarSys started working on a <a href="https://polarsys.org/wiki/Maturity_Assessment_WG">Maturity Assessment task force</a> back in 2013, to provide an evaluation of the quality of software components entering the PolarSys umbrella, and provides advice and guidance to improve it. </p>

              <p>The complete process is fully documented, from <a href="https://polarsys.org/wiki/EclipseQualityRequirements">quality requirements</a> to <a href="/documentation/metrics.html">metrics</a> used to assess them. </p>
    
              <p>This web site is automatically generated from the definition files stored in a git repository, so it can not be modified directly. Instead, please send your remarks to the <a href="https://dev.eclipse.org/mailman/listinfo/polarsys-iwg">PolarSys mailing list</a> or <a href="https://wiki.eclipse.org/index.php?title=User_talk:Boris.chrysalice.org">contact us</a>.</p>

            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading"><b>Documentation</b></div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="documentation/attributes.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Quality attributes definition</a>
                    <a href="documentation/metrics.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Metrics definition</a>
                    <a href="documentation/questions.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Questions definition</a>
                    <a href="documentation/quality_model.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Quality Model</a>
                    <a href="documentation/rules.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Rules</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading"><b>Projects</b></div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="projects/cdt.html" class="list-group-item">
                        <i class="glyphicon glyphicon-folder-open"></i>&nbsp; CDT</a>
                    <a href="projects/ease.html" class="list-group-item"><i class="glyphicon glyphicon-folder-open"></i>&nbsp; EASE</a>
                    <a href="projects/example.html" class="list-group-item"><i class="glyphicon glyphicon-folder-open"></i>&nbsp; Example</a>
                    <a href="projects/papyrus.html" class="list-group-item"><i class="glyphicon glyphicon-folder-open"></i>&nbsp; Papyrus</a>
                    <a href="projects/sirius.html" class="list-group-item"><i class="glyphicon glyphicon-folder-open"></i>&nbsp; Sirius</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
