

          <img src="/images/logo_polarsys.png" class="img-responsive" style="margin: 25px 0px" alt="PolarSys logo" /> 

	  <h1 class="text-right"><small>Welcome to the</small> PolarSys Maturity Assessment Dashboard</h1>

	  <br />
          <p>You just landed on the <strong>PolarSys Maturity Assessment dashboard</strong>. </p>
          <p><a href="http://polarsys.org">PolarSys</a> is an Eclipse <a href="http://www.eclipse.org/org/workinggroups/">Industry Working Group</a> created by large industry players and by tools providers to collaborate on the creation and support of Open Source tools for the development of embedded systems. Members of PolarSys started working on a <a href="https://polarsys.org/wiki/Maturity_Assessment_WG">Maturity Assessment task force</a> back in 2013, to provide an evaluation of the quality of software components entering the PolarSys umbrella, and provide advice and guidance to projects for improving it. </p>

          <p>The complete process is fully documented, from <a href="https://polarsys.org/wiki/EclipseQualityRequirements">quality requirements</a> to <a href="/documentation/metrics.html">metrics</a> used to assess them. It leverages the <a href="http://dashboard.eclipse.org">Eclipse Dashboard</a>, the <a href="http://wiki.eclipse.org/Project_Management_Infrastructure">Project Management Infrastructure</a> and <a href="http://wiki.eclipse.org/Sonar">SonarQube</a> instances to take advantage of open development data of projects: mailing lists, configuration management, issue tracking system, source code, and more.</p>
    
          <p>This web site is automatically generated from the definition files stored in a git repository, so it can not be modified directly. Instead, please send your remarks to the <a href="https://dev.eclipse.org/mailman/listinfo/polarsys-iwg">PolarSys mailing list</a> or <a href="/contact.html">contact us</a>.</p>

	  <br />

          <div class="row">
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-life-ring fa-fw"></i> Documentation</div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="documentation/quality_model.html" class="list-group-item"><i class="fa fa-file-o"></i> The full quality model</a>
                    <a href="documentation/attributes.html" class="list-group-item"><i class="fa fa-file-o"></i> Quality attributes definition</a>
                    <a href="documentation/questions.html" class="list-group-item"><i class="fa fa-file-o"></i> Questions definition</a>
                    <a href="documentation/metrics.html" class="list-group-item"><i class="fa fa-file-o"></i> Metrics definition</a>
                    <a href="documentation/rules.html" class="list-group-item"><i class="fa fa-file-o"></i> Rules (PMD, FindBugs)</a>
                    <a href="documentation/references.html" class="list-group-item"><i class="fa fa-file-o"></i> References</a>
                  </div>
                </div>
              </div>
	      <br />

              <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-life-ring fa-fw"></i> Administration tools</div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="analyse_metrics.html" class="list-group-item"><i class="fa fa-file-o"></i> List of available metrics per project</a>
                    <a href="comments/" class="list-group-item"><i class="fa fa-file-o"></i> Comments administration panel</a>
                  </div>
                </div>
              </div>

            </div>
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading"><i class="fa fa-dashboard fa-fw"></i> Projects</div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="projects/polarsys.capella.html" class="list-group-item">
		       <i class="fa fa-file-o"></i>&nbsp; Capella</a>
                    <a href="projects/tools.cdt.html" class="list-group-item">
		       <i class="fa fa-file-o"></i>&nbsp; CDT</a>
                    <a href="projects/technology.ease.html" class="list-group-item">
		       <i class="fa fa-file-o"></i>&nbsp; EASE</a>
                    <a href="projects/modeling.emf.compare.html" class="list-group-item">
                        <i class="fa fa-file-o"></i>&nbsp; EMF Compare</a>
                    <a href="projects/modeling.gendoc.html" class="list-group-item">
		       <i class="fa fa-file-o"></i>&nbsp; Gendoc</a>
                    <a href="projects/polarsys.kitalpha.html" class="list-group-item">
		       <i class="fa fa-file-o"></i>&nbsp; Kitalpha</a>
                    <a href="projects/modeling.sirius.html" class="list-group-item">
		       <i class="fa fa-file-o"></i>&nbsp; Sirius</a>
                    <a href="projects/tools.tracecompass.html" class="list-group-item">
		       <i class="fa fa-file-o"></i>&nbsp; TraceCompass</a>
                  </div>
                </div>
              </div>
            </div>
