
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">

              <h3>Maturity Assessment Home</h3>
              
              <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                  <span class="sr-only">Close</span>
                </button>
                Info: This web site is hosted on a temporary server and will be migrated to the Eclipse infrastructure when it is officially released. <a href="https://polarsys.org/wiki/Maturity_Assessment_WG" class="alert-link">Stay tuned</A>!
              </div>
              
              <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                  <span class="sr-only">Close</span>
                </button>
                <strong>Info:</strong> This site is an on-going work. You can <a href="/about.html" class="alert-link">participate</a> or <a href="/contact.html" class="alert-link">tell us what you think</a>.<br />
                NEW: <a href="/documentation/scales.html" class="alert-link">Check the scales</a> and how we selected them. Your feedback is welcome!
              </div>
              
              

              <img src="/images/logo_polarsys.png" class="img-responsive pull-right" style="margin: 5px" alt="PolarSys logo" /> 
              <p>You just landed on the <strong>PolarSys Maturity Assessment dashboard</strong>. </p>
              <p><a href="http://polarsys.org">PolarSys</a> is an Eclipse <a href="http://www.eclipse.org/org/industry-workgroups/">Industry Working Group</a> created by large industry players and by tools providers to collaborate on the creation and support of Open Source tools for the development of embedded systems. Members of PolarSys started working on a <a href="https://polarsys.org/wiki/Maturity_Assessment_WG">Maturity Assessment task force</a> back in 2013, to provide an evaluation of the quality of software components entering the PolarSys umbrella, and provides advice and guidance to improve it. </p>

              <p>The complete process is fully documented, from <a href="https://polarsys.org/wiki/EclipseQualityRequirements">quality requirements</a> to <a href="/documentation/metrics.html">metrics</a> used to assess them. It leverages the <a href="http://dashboard.eclipse.org">Eclipse Dashboard</a>, the <a href="http://wiki.eclipse.org/Project_Management_Infrastructure">Project Management Infrastructure</a> and <a href="http://wiki.eclipse.org/Sonar">SonarQube</a> instances to take advantage of open development data of projects: mailing lists, configuration management, issue tracking system, source code, and more.</p>
    
              <p>This web site is automatically generated from the definition files stored in a git repository, so it can not be modified directly. Instead, please send your remarks to the <a href="https://dev.eclipse.org/mailman/listinfo/polarsys-iwg">PolarSys mailing list</a> or <a href="/contact.html">contact us</a>.</p>

            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading">Documentation</div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="documentation/quality_model.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> The full quality model</a>
                    <a href="documentation/attributes.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Quality attributes definition</a>
                    <a href="documentation/questions.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Questions definition</a>
                    <a href="documentation/metrics.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Metrics definition</a>
                    <a href="documentation/rules.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> Rules (PMD, FindBugs)</a>
                    <a href="documentation/references.html" class="list-group-item"><i class="glyphicon glyphicon-file"></i> References</a>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="panel panel-default">
                <div class="panel-heading">Projects</div>
                <div class="panel-body">
                  <div class="list-group">
                    <a href="projects/cdt.html" class="list-group-item">
                        <i class="glyphicon glyphicon-folder-open"></i>&nbsp; CDT</a>
                    <a href="projects/ease.html" class="list-group-item"><i class="glyphicon glyphicon-folder-open"></i>&nbsp; EASE</a>
                    <a href="projects/example.html" class="list-group-item"><i class="glyphicon glyphicon-folder-open"></i>&nbsp; Example</a>
                    <a href="projects/papyrus.html" class="list-group-item"><i class="glyphicon glyphicon-folder-open"></i>&nbsp; Papyrus</a>
                    <a href="projects/sirius.html" class="list-group-item"><i class="glyphicon glyphicon-folder-open"></i>&nbsp; Sirius</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
