
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>Project cdt</h2>

              <div class="tabbable">
                <ul class="nav nav-pills" role="tablist">
                  <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Summary</a></li>
                  <li role="presentation"><a href="#pmi" role="tab" data-toggle="tab">PMI</a></li>
                  <li role="presentation"><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation"><a href="#attrs" role="tab" data-toggle="tab">Attributes</a></li>
                  <li role="presentation"><a href="#questions" role="tab" data-toggle="tab">Questions</a></li>
                  <li role="presentation"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation"><a href="#actions" role="tab" data-toggle="tab">Actions</a></li>
                  <li role="presentation"><a href="#log" role="tab" data-toggle="tab">Errors</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="home"><br />...<h4>Project rating</h4><h4>Main caracteristics</h4><h4>Errors during the analysis</h4>
                    <ul class="list-group">
                    </ul>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="pmi"><br />
                    <dl class="dl-horizontal">
                      <dt>Description</dt>
                      <dd><p>The CDT Project provides a fully functional C and C++ Integrated Development Environment based on the Eclipse platform. Features include: support for project creation and managed build for various toolchains, standard make build, source navigation, various source knowledge tools, such as type hierarchy, call graph, include browser, macro definition browser, code editor with syntax highlighting, folding and hyperlink navigation, source code refactoring and code generation, visual debugging tools, including memory, registers, and disassembly viewers.</p>
</dd>
                      <dt>Web</dt>
                      <dd><a href="http://www.eclipse.org/cdt">http://www.eclipse.org/cdt</a></dd>
                      <dt>Wiki</dt>
                      <dd><a href="http://wiki.eclipse.org/index.php/CDT">http://wiki.eclipse.org/index.php/CDT</a></dd>
                      <dt>Downloads</dt>
                      <dd><a href="http://www.eclipse.org/cdt/downloads.php">http://www.eclipse.org/cdt/downloads.php</a></dd>
                      <dt>Documentation</dt>
                      <dd><a href="http://wiki.eclipse.org/index.php/CDT">http://wiki.eclipse.org/index.php/CDT</a></dd>
                      <dt>Getting Started</dt>
                      <dd><a href="http://dev.eclipse.org/viewcvs/indextools.cgi/%7Echeckout%7E/cdt-home/user/Tutorials.html">http://dev.eclipse.org/viewcvs/indextools.cgi/%7Echeckout%7E/cdt-home/user/Tutorials.html</a></dd>
                    </dl>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="qm">...</div>
                  <div role="tabpanel" class="tab-pane" id="attrs"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/attributes.html#QM_ACTIVITY">Activity</a></td><td><a href="/documentation/attributes.html#QM_ACTIVITY">QM_ACTIVITY</a></td><td>5</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ANA">Analysability</a></td><td><a href="/documentation/attributes.html#QM_ANA">QM_ANA</a></td><td>5</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_CHA">Changeability</a></td><td><a href="/documentation/attributes.html#QM_CHA">QM_CHA</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_DIVERSITY">Diversity</a></td><td><a href="/documentation/attributes.html#QM_DIVERSITY">QM_DIVERSITY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ECOSYSTEM">Ecosystem</a></td><td><a href="/documentation/attributes.html#QM_ECOSYSTEM">QM_ECOSYSTEM</a></td><td>3</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_FEEDBACK">User feedback</a></td><td><a href="/documentation/attributes.html#QM_FEEDBACK">QM_FEEDBACK</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ITS">Change Management</a></td><td><a href="/documentation/attributes.html#QM_ITS">QM_ITS</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PLAN">Planning Management</a></td><td><a href="/documentation/attributes.html#QM_PLAN">QM_PLAN</a></td><td>3</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PROCESS">Process</a></td><td><a href="/documentation/attributes.html#QM_PROCESS">QM_PROCESS</a></td><td>3</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PRODUCT">Product</a></td><td><a href="/documentation/attributes.html#QM_PRODUCT">QM_PRODUCT</a></td><td>2</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_QUALITY">Project Quality</a></td><td><a href="/documentation/attributes.html#QM_QUALITY">QM_QUALITY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_REL">Reliability</a></td><td><a href="/documentation/attributes.html#QM_REL">QM_REL</a></td><td>2</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_RESPONSIVENESS">Responsiveness</a></td><td><a href="/documentation/attributes.html#QM_RESPONSIVENESS">QM_RESPONSIVENESS</a></td><td>3</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_REU">Reusability</a></td><td><a href="/documentation/attributes.html#QM_REU">QM_REU</a></td><td>1</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_SCM">Configuration Management</a></td><td><a href="/documentation/attributes.html#QM_SCM">QM_SCM</a></td><td>5</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_SUPPORT">Support</a></td><td><a href="/documentation/attributes.html#QM_SUPPORT">QM_SUPPORT</a></td><td>2</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_TST">Test Management</a></td><td><a href="/documentation/attributes.html#QM_TST">QM_TST</a></td><td>2</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_USAGE">Usage</a></td><td><a href="/documentation/attributes.html#QM_USAGE">QM_USAGE</a></td><td>2</td></tr>
</table>


                  </div>
                  <div role="tabpanel" class="tab-pane" id="questions"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/questions.html#CODE_CLONE">Code cloning</a></td><td><a href="/documentation/questions.html#CODE_CLONE">CODE_CLONE</a></td><td>1</td></tr>
<tr><td><a href="/documentation/questions.html#CPX">Code complexity</a></td><td><a href="/documentation/questions.html#CPX">CPX</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#INSTALL">Installations</a></td><td><a href="/documentation/questions.html#INSTALL">INSTALL</a></td><td>2</td></tr>
<tr><td><a href="/documentation/questions.html#MKT_FEEDBACK">Marketplace feedback</a></td><td><a href="/documentation/questions.html#MKT_FEEDBACK">MKT_FEEDBACK</a></td><td>3</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_ACTIVITY">Developer ML activity</a></td><td><a href="/documentation/questions.html#MLS_DEV_ACTIVITY">MLS_DEV_ACTIVITY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_DIVERSITY">Developer ML diversity</a></td><td><a href="/documentation/questions.html#MLS_DEV_DIVERSITY">MLS_DEV_DIVERSITY</a></td><td>3</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_RESPONSIVENESS">Developer ML responsiveness</a></td><td><a href="/documentation/questions.html#MLS_DEV_RESPONSIVENESS">MLS_DEV_RESPONSIVENESS</a></td><td>3</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_SUPPORT">Developer ML support</a></td><td><a href="/documentation/questions.html#MLS_DEV_SUPPORT">MLS_DEV_SUPPORT</a></td><td>3</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_ACTIVITY">User ML activity</a></td><td><a href="/documentation/questions.html#MLS_USR_ACTIVITY">MLS_USR_ACTIVITY</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_DIVERSITY">User ML diversity</a></td><td><a href="/documentation/questions.html#MLS_USR_DIVERSITY">MLS_USR_DIVERSITY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_RESPONSIVENESS">User ML responsiveness</a></td><td><a href="/documentation/questions.html#MLS_USR_RESPONSIVENESS">MLS_USR_RESPONSIVENESS</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_SUPPORT">User ML support</a></td><td><a href="/documentation/questions.html#MLS_USR_SUPPORT">MLS_USR_SUPPORT</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#PUB_ITS_INFO">ITS information access</a></td><td><a href="/documentation/questions.html#PUB_ITS_INFO">PUB_ITS_INFO</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#PUB_SCM_INFO">SCM information access</a></td><td><a href="/documentation/questions.html#PUB_SCM_INFO">PUB_SCM_INFO</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#SCM_ACTIVITY">SCM activity</a></td><td><a href="/documentation/questions.html#SCM_ACTIVITY">SCM_ACTIVITY</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#SCM_DIVERSITY">SCM diversity</a></td><td><a href="/documentation/questions.html#SCM_DIVERSITY">SCM_DIVERSITY</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#TST_COV">Test coverage</a></td><td><a href="/documentation/questions.html#TST_COV">TST_COV</a></td><td>4</td></tr>
</table>


                  </div>
                  <div role="tabpanel" class="tab-pane" id="metrics"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/metrics.html#COMR">Comment rate</a></td><td><a href="/documentation/metrics.html#COMR">COMR</a></td><td>16.4</td></tr>
<tr><td><a href="/documentation/metrics.html#DL_REPO_1M">Number of downloads on the web site</a></td><td><a href="/documentation/metrics.html#DL_REPO_1M">DL_REPO_1M</a></td><td>572801</td></tr>
<tr><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">Number of downloads on update site</a></td><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">DL_UPDATE_SITE_1M</a></td><td>3359</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS_AUTH_1M</a></td><td>53</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>0.08</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">ITS_FIX_MED_1M</a></td><td>6.15</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS_UPDATES_1M</a></td><td>199</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_FAV">Number of favourites on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_FAV">MKT_FAV</a></td><td>7</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">Number of failed install on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">MKT_INSTALL_FAILED_1M</a></td><td>301</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">Number of successfull installs on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">MKT_INSTALL_SUCCESS_1M</a></td><td>3058</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_AUTH_1M">Developer ML authors</a></td><td><a href="/documentation/metrics.html#MLS_DEV_AUTH_1M">MLS_DEV_AUTH_1M</a></td><td>32</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">Developer ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">MLS_DEV_RESP_RATIO_1M</a></td><td>2.14</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">Developer ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">MLS_DEV_SUBJ_1M</a></td><td>29</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">Developer ML posts</a></td><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">MLS_DEV_VOL_1M</a></td><td>91</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">User ML response time</a></td><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">MLS_USR_RESP_TIME_MED_1M</a></td><td>0.18</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA">Number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA">NCC_ANA</a></td><td>28410</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA_IDX">Average number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA_IDX">NCC_ANA_IDX</a></td><td>31.07</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA">Number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA">NCC_CHA</a></td><td>5153</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA_IDX">Average number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA_IDX">NCC_CHA_IDX</a></td><td>5.63</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL">Number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL">NCC_REL</a></td><td>7183</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL_IDX">Average number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL_IDX">NCC_REL_IDX</a></td><td>7.86</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU">Number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU">NCC_REU</a></td><td>139754</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU_IDX">Average number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU_IDX">NCC_REU_IDX</a></td><td>152.84</td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">Milestone success rate</a></td><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">PLAN_REVIEWS_SUCCESS_RATE</a></td><td>40</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">ITS information</a></td><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">PUB_ITS_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">SCM information</a></td><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">PUB_SCM_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_ANA">Number of violated rules for analysability</a></td><td><a href="/documentation/metrics.html#RKO_ANA">RKO_ANA</a></td><td>46</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_CHA">Number of violated rules for changeability</a></td><td><a href="/documentation/metrics.html#RKO_CHA">RKO_CHA</a></td><td>14</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REL">Number of violated rules for reliability</a></td><td><a href="/documentation/metrics.html#RKO_REL">RKO_REL</a></td><td>21</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REU">Number of violated rules for reusability</a></td><td><a href="/documentation/metrics.html#RKO_REU">RKO_REU</a></td><td>13</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_ANA">Adherence to analysability rules</a></td><td><a href="/documentation/metrics.html#ROKR_ANA">ROKR_ANA</a></td><td>26.984126984127</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_CHA">Adherence to changeability rules</a></td><td><a href="/documentation/metrics.html#ROKR_CHA">ROKR_CHA</a></td><td>26.3157894736842</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REL">Adherence to reliability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REL">ROKR_REL</a></td><td>55.3191489361702</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REU">Adherence to reusability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REU">ROKR_REU</a></td><td>27.7777777777778</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_ANA">Number of rules for analysability</a></td><td><a href="/documentation/metrics.html#RULES_ANA">RULES_ANA</a></td><td>63</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_CHA">Number of rules for changeability</a></td><td><a href="/documentation/metrics.html#RULES_CHA">RULES_CHA</a></td><td>19</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REL">Number of rules for reliability</a></td><td><a href="/documentation/metrics.html#RULES_REL">RULES_REL</a></td><td>47</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REU">Number of rules for reusability</a></td><td><a href="/documentation/metrics.html#RULES_REU">RULES_REU</a></td><td>18</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM_COMMITS_1M</a></td><td>113</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">SCM_COMMITTED_FILES_1M</a></td><td>230</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM_COMMITTERS_1M</a></td><td>22</td></tr>
<tr><td><a href="/documentation/metrics.html#SLOC">Source Lines Of Code</a></td><td><a href="/documentation/metrics.html#SLOC">SLOC</a></td><td>914354</td></tr>
<tr><td><a href="/documentation/metrics.html#TST_COV_LINES">Percentage of lines of code covered by tests</a></td><td><a href="/documentation/metrics.html#TST_COV_LINES">TST_COV_LINES</a></td><td>63.18</td></tr>
<tr><td><a href="/documentation/metrics.html#VG">Average Cyclomatic Complexity</a></td><td><a href="/documentation/metrics.html#VG">VG</a></td><td>225705</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane" id="practices"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="40%">Mnemo</th><th width="20%">NCC</th></tr>
<tr><td><a href="/documentation/rules.html#DMI_INVOKING_TOSTRING_ON_ARRAY">USELESS_STRING: Invocation of toString on an array </a></td><td><a href="/documentation/rules.html#DMI_INVOKING_TOSTRING_ON_ARRAY">DMI_INVOKING_TOSTRING_ON_ARRAY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#JLM_JSR166_UTILCONCURRENT_MONITORENTER">JLM: Synchronization performed on util.concurrent instance </a></td><td><a href="/documentation/rules.html#JLM_JSR166_UTILCONCURRENT_MONITORENTER">JLM_JSR166_UTILCONCURRENT_MONITORENTER</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidReassigningParameters">Avoid Reassigning Parameters</a></td><td><a href="/documentation/rules.html#AvoidReassigningParameters">AvoidReassigningParameters</a></td><td>1877</td></tr>
<tr><td><a href="/documentation/rules.html#GC_UNRELATED_TYPES">GC: No relationship between generic parameter and method argument </a></td><td><a href="/documentation/rules.html#GC_UNRELATED_TYPES">GC_UNRELATED_TYPES</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#FieldDeclarationsShouldBeAtStartOfClass">Field Declarations Should Be At Start Of Class</a></td><td><a href="/documentation/rules.html#FieldDeclarationsShouldBeAtStartOfClass">FieldDeclarationsShouldBeAtStartOfClass</a></td><td>6058</td></tr>
<tr><td><a href="/documentation/rules.html#EQ_ALWAYS_FALSE">Eq: equals method always returns false </a></td><td><a href="/documentation/rules.html#EQ_ALWAYS_FALSE">EQ_ALWAYS_FALSE</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#CO_COMPARETO_RESULTS_MIN_VALUE">Co: compareTo()/compare() returns Integer.MIN_VALUE</a></td><td><a href="/documentation/rules.html#CO_COMPARETO_RESULTS_MIN_VALUE">CO_COMPARETO_RESULTS_MIN_VALUE</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#OptimizableToArrayCall">Optimizable toArray Call</a></td><td><a href="/documentation/rules.html#OptimizableToArrayCall">OptimizableToArrayCall</a></td><td>167</td></tr>
<tr><td><a href="/documentation/rules.html#AbstractClassWithoutAnyMethod">Abstract Class Without Any Method</a></td><td><a href="/documentation/rules.html#AbstractClassWithoutAnyMethod">AbstractClassWithoutAnyMethod</a></td><td>7</td></tr>
<tr><td><a href="/documentation/rules.html#LooseCoupling">Loose Coupling</a></td><td><a href="/documentation/rules.html#LooseCoupling">LooseCoupling</a></td><td>753</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyStatementBlock">Empty Statement Block</a></td><td><a href="/documentation/rules.html#EmptyStatementBlock">EmptyStatementBlock</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidInstanceofChecksInCatchClause">Avoid Instanceof() Checks In Catch Clause</a></td><td><a href="/documentation/rules.html#AvoidInstanceofChecksInCatchClause">AvoidInstanceofChecksInCatchClause</a></td><td>11</td></tr>
<tr><td><a href="/documentation/rules.html#CompareObjectsWithEquals">Compare Objects With Equals</a></td><td><a href="/documentation/rules.html#CompareObjectsWithEquals">CompareObjectsWithEquals</a></td><td>972</td></tr>
<tr><td><a href="/documentation/rules.html#JumbledIncrementer">Jumbled Incrementer</a></td><td><a href="/documentation/rules.html#JumbledIncrementer">JumbledIncrementer</a></td><td>7</td></tr>
<tr><td><a href="/documentation/rules.html#DM_DEFAULT_ENCODING">Dm: Reliance on default encoding </a></td><td><a href="/documentation/rules.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td><td>449</td></tr>
<tr><td><a href="/documentation/rules.html#SwitchDensity">Switch Density</a></td><td><a href="/documentation/rules.html#SwitchDensity">SwitchDensity</a></td><td>53</td></tr>
<tr><td><a href="/documentation/rules.html#CouplingBetweenObjects">Coupling Between Objects</a></td><td><a href="/documentation/rules.html#CouplingBetweenObjects">CouplingBetweenObjects</a></td><td>53</td></tr>
<tr><td><a href="/documentation/rules.html#PositionLiteralsFirstInComparisons">Position Literals First In Comparisons</a></td><td><a href="/documentation/rules.html#PositionLiteralsFirstInComparisons">PositionLiteralsFirstInComparisons</a></td><td>781</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidSynchronizedAtMethodLevel">Avoid Synchronized At Method Level</a></td><td><a href="/documentation/rules.html#AvoidSynchronizedAtMethodLevel">AvoidSynchronizedAtMethodLevel</a></td><td>631</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidProtectedMethodInFinalClassNotExtending">Avoid Protected Method In Final Class Not Extending</a></td><td><a href="/documentation/rules.html#AvoidProtectedMethodInFinalClassNotExtending">AvoidProtectedMethodInFinalClassNotExtending</a></td><td>24</td></tr>
<tr><td><a href="/documentation/rules.html#EC_ARRAY_AND_NONARRAY">EC: equals() used to compare array and nonarray</a></td><td><a href="/documentation/rules.html#EC_ARRAY_AND_NONARRAY">EC_ARRAY_AND_NONARRAY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#BrokenNullCheck">Broken NullCheck</a></td><td><a href="/documentation/rules.html#BrokenNullCheck">BrokenNullCheck</a></td><td>11</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedPrivateMethod">Unused Private Method</a></td><td><a href="/documentation/rules.html#UnusedPrivateMethod">UnusedPrivateMethod</a></td><td>977</td></tr>
<tr><td><a href="/documentation/rules.html#ReturnFromFinallyBlock">Return From Finally Block</a></td><td><a href="/documentation/rules.html#ReturnFromFinallyBlock">ReturnFromFinallyBlock</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#BC_IMPOSSIBLE_CAST">BC: Impossible cast </a></td><td><a href="/documentation/rules.html#BC_IMPOSSIBLE_CAST">BC_IMPOSSIBLE_CAST</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#EI_EXPOSE_REP">EI: May expose internal representation by returning reference to mutable object </a></td><td><a href="/documentation/rules.html#EI_EXPOSE_REP">EI_EXPOSE_REP</a></td><td>556</td></tr>
<tr><td><a href="/documentation/rules.html#SimplifyBooleanReturns">Simplify Boolean Returns</a></td><td><a href="/documentation/rules.html#SimplifyBooleanReturns">SimplifyBooleanReturns</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#EQ_ALWAYS_TRUE">Eq: equals() method always returns true </a></td><td><a href="/documentation/rules.html#EQ_ALWAYS_TRUE">EQ_ALWAYS_TRUE</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#SI_INSTANCE_BEFORE_FINALS_ASSIGNED">SI: Static initializer creates instance before all static final fields assigned </a></td><td><a href="/documentation/rules.html#SI_INSTANCE_BEFORE_FINALS_ASSIGNED">SI_INSTANCE_BEFORE_FINALS_ASSIGNED</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#LawOfDemeter">LawOfDemeter</a></td><td><a href="/documentation/rules.html#LawOfDemeter">LawOfDemeter</a></td><td>137104</td></tr>
<tr><td><a href="/documentation/rules.html#DoubleCheckedLocking">Double Checked Locking</a></td><td><a href="/documentation/rules.html#DoubleCheckedLocking">DoubleCheckedLocking</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#FinalFieldCouldBeStatic">Final Field Could Be Static</a></td><td><a href="/documentation/rules.html#FinalFieldCouldBeStatic">FinalFieldCouldBeStatic</a></td><td>311</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedPrivateField">Unused Private Field</a></td><td><a href="/documentation/rules.html#UnusedPrivateField">UnusedPrivateField</a></td><td>44</td></tr>
<tr><td><a href="/documentation/rules.html#ImmutableField">Immutable Field</a></td><td><a href="/documentation/rules.html#ImmutableField">ImmutableField</a></td><td>2817</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidConstantsInterface">Avoid Constants Interface</a></td><td><a href="/documentation/rules.html#AvoidConstantsInterface">AvoidConstantsInterface</a></td><td>509</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyFinallyBlock">Empty Finally Block</a></td><td><a href="/documentation/rules.html#EmptyFinallyBlock">EmptyFinallyBlock</a></td><td>8</td></tr>
<tr><td><a href="/documentation/rules.html#PositionLiteralsFirstInCaseInsensitiveComparisons">Position Literals First In Case Insensitive Comparisons</a></td><td><a href="/documentation/rules.html#PositionLiteralsFirstInCaseInsensitiveComparisons">PositionLiteralsFirstInCaseInsensitiveComparisons</a></td><td>63</td></tr>
<tr><td><a href="/documentation/rules.html#SimplifyBooleanExpressions">Simplify Boolean Expressions</a></td><td><a href="/documentation/rules.html#SimplifyBooleanExpressions">SimplifyBooleanExpressions</a></td><td>225</td></tr>
<tr><td><a href="/documentation/rules.html#SwitchStmtsShouldHaveDefault">Switch Statements Should Have Default</a></td><td><a href="/documentation/rules.html#SwitchStmtsShouldHaveDefault">SwitchStmtsShouldHaveDefault</a></td><td>779</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyIfStmt">Empty If Stmt</a></td><td><a href="/documentation/rules.html#EmptyIfStmt">EmptyIfStmt</a></td><td>258</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedFormalParameter">Unused Formal Parameter</a></td><td><a href="/documentation/rules.html#UnusedFormalParameter">UnusedFormalParameter</a></td><td>283</td></tr>
<tr><td><a href="/documentation/rules.html#OverrideBothEqualsAndHashcode">Override Both Equals And Hash code</a></td><td><a href="/documentation/rules.html#OverrideBothEqualsAndHashcode">OverrideBothEqualsAndHashcode</a></td><td>59</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedLocalVariable">Unused Local Variable</a></td><td><a href="/documentation/rules.html#UnusedLocalVariable">UnusedLocalVariable</a></td><td>629</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidUsingOctalValues">Avoid Using Octal Values</a></td><td><a href="/documentation/rules.html#AvoidUsingOctalValues">AvoidUsingOctalValues</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#SimplifyConditional">Simplify Conditional</a></td><td><a href="/documentation/rules.html#SimplifyConditional">SimplifyConditional</a></td><td>125</td></tr>
<tr><td><a href="/documentation/rules.html#UseLocaleWithCaseConversions">Use Locale With Case Conversions</a></td><td><a href="/documentation/rules.html#UseLocaleWithCaseConversions">UseLocaleWithCaseConversions</a></td><td>91</td></tr>
<tr><td><a href="/documentation/rules.html#NonCaseLabelInSwitchStatement">Non Case Label In Switch Statement</a></td><td><a href="/documentation/rules.html#NonCaseLabelInSwitchStatement">NonCaseLabelInSwitchStatement</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#AssignmentToNonFinalStatic">Assignment To Non Final Static</a></td><td><a href="/documentation/rules.html#AssignmentToNonFinalStatic">AssignmentToNonFinalStatic</a></td><td>69</td></tr>
<tr><td><a href="/documentation/rules.html#NonThreadSafeSingleton">Non Thread Safe Singleton</a></td><td><a href="/documentation/rules.html#NonThreadSafeSingleton">NonThreadSafeSingleton</a></td><td>135</td></tr>
<tr><td><a href="/documentation/rules.html#MissingStaticMethodInNonInstantiatableClass">Missing Static Method In Non Instantiatable Class</a></td><td><a href="/documentation/rules.html#MissingStaticMethodInNonInstantiatableClass">MissingStaticMethodInNonInstantiatableClass</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyStatementNotInLoop">Empty Statement Not In Loop</a></td><td><a href="/documentation/rules.html#EmptyStatementNotInLoop">EmptyStatementNotInLoop</a></td><td>7</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyCatchBlock">Empty Catch Block</a></td><td><a href="/documentation/rules.html#EmptyCatchBlock">EmptyCatchBlock</a></td><td>2474</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyMethodInAbstractClassShouldBeAbstract">Empty Method In Abstract Class Should Be Abstract</a></td><td><a href="/documentation/rules.html#EmptyMethodInAbstractClassShouldBeAbstract">EmptyMethodInAbstractClassShouldBeAbstract</a></td><td>241</td></tr>
<tr><td><a href="/documentation/rules.html#EI_EXPOSE_REP2">EI2: May expose internal representation by incorporating reference to mutable object </a></td><td><a href="/documentation/rules.html#EI_EXPOSE_REP2">EI_EXPOSE_REP2</a></td><td>318</td></tr>
<tr><td><a href="/documentation/rules.html#MS_SHOULD_BE_FINAL">MS: Field isn't final but should be </a></td><td><a href="/documentation/rules.html#MS_SHOULD_BE_FINAL">MS_SHOULD_BE_FINAL</a></td><td>112</td></tr>
<tr><td><a href="/documentation/rules.html#MS_MUTABLE_ARRAY">MS: Field is a mutable array </a></td><td><a href="/documentation/rules.html#MS_MUTABLE_ARRAY">MS_MUTABLE_ARRAY</a></td><td>149</td></tr>
<tr><td><a href="/documentation/rules.html#NonStaticInitializer">Non Static Initializer</a></td><td><a href="/documentation/rules.html#NonStaticInitializer">NonStaticInitializer</a></td><td>227</td></tr>
<tr><td><a href="/documentation/rules.html#EQ_OVERRIDING_EQUALS_NOT_SYMMETRIC">Eq: equals method overrides equals in superclass and may not be symmetric </a></td><td><a href="/documentation/rules.html#EQ_OVERRIDING_EQUALS_NOT_SYMMETRIC">EQ_OVERRIDING_EQUALS_NOT_SYMMETRIC</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#AccessorClassGeneration">Accessor Class Generation</a></td><td><a href="/documentation/rules.html#AccessorClassGeneration">AccessorClassGeneration</a></td><td>112</td></tr>
<tr><td><a href="/documentation/rules.html#BooleanInstantiation">Boolean Instantiation</a></td><td><a href="/documentation/rules.html#BooleanInstantiation">BooleanInstantiation</a></td><td>127</td></tr>
<tr><td><a href="/documentation/rules.html#DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED">DP: Classloaders should only be created inside doPrivileged block</a></td><td><a href="/documentation/rules.html#DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED">DP_CREATE_CLASSLOADER_INSIDE_DO_PRIVILEGED</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#GodClass">God Class</a></td><td><a href="/documentation/rules.html#GodClass">GodClass</a></td><td>1091</td></tr>
<tr><td><a href="/documentation/rules.html#TooFewBranchesForASwitchStatement">Too Few Branches For A Switch Statement</a></td><td><a href="/documentation/rules.html#TooFewBranchesForASwitchStatement">TooFewBranchesForASwitchStatement</a></td><td>253</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyWhileStmt">Empty While Stmt</a></td><td><a href="/documentation/rules.html#EmptyWhileStmt">EmptyWhileStmt</a></td><td>16</td></tr>
<tr><td><a href="/documentation/rules.html#PreserveStackTrace">Preserve Stack Trace</a></td><td><a href="/documentation/rules.html#PreserveStackTrace">PreserveStackTrace</a></td><td>198</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidProtectedFieldInFinalClass">Avoid Protected Field In Final Class</a></td><td><a href="/documentation/rules.html#AvoidProtectedFieldInFinalClass">AvoidProtectedFieldInFinalClass</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#JLM_JSR166_LOCK_MONITORENTER">JLM: Synchronization performed on Lock </a></td><td><a href="/documentation/rules.html#JLM_JSR166_LOCK_MONITORENTER">JLM_JSR166_LOCK_MONITORENTER</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#SE_COMPARATOR_SHOULD_BE_SERIALIZABLE">Se: Comparator doesn't implement Serializable </a></td><td><a href="/documentation/rules.html#SE_COMPARATOR_SHOULD_BE_SERIALIZABLE">SE_COMPARATOR_SHOULD_BE_SERIALIZABLE</a></td><td>22</td></tr>
<tr><td><a href="/documentation/rules.html#SE_BAD_FIELD">Se: Non-transient non-serializable instance field in serializable class </a></td><td><a href="/documentation/rules.html#SE_BAD_FIELD">SE_BAD_FIELD</a></td><td>16</td></tr>
<tr><td><a href="/documentation/rules.html#MS_EXPOSE_REP">MS: Public static method may expose internal representation by returning array </a></td><td><a href="/documentation/rules.html#MS_EXPOSE_REP">MS_EXPOSE_REP</a></td><td>24</td></tr>
<tr><td><a href="/documentation/rules.html#IS2_INCONSISTENT_SYNC">IS: Inconsistent synchronization </a></td><td><a href="/documentation/rules.html#IS2_INCONSISTENT_SYNC">IS2_INCONSISTENT_SYNC</a></td><td>129</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidThreadGroup">Avoid ThreadGroup</a></td><td><a href="/documentation/rules.html#AvoidThreadGroup">AvoidThreadGroup</a></td><td>3</td></tr>
<tr><td><a href="/documentation/rules.html#UseNotifyAllInsteadOfNotify">Use Notify All Instead Of Notify</a></td><td><a href="/documentation/rules.html#UseNotifyAllInsteadOfNotify">UseNotifyAllInsteadOfNotify</a></td><td>12</td></tr>
<tr><td><a href="/documentation/rules.html#MS_SHOULD_BE_REFACTORED_TO_BE_FINAL">MS: Field isn't final but should be refactored to be so </a></td><td><a href="/documentation/rules.html#MS_SHOULD_BE_REFACTORED_TO_BE_FINAL">MS_SHOULD_BE_REFACTORED_TO_BE_FINAL</a></td><td>9</td></tr>
<tr><td><a href="/documentation/rules.html#ClassWithOnlyPrivateConstructorsShouldBeFinal">Class With Only Private Constructors Should Be Final</a></td><td><a href="/documentation/rules.html#ClassWithOnlyPrivateConstructorsShouldBeFinal">ClassWithOnlyPrivateConstructorsShouldBeFinal</a></td><td>317</td></tr>
<tr><td><a href="/documentation/rules.html#UncommentedEmptyMethod">Uncommented Empty Method</a></td><td><a href="/documentation/rules.html#UncommentedEmptyMethod">UncommentedEmptyMethod</a></td><td>1574</td></tr>
<tr><td><a href="/documentation/rules.html#BIT_ADD_OF_SIGNED_BYTE">BIT: Bitwise add of signed byte value </a></td><td><a href="/documentation/rules.html#BIT_ADD_OF_SIGNED_BYTE">BIT_ADD_OF_SIGNED_BYTE</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#UseCollectionIsEmpty">Use Collection isEmpty</a></td><td><a href="/documentation/rules.html#UseCollectionIsEmpty">UseCollectionIsEmpty</a></td><td>632</td></tr>
<tr><td><a href="/documentation/rules.html#MS_CANNOT_BE_FINAL">MS: Field isn't final and can't be protected from malicious code </a></td><td><a href="/documentation/rules.html#MS_CANNOT_BE_FINAL">MS_CANNOT_BE_FINAL</a></td><td>43</td></tr>
<tr><td><a href="/documentation/rules.html#BigIntegerInstantiation">BigInteger Instantiation</a></td><td><a href="/documentation/rules.html#BigIntegerInstantiation">BigIntegerInstantiation</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#SingularField">Singular Field</a></td><td><a href="/documentation/rules.html#SingularField">SingularField</a></td><td>174</td></tr>
<tr><td><a href="/documentation/rules.html#RV_RETURN_VALUE_IGNORED_BAD_PRACTICE">RV: Method ignores exceptional return value </a></td><td><a href="/documentation/rules.html#RV_RETURN_VALUE_IGNORED_BAD_PRACTICE">RV_RETURN_VALUE_IGNORED_BAD_PRACTICE</a></td><td>179</td></tr>
<tr><td><a href="/documentation/rules.html#ConstructorCallsOverridableMethod">Constructor Calls Overridable Method</a></td><td><a href="/documentation/rules.html#ConstructorCallsOverridableMethod">ConstructorCallsOverridableMethod</a></td><td>264</td></tr>
<tr><td><a href="/documentation/rules.html#BC_UNCONFIRMED_CAST">BC: Unchecked/unconfirmed cast </a></td><td><a href="/documentation/rules.html#BC_UNCONFIRMED_CAST">BC_UNCONFIRMED_CAST</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidBranchingStatementAsLastInLoop">Avoid Branching Statement As Last In Loop</a></td><td><a href="/documentation/rules.html#AvoidBranchingStatementAsLastInLoop">AvoidBranchingStatementAsLastInLoop</a></td><td>42</td></tr>
<tr><td><a href="/documentation/rules.html#EC_UNRELATED_TYPES">EC: Call to equals() comparing different types</a></td><td><a href="/documentation/rules.html#EC_UNRELATED_TYPES">EC_UNRELATED_TYPES</a></td><td>3</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedModifier">Unused Modifier</a></td><td><a href="/documentation/rules.html#UnusedModifier">UnusedModifier</a></td><td>6663</td></tr>
<tr><td><a href="/documentation/rules.html#MissingBreakInSwitch">Missing Break In Switch</a></td><td><a href="/documentation/rules.html#MissingBreakInSwitch">MissingBreakInSwitch</a></td><td>115</td></tr>
<tr><td><a href="/documentation/rules.html#EC_BAD_ARRAY_COMPARE">EC: Invocation of equals() on an array, which is equivalent to ==</a></td><td><a href="/documentation/rules.html#EC_BAD_ARRAY_COMPARE">EC_BAD_ARRAY_COMPARE</a></td><td>10</td></tr>
<tr><td><a href="/documentation/rules.html#SimpleDateFormatNeedsLocale">Simple Date Format Needs Locale</a></td><td><a href="/documentation/rules.html#SimpleDateFormatNeedsLocale">SimpleDateFormatNeedsLocale</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyTryBlock">Empty Try Block</a></td><td><a href="/documentation/rules.html#EmptyTryBlock">EmptyTryBlock</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#FI_PUBLIC_SHOULD_BE_PROTECTED">FI: Finalizer should be protected, not public </a></td><td><a href="/documentation/rules.html#FI_PUBLIC_SHOULD_BE_PROTECTED">FI_PUBLIC_SHOULD_BE_PROTECTED</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#UnnecessaryLocalBeforeReturn">Unnecessary Local Before Return</a></td><td><a href="/documentation/rules.html#UnnecessaryLocalBeforeReturn">UnnecessaryLocalBeforeReturn</a></td><td>275</td></tr>
<tr><td><a href="/documentation/rules.html#EI_EXPOSE_STATIC_REP2">MS: May expose internal static state by storing a mutable object into a static field </a></td><td><a href="/documentation/rules.html#EI_EXPOSE_STATIC_REP2">EI_EXPOSE_STATIC_REP2</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#LogicInversion">Logic Inversion</a></td><td><a href="/documentation/rules.html#LogicInversion">LogicInversion</a></td><td>31</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidUsingHardCodedIP">Avoid Using Hard Coded IP</a></td><td><a href="/documentation/rules.html#AvoidUsingHardCodedIP">AvoidUsingHardCodedIP</a></td><td>19</td></tr>
<tr><td><a href="/documentation/rules.html#EC_UNRELATED_CLASS_AND_INTERFACE">EC: Call to equals() comparing unrelated class and interface </a></td><td><a href="/documentation/rules.html#EC_UNRELATED_CLASS_AND_INTERFACE">EC_UNRELATED_CLASS_AND_INTERFACE</a></td><td>9</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidDeeplyNestedIfStmts">Avoid Deeply Nested If Statements</a></td><td><a href="/documentation/rules.html#AvoidDeeplyNestedIfStmts">AvoidDeeplyNestedIfStmts</a></td><td>1102</td></tr>
<tr><td><a href="/documentation/rules.html#EmptySynchronizedBlock">Empty Synchronized Block</a></td><td><a href="/documentation/rules.html#EmptySynchronizedBlock">EmptySynchronizedBlock</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#EC_UNRELATED_TYPES_USING_POINTER_EQUALITY">EC: Using pointer equality to compare different types </a></td><td><a href="/documentation/rules.html#EC_UNRELATED_TYPES_USING_POINTER_EQUALITY">EC_UNRELATED_TYPES_USING_POINTER_EQUALITY</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#DefaultLabelNotLastInSwitchStmt">Default Label Not Last In Switch Statement</a></td><td><a href="/documentation/rules.html#DefaultLabelNotLastInSwitchStmt">DefaultLabelNotLastInSwitchStmt</a></td><td>9</td></tr>
<tr><td><a href="/documentation/rules.html#AbstractClassWithoutAbstractMethod">Abstract Class Without Abstract Method</a></td><td><a href="/documentation/rules.html#AbstractClassWithoutAbstractMethod">AbstractClassWithoutAbstractMethod</a></td><td>28</td></tr>
<tr><td><a href="/documentation/rules.html#RV_NEGATING_RESULT_OF_COMPARETO">RV: Negating the result of compareTo()/compare()</a></td><td><a href="/documentation/rules.html#RV_NEGATING_RESULT_OF_COMPARETO">RV_NEGATING_RESULT_OF_COMPARETO</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#ReturnEmptyArrayRatherThanNull">Return Empty Array Rather Than Null</a></td><td><a href="/documentation/rules.html#ReturnEmptyArrayRatherThanNull">ReturnEmptyArrayRatherThanNull</a></td><td>313</td></tr>
<tr><td><a href="/documentation/rules.html#CollapsibleIfStatements">Collapsible If Statements</a></td><td><a href="/documentation/rules.html#CollapsibleIfStatements">CollapsibleIfStatements</a></td><td>1162</td></tr>
<tr><td><a href="/documentation/rules.html#EQ_SELF_USE_OBJECT">Eq: Covariant equals() method defined, Object.equals(Object) inherited</a></td><td><a href="/documentation/rules.html#EQ_SELF_USE_OBJECT">EQ_SELF_USE_OBJECT</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#UseUtilityClass">UseUtilityClass</a></td><td><a href="/documentation/rules.html#UseUtilityClass">UseUtilityClass</a></td><td>357</td></tr>
<tr><td><a href="/documentation/rules.html#MS_OOI_PKGPROTECT">MS: Field should be moved out of an interface and made package protected </a></td><td><a href="/documentation/rules.html#MS_OOI_PKGPROTECT">MS_OOI_PKGPROTECT</a></td><td>422</td></tr>
<tr><td><a href="/documentation/rules.html#DMI_INVOKING_HASHCODE_ON_ARRAY">DMI: Invocation of hashCode on an array </a></td><td><a href="/documentation/rules.html#DMI_INVOKING_HASHCODE_ON_ARRAY">DMI_INVOKING_HASHCODE_ON_ARRAY</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#MS_FINAL_PKGPROTECT">MS: Field should be both final and package protected </a></td><td><a href="/documentation/rules.html#MS_FINAL_PKGPROTECT">MS_FINAL_PKGPROTECT</a></td><td>8</td></tr>
<tr><td><a href="/documentation/rules.html#ForLoopShouldBeWhileLoop">For Loop Should Be While Loop</a></td><td><a href="/documentation/rules.html#ForLoopShouldBeWhileLoop">ForLoopShouldBeWhileLoop</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#UncommentedEmptyConstructor">Uncommented Empty Constructor</a></td><td><a href="/documentation/rules.html#UncommentedEmptyConstructor">UncommentedEmptyConstructor</a></td><td>483</td></tr>
<tr><td><a href="/documentation/rules.html#MS_PKGPROTECT">MS: Field should be package protected </a></td><td><a href="/documentation/rules.html#MS_PKGPROTECT">MS_PKGPROTECT</a></td><td>594</td></tr>
<tr><td><a href="/documentation/rules.html#UnconditionalIfStatement">Unconditional If Statement</a></td><td><a href="/documentation/rules.html#UnconditionalIfStatement">UnconditionalIfStatement</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#ExcessiveImports">Excessive Imports</a></td><td><a href="/documentation/rules.html#ExcessiveImports">ExcessiveImports</a></td><td>708</td></tr>
<tr><td><a href="/documentation/rules.html#ConfusingTernary">Confusing Ternary</a></td><td><a href="/documentation/rules.html#ConfusingTernary">ConfusingTernary</a></td><td>3272</td></tr>
<tr><td><a href="/documentation/rules.html#ICAST_BAD_SHIFT_AMOUNT">BSHIFT: 32 bit int shifted by an amount not in the range -31..31 </a></td><td><a href="/documentation/rules.html#ICAST_BAD_SHIFT_AMOUNT">ICAST_BAD_SHIFT_AMOUNT</a></td><td>8</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane" id="actions">...</div>
                  <div role="tabpanel" class="tab-pane" id="log"><br />
                    <ul class="list-group">
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
