
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>Project ease</h2>

              <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Summary</a></li>
                  <li role="presentation"><a href="#pmi" role="tab" data-toggle="tab">PMI</a></li>
                  <li role="presentation" class=""><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation" class="disabled"><a href="#attrs" role="tab" data-toggle="tab">Attributes</a></li>
                  <li role="presentation" class="disabled"><a href="#questions" role="tab" data-toggle="tab">Questions</a></li>
                  <li role="presentation"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation" class="disabled"><a href="#actions" role="tab" data-toggle="tab">Actions</a></li>
                  <li role="presentation"><a href="#log" role="tab" data-toggle="tab">Errors</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane fade in active" id="home"><br />
                    <div class="row">
                      <div class="col-sm-8">
                        <div class="panel panel-primary"><div class="panel-heading">Rating for main quality attributes</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Ecosystem Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Process Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Product Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Downloads</div><ul class="list-group"><li class="list-group-item">Project attributes: [ <a href="ease_attributes.json">JSON</a> ] [ <a href="ease_attributes.csv">CSV</a> ]</li><li class="list-group-item">Project questions: [ <a href="ease_questions.json">JSON</a> ] [ <a href="ease_questions.csv">CSV</a> ]</li><li class="list-group-item">Project metrics: [ <a href="ease_metrics.json">JSON</a> ] [ <a href="ease_metrics.csv">CSV</a> ]</li><li class="list-group-item">Project violations: [ <a href="ease_violations.json">JSON</a> ] [ <a href="ease_violations.csv">CSV</a> ]</li></ul></div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Ecosystem quality</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Activity</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Diversity</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Responsiveness</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Support</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                            <dt>Usage</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                            <dt>User feedback</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Process quality</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Configuration Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Change Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Planning Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Test Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Product quality</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Analysability</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Changeability</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Reliability</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Reusability</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="pmi"><br />
                    <dl class="dl-horizontal">
                      <dt>Description</dt>
                      <dd><p>EASE allows the execution of script code (using scripting languages such as JS, Python, ...) within the context of the Eclipse Platform/RCP. As they are running in the same JRE as Eclipse itself, these scripts have direct access to any class of your application and may interact with your workbench.</p>
<p>Through keywords within header data, scripts might be integrated seamlessly into the UI as toolbar and/or menu contributions. Thus the functionality could be extended by providing scripts only. No need to build, export and install a new feature, just provide a script and add it to your application at runtime.</p>
<p>Scripting allows to easily extend an existing application, helps in automating everyday tasks and aids in rapid prototyping during application development. </p>
<p>Following goals for the project have been defined:</p>
<ol><li>
		Execute scripts within the running IDE.</li>
<li>
		Support multiple script languages via a generic service that creates (multiple) script interpreters.</li>
<li>
		Scripts are capable of interacting with the IDE, like accessing classes on the Eclipse/JRE classpath and calling methods upon them.</li>
<li>
		Seamless integration of scripts into UI</li>
<li>
		Scripts should be attachable to toolbars and menus</li>
<li>
		Debuggers are aware of the script language/Java classes co-existence by providing variables access</li>
<li>
		Provide means to sign scripts.</li>
</ol></dd>
                      <dt>Web</dt>
                      <dd><a href=""></a></dd>
                      <dt>Wiki</dt>
                      <dd><a href=""></a></dd>
                      <dt>Downloads</dt>
                      <dd><a href=""></a></dd>
                      <dt>Documentation</dt>
                      <dd><a href=""></a></dd>
                      <dt>Getting Started</dt>
                      <dd><a href=""></a></dd>
                    </dl>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="qm">              <h3>The Quality model</h3>
            
            <p>The quality model shows the complete hierarchy tree, from <a href="/documentation/attributes.html">quality attributes</a> to <a href="/documentation/questions.html">measurement concepts</a> (questions) and <a href="/documentation/metrics.html">metrics</a>. Following Basili's Goal-Question-Metric approach [<a href="/documentation/references.html#Basili1994">Basili1994</a>], the quality attributes (the 3 first columns) are goals for our measurement, concepts (4th col) are mapped to questions, and metrics (right col) are the base measures.</p>
              <div class="row">
            <div class="col-lg-7">
        
<div id="tree"></div>

<script src="/js/d3/d3.min.js"></script>
<script>

var margin = {top: 20, right: 120, bottom: 20, left: 10},
    width = 1100 - margin.right - margin.left,
    height = 1024 - margin.top - margin.bottom;
    
var i = 0,
    duration = 750,
    root;

var tree = d3.layout.tree()
    .size([height, width]);

var diagonal = d3.svg.diagonal()
    .projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("div#tree").append("svg")
    .attr("width", width + margin.right + margin.left)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

//var mycolours = ["#fff", "#ff0000", "#cc3300", "#996600", "#669900", "#33CC00"];
var mycolours = ["#ebebeb", "#FFFF66", "#CCF24D", "#99E633", "#66D91A", "#33CC00"];

var myattrs = {};
var mymetrics = {};
var myconcepts = {};
var myvalues = new Object();

// Load file for attributes.
d3.json("../data/polarsys_attributes.json", function(error, attributes) {
  if (error) return console.warn(error);

  for(i=0;i<attributes.children.length;i++) {
    attr_mnemo = attributes.children[i]['mnemo'];
    myattrs[attr_mnemo] = attributes.children[i];
  }
});

// Load file for concepts.
d3.json("../data/polarsys_questions.json", function(error, concepts) {
  if (error) return console.warn(error);
  
  for(i=0;i<concepts.children.length;i++) {
    concept_name = concepts.children[i].mnemo;
    myconcepts[concept_name] = concepts.children[i];
  }
});

// Load file for metrics.
d3.json("../data/polarsys_metrics.json", function(error, metrics) {
  if (error) return console.warn(error);
  
  for(i=0;i<metrics.children.length;i++) {
    metric_name = metrics.children[i].mnemo;
    mymetrics[metric_name] = metrics.children[i];
  }
});

d3.json("ease_qm.json", function(error, qm) {
  if (error) return console.warn(error);

  root = qm;
  root.x0 = height / 2;
  root.y0 = 0;

  function collapse(d) {
    if (d.children) {
      d._children = d.children;
      d._children.forEach(collapse);
      d.children = null;
    }
  }

  update(root);
});

function update(source) {

  var tabs = [0, 100, 200, 400, 630, 700];

  // Compute the new tree layout.
  var nodes = tree.nodes(root).reverse(),
      links = tree.links(nodes);

  // Normalize for fixed-depth.
  nodes.forEach(function(d, i) { 
    d.y = tabs[d.depth];
  });

  // Update the nodes…
  var node = svg.selectAll("g.node")
      .data(nodes, function(d) { return d.id || (d.id = ++i); });

  // Enter any new nodes at the parent's previous position.
  var nodeEnter = node.enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
      .on("click", click);

  nodeEnter.append("circle")
      .attr("r", 1e-6)
      .style("fill", function(d) { 
        return d.ind ? mycolours[d.ind] : "gray"; 
      })
      .style("stroke", function(d) {
	  return "black";
	  //return d.ind ? mycolours[d.ind] : "gray"; 
      });

  nodeEnter.append("text")
      .attr("x", function(d) { return d.children || d._children ? -20 : 20; })
      .attr("dy", function(d) { return d.children || d._children ? "-0.5em" : ".35em" })
      .attr("text-anchor", function(d) { return d.children || d.children ? "end" : "start"; })
      .attr("fill", function(d) { return d.active == "true" ? "black" : "gray";})
      .text(function(d) { 
        return d.value ? d.name + " (" + d.value + " / " + d.ind + ")" : d.name;
      })
      .style("fill-opacity", 1e-6);

  // Transition nodes to their new position.
  var nodeUpdate = node.transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; });

  nodeUpdate.select("circle")
      .attr("r", 7)
      .style("fill", function(d) { 
        return d.ind ? mycolours[d.ind] : "lightgray"; 
      })
      .style("stroke", function(d) {
	  return "black";
      });

  nodeUpdate.select("text")
      .style("fill-opacity", 1);

  // Transition exiting nodes to the parent's new position. '
  var nodeExit = node.exit().transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
      .remove();

  nodeExit.select("circle")
      .attr("r", 1e-6);

  nodeExit.select("text")
      .style("fill-opacity", 1e-6);

  // Update the links…
  var link = svg.selectAll("path.link")
      .data(links, function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position. '
  link.enter().insert("path", "g")
      .attr("class", "link")
      .attr("d", function(d) {
        var o = {x: source.x0, y: source.y0};
        return diagonal({source: o, target: o});
      });

  // Transition links to their new position.
  link.transition()
      .duration(duration)
      .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position. '
  link.exit().transition()
      .duration(duration)
      .attr("d", function(d) {
        var o = {x: source.x, y: source.y};
        return diagonal({source: o, target: o});
      })
      .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
    d.x0 = d.x;
    d.y0 = d.y;
  });
}

// Toggle children on click.
function click(d) {

  var i = 0;
  var mynode;

  // find element in our json files (metrics, concepts, attributes of quality).
  if (typeof d.type == "undefined") {
    alert("No type defined on node.");
  } else {
    if (d.type == "metric") {
      mynode = d;
      mynode.description = mymetrics[d.mnemo]["desc"]; 
      mynode.name = mymetrics[d.mnemo]["name"]; 
//      mynode.ind = mymetrics[d.mnemo]["ind"];
//      mynode.value = mymetrics[d.mnemo]["value"];
      mynode.datasource = mymetrics[d.mnemo]["ds"]; 

      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
  
      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active.charAt(0).toUpperCase() + mynode.active.slice(1));

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Value:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(d.value + " ( " + d.ind + " )");

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Data source:")
      psource = ptitle.append('span');
      psource.classed("details", true);
      psource.text(mynode.datasource);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.html(mynode.description[desc_idx]);
      }
    } else if (d.type == "concept") {
      mynode = d;
      mynode.description = myconcepts[d.mnemo]["desc"]; 
      mynode.name = myconcepts[d.mnemo]["name"]; 
      mynode.question = myconcepts[d.mnemo]["question"]; 

      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
  
      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active);

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Value:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(d.ind);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Question:")
      var pdesc = mydiv.append('p');
      pdesc.classed("details", true);
      pdesc.text(mynode.question);
      
      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.html(mynode.description[desc_idx]);
      }
    } else if (d.type == "attribute") {
      mynode = d;
      mynode.description = myattrs[d.mnemo]["desc"]; 
      mynode.name = myattrs[d.mnemo]["name"]; 

      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
    
      var pactive = mydiv.append('p');
      ptitle = pactive.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = pactive.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active);

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Value:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(d.ind);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.text(mynode.description[desc_idx]);
      }
    
    }
  }
}

</script>
</div>
<div class="col-lg-5">
<div id="details-box-project"><p>Click on a node to get more details.</p></div>
</div> <!-- col -->
</div> <!-- row -->

                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="attrs"><br />
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="questions"><br />
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="metrics"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="20%">Mnemo</th><th width="20%">Value</th><th width="20%">Indicator</th></tr>
<tr><td><a href="/documentation/metrics.html#DL_REPO_1M">Number of downloads on the web site</a></td><td><a href="/documentation/metrics.html#DL_REPO_1M">DL_REPO_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">Number of downloads on update site</a></td><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">DL_UPDATE_SITE_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS_AUTH_1M</a></td><td>1</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>0.1370463764938055</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">ITS_FIX_MED_1M</a></td><td>0.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS_UPDATES_1M</a></td><td>54</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_FAV">Number of favourites on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_FAV">MKT_FAV</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">Number of successfull installs on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">MKT_INSTALL_SUCCESS_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">Developer ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">MLS_DEV_RESP_RATIO_1M</a></td><td>0.4444444444444444</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">Developer ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">MLS_DEV_SUBJ_1M</a></td><td>36</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">Developer ML posts</a></td><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">MLS_DEV_VOL_1M</a></td><td>52</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">User ML response time</a></td><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">MLS_USR_RESP_TIME_MED_1M</a></td><td>0.56</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA">Number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA">NCC_ANA</a></td><td>574</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA">Number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA">NCC_CHA</a></td><td>107</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL">Number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL">NCC_REL</a></td><td>265</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU">Number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU">NCC_REU</a></td><td>2517</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_MILESTONES_VOL">Number of milestones</a></td><td><a href="/documentation/metrics.html#PLAN_MILESTONES_VOL">PLAN_MILESTONES_VOL</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">Milestone success rate</a></td><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">PLAN_REVIEWS_SUCCESS_RATE</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">ITS information</a></td><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">PUB_ITS_INFO_PMI</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">SCM information</a></td><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">PUB_SCM_INFO_PMI</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_ANA">Number of violated rules for analysability</a></td><td><a href="/documentation/metrics.html#RKO_ANA">RKO_ANA</a></td><td>21</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_CHA">Number of violated rules for changeability</a></td><td><a href="/documentation/metrics.html#RKO_CHA">RKO_CHA</a></td><td>7</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REL">Number of violated rules for reliability</a></td><td><a href="/documentation/metrics.html#RKO_REL">RKO_REL</a></td><td>11</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REU">Number of violated rules for reusability</a></td><td><a href="/documentation/metrics.html#RKO_REU">RKO_REU</a></td><td>8</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_ANA">Adherence to analysability rules</a></td><td><a href="/documentation/metrics.html#ROKR_ANA">ROKR_ANA</a></td><td>66.6666666666667</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_CHA">Adherence to changeability rules</a></td><td><a href="/documentation/metrics.html#ROKR_CHA">ROKR_CHA</a></td><td>63.1578947368421</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REL">Adherence to reliability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REL">ROKR_REL</a></td><td>76.5957446808511</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REU">Adherence to reusability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REU">ROKR_REU</a></td><td>55.5555555555556</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_ANA">Number of rules for analysability</a></td><td><a href="/documentation/metrics.html#RULES_ANA">RULES_ANA</a></td><td>63</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_CHA">Number of rules for changeability</a></td><td><a href="/documentation/metrics.html#RULES_CHA">RULES_CHA</a></td><td>19</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REL">Number of rules for reliability</a></td><td><a href="/documentation/metrics.html#RULES_REL">RULES_REL</a></td><td>47</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REU">Number of rules for reusability</a></td><td><a href="/documentation/metrics.html#RULES_REU">RULES_REU</a></td><td>18</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM_COMMITS_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">SCM_COMMITTED_FILES_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM_COMMITTERS_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane fade" id="practices"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="40%">Mnemo</th><th width="20%">NCC</th></tr>
<tr><td><a href="/documentation/rules.html#CouplingBetweenObjects">Coupling Between Objects</a></td><td><a href="/documentation/rules.html#CouplingBetweenObjects">CouplingBetweenObjects</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#UnnecessaryLocalBeforeReturn">Unnecessary Local Before Return</a></td><td><a href="/documentation/rules.html#UnnecessaryLocalBeforeReturn">UnnecessaryLocalBeforeReturn</a></td><td>29</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedPrivateMethod">Unused Private Method</a></td><td><a href="/documentation/rules.html#UnusedPrivateMethod">UnusedPrivateMethod</a></td><td>13</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedFormalParameter">Unused Formal Parameter</a></td><td><a href="/documentation/rules.html#UnusedFormalParameter">UnusedFormalParameter</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#ImmutableField">Immutable Field</a></td><td><a href="/documentation/rules.html#ImmutableField">ImmutableField</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#SimpleDateFormatNeedsLocale">Simple Date Format Needs Locale</a></td><td><a href="/documentation/rules.html#SimpleDateFormatNeedsLocale">SimpleDateFormatNeedsLocale</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#FieldDeclarationsShouldBeAtStartOfClass">Field Declarations Should Be At Start Of Class</a></td><td><a href="/documentation/rules.html#FieldDeclarationsShouldBeAtStartOfClass">FieldDeclarationsShouldBeAtStartOfClass</a></td><td>100</td></tr>
<tr><td><a href="/documentation/rules.html#UseUtilityClass">UseUtilityClass</a></td><td><a href="/documentation/rules.html#UseUtilityClass">UseUtilityClass</a></td><td>14</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyIfStmt">Empty If Stmt</a></td><td><a href="/documentation/rules.html#EmptyIfStmt">EmptyIfStmt</a></td><td>8</td></tr>
<tr><td><a href="/documentation/rules.html#UncommentedEmptyConstructor">Uncommented Empty Constructor</a></td><td><a href="/documentation/rules.html#UncommentedEmptyConstructor">UncommentedEmptyConstructor</a></td><td>33</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidReassigningParameters">Avoid Reassigning Parameters</a></td><td><a href="/documentation/rules.html#AvoidReassigningParameters">AvoidReassigningParameters</a></td><td>27</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidDeeplyNestedIfStmts">Avoid Deeply Nested If Statements</a></td><td><a href="/documentation/rules.html#AvoidDeeplyNestedIfStmts">AvoidDeeplyNestedIfStmts</a></td><td>26</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedModifier">Unused Modifier</a></td><td><a href="/documentation/rules.html#UnusedModifier">UnusedModifier</a></td><td>76</td></tr>
<tr><td><a href="/documentation/rules.html#RV_RETURN_VALUE_IGNORED_BAD_PRACTICE">RV: Method ignores exceptional return value </a></td><td><a href="/documentation/rules.html#RV_RETURN_VALUE_IGNORED_BAD_PRACTICE">RV_RETURN_VALUE_IGNORED_BAD_PRACTICE</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedLocalVariable">Unused Local Variable</a></td><td><a href="/documentation/rules.html#UnusedLocalVariable">UnusedLocalVariable</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#SwitchStmtsShouldHaveDefault">Switch Statements Should Have Default</a></td><td><a href="/documentation/rules.html#SwitchStmtsShouldHaveDefault">SwitchStmtsShouldHaveDefault</a></td><td>137</td></tr>
<tr><td><a href="/documentation/rules.html#TooFewBranchesForASwitchStatement">Too Few Branches For A Switch Statement</a></td><td><a href="/documentation/rules.html#TooFewBranchesForASwitchStatement">TooFewBranchesForASwitchStatement</a></td><td>115</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyStatementNotInLoop">Empty Statement Not In Loop</a></td><td><a href="/documentation/rules.html#EmptyStatementNotInLoop">EmptyStatementNotInLoop</a></td><td>3</td></tr>
<tr><td><a href="/documentation/rules.html#FinalFieldCouldBeStatic">Final Field Could Be Static</a></td><td><a href="/documentation/rules.html#FinalFieldCouldBeStatic">FinalFieldCouldBeStatic</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidSynchronizedAtMethodLevel">Avoid Synchronized At Method Level</a></td><td><a href="/documentation/rules.html#AvoidSynchronizedAtMethodLevel">AvoidSynchronizedAtMethodLevel</a></td><td>22</td></tr>
<tr><td><a href="/documentation/rules.html#ClassWithOnlyPrivateConstructorsShouldBeFinal">Class With Only Private Constructors Should Be Final</a></td><td><a href="/documentation/rules.html#ClassWithOnlyPrivateConstructorsShouldBeFinal">ClassWithOnlyPrivateConstructorsShouldBeFinal</a></td><td>11</td></tr>
<tr><td><a href="/documentation/rules.html#ExcessiveImports">Excessive Imports</a></td><td><a href="/documentation/rules.html#ExcessiveImports">ExcessiveImports</a></td><td>12</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyCatchBlock">Empty Catch Block</a></td><td><a href="/documentation/rules.html#EmptyCatchBlock">EmptyCatchBlock</a></td><td>66</td></tr>
<tr><td><a href="/documentation/rules.html#UseCollectionIsEmpty">Use Collection isEmpty</a></td><td><a href="/documentation/rules.html#UseCollectionIsEmpty">UseCollectionIsEmpty</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedPrivateField">Unused Private Field</a></td><td><a href="/documentation/rules.html#UnusedPrivateField">UnusedPrivateField</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#UncommentedEmptyMethod">Uncommented Empty Method</a></td><td><a href="/documentation/rules.html#UncommentedEmptyMethod">UncommentedEmptyMethod</a></td><td>20</td></tr>
<tr><td><a href="/documentation/rules.html#CollapsibleIfStatements">Collapsible If Statements</a></td><td><a href="/documentation/rules.html#CollapsibleIfStatements">CollapsibleIfStatements</a></td><td>23</td></tr>
<tr><td><a href="/documentation/rules.html#PreserveStackTrace">Preserve Stack Trace</a></td><td><a href="/documentation/rules.html#PreserveStackTrace">PreserveStackTrace</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#SingularField">Singular Field</a></td><td><a href="/documentation/rules.html#SingularField">SingularField</a></td><td>9</td></tr>
<tr><td><a href="/documentation/rules.html#NonStaticInitializer">Non Static Initializer</a></td><td><a href="/documentation/rules.html#NonStaticInitializer">NonStaticInitializer</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#DM_DEFAULT_ENCODING">Dm: Reliance on default encoding </a></td><td><a href="/documentation/rules.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td><td>21</td></tr>
<tr><td><a href="/documentation/rules.html#ReturnEmptyArrayRatherThanNull">Return Empty Array Rather Than Null</a></td><td><a href="/documentation/rules.html#ReturnEmptyArrayRatherThanNull">ReturnEmptyArrayRatherThanNull</a></td><td>3</td></tr>
<tr><td><a href="/documentation/rules.html#IS2_INCONSISTENT_SYNC">IS: Inconsistent synchronization </a></td><td><a href="/documentation/rules.html#IS2_INCONSISTENT_SYNC">IS2_INCONSISTENT_SYNC</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#CompareObjectsWithEquals">Compare Objects With Equals</a></td><td><a href="/documentation/rules.html#CompareObjectsWithEquals">CompareObjectsWithEquals</a></td><td>13</td></tr>
<tr><td><a href="/documentation/rules.html#ConstructorCallsOverridableMethod">Constructor Calls Overridable Method</a></td><td><a href="/documentation/rules.html#ConstructorCallsOverridableMethod">ConstructorCallsOverridableMethod</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#OverrideBothEqualsAndHashcode">Override Both Equals And Hash code</a></td><td><a href="/documentation/rules.html#OverrideBothEqualsAndHashcode">OverrideBothEqualsAndHashcode</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#ConfusingTernary">Confusing Ternary</a></td><td><a href="/documentation/rules.html#ConfusingTernary">ConfusingTernary</a></td><td>82</td></tr>
<tr><td><a href="/documentation/rules.html#AccessorClassGeneration">Accessor Class Generation</a></td><td><a href="/documentation/rules.html#AccessorClassGeneration">AccessorClassGeneration</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#NonThreadSafeSingleton">Non Thread Safe Singleton</a></td><td><a href="/documentation/rules.html#NonThreadSafeSingleton">NonThreadSafeSingleton</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#LooseCoupling">Loose Coupling</a></td><td><a href="/documentation/rules.html#LooseCoupling">LooseCoupling</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#AssignmentToNonFinalStatic">Assignment To Non Final Static</a></td><td><a href="/documentation/rules.html#AssignmentToNonFinalStatic">AssignmentToNonFinalStatic</a></td><td>8</td></tr>
<tr><td><a href="/documentation/rules.html#MissingBreakInSwitch">Missing Break In Switch</a></td><td><a href="/documentation/rules.html#MissingBreakInSwitch">MissingBreakInSwitch</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#GodClass">God Class</a></td><td><a href="/documentation/rules.html#GodClass">GodClass</a></td><td>16</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyMethodInAbstractClassShouldBeAbstract">Empty Method In Abstract Class Should Be Abstract</a></td><td><a href="/documentation/rules.html#EmptyMethodInAbstractClassShouldBeAbstract">EmptyMethodInAbstractClassShouldBeAbstract</a></td><td>10</td></tr>
<tr><td><a href="/documentation/rules.html#MS_PKGPROTECT">MS: Field should be package protected </a></td><td><a href="/documentation/rules.html#MS_PKGPROTECT">MS_PKGPROTECT</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#MS_SHOULD_BE_FINAL">MS: Field isn't final but should be </a></td><td><a href="/documentation/rules.html#MS_SHOULD_BE_FINAL">MS_SHOULD_BE_FINAL</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#LawOfDemeter">LawOfDemeter</a></td><td><a href="/documentation/rules.html#LawOfDemeter">LawOfDemeter</a></td><td>2456</td></tr>
<tr><td><a href="/documentation/rules.html#BC_IMPOSSIBLE_CAST">BC: Impossible cast </a></td><td><a href="/documentation/rules.html#BC_IMPOSSIBLE_CAST">BC_IMPOSSIBLE_CAST</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidConstantsInterface">Avoid Constants Interface</a></td><td><a href="/documentation/rules.html#AvoidConstantsInterface">AvoidConstantsInterface</a></td><td>16</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane fade" id="actions">...</div>
                  <div role="tabpanel" class="tab-pane fade" id="log"><br />
                    <ul class="list-group">
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find attributes file [../../samples//ease/ease_attributes.json] for [ease].</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find questions file [../../samples//ease/ease_attributes.json] for [ease].</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
