
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2 class="page-header">Project example</h2>

              <div class="tabbable">
                <ul class="nav nav-pills" role="tablist">
                  <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">PMI</a></li>
                  <li role="presentation"><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation"><a href="#actions" role="tab" data-toggle="tab">Actions</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="home"><br />
                    <dl class="dl-horizontal">
                      <dt>Description</dt>
                      <dd><p>The CDT Project provides a fully functional C and C++ Integrated Development Environment based on the Eclipse platform. Features include: support for project creation and managed build for various toolchains, standard make build, source navigation, various source knowledge tools, such as type hierarchy, call graph, include browser, macro definition browser, code editor with syntax highlighting, folding and hyperlink navigation, source code refactoring and code generation, visual debugging tools, including memory, registers, and disassembly viewers.</p>
</dd>
                      <dt>Web</dt>
                      <dd><a href="http://www.eclipse.org/cdt">http://www.eclipse.org/cdt</a></dd>
                      <dt>Wiki</dt>
                      <dd><a href="http://wiki.eclipse.org/index.php/CDT">http://wiki.eclipse.org/index.php/CDT</a></dd>
                      <dt>Downloads</dt>
                      <dd><a href="http://www.eclipse.org/cdt/downloads.php">http://www.eclipse.org/cdt/downloads.php</a></dd>
                      <dt>Documentation</dt>
                      <dd><a href="http://wiki.eclipse.org/index.php/CDT">http://wiki.eclipse.org/index.php/CDT</a></dd>
                      <dt>Getting Started</dt>
                      <dd><a href="http://dev.eclipse.org/viewcvs/indextools.cgi/%7Echeckout%7E/cdt-home/user/Tutorials.html">http://dev.eclipse.org/viewcvs/indextools.cgi/%7Echeckout%7E/cdt-home/user/Tutorials.html</a></dd>
                    </dl>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="qm">...</div>
                  <div role="tabpanel" class="tab-pane" id="metrics"><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/metrics.html#COMR">Comment rate</a></td><td><a href="/documentation/metrics.html#COMR">COMR</a></td><td>16.4</td></tr>
<tr><td><a href="/documentation/metrics.html#DL_REPO_1M">Number of downloads on the web site</a></td><td><a href="/documentation/metrics.html#DL_REPO_1M">DL_REPO_1M</a></td><td>572801</td></tr>
<tr><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">Number of downloads on update site</a></td><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">DL_UPDATE_SITE_1M</a></td><td>3359</td></tr>
<tr><td><a href="/documentation/metrics.html#FU_CLONE">Function cloning</a></td><td><a href="/documentation/metrics.html#FU_CLONE">FU_CLONE</a></td><td>115314</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS_AUTH_1M</a></td><td>55</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>0.08530612869851283</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">ITS_FIX_MED_1M</a></td><td>14.95</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS_UPDATES_1M</a></td><td>237</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_FAV">Number of favourites on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_FAV">MKT_FAV</a></td><td>7</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">Number of failed install on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">MKT_INSTALL_FAILED_1M</a></td><td>301</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">Number of successfull installs on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">MKT_INSTALL_SUCCESS_1M</a></td><td>3058</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_AUTH_1M">Developer ML authors</a></td><td><a href="/documentation/metrics.html#MLS_DEV_AUTH_1M">MLS_DEV_AUTH_1M</a></td><td>32</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">Developer ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">MLS_DEV_RESP_RATIO_1M</a></td><td>2.71875</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">Developer ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">MLS_DEV_SUBJ_1M</a></td><td>32</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">Developer ML posts</a></td><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">MLS_DEV_VOL_1M</a></td><td>119</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA">Number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA">NCC_ANA</a></td><td>28410</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA_IDX">Non conformities index for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA_IDX">NCC_ANA_IDX</a></td><td>31.07</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA">Number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA">NCC_CHA</a></td><td>5153</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA_IDX">Non conformities index for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA_IDX">NCC_CHA_IDX</a></td><td>5.63</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL">Number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL">NCC_REL</a></td><td>7183</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL_IDX">Non conformities index for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL_IDX">NCC_REL_IDX</a></td><td>7.86</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU">Number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU">NCC_REU</a></td><td>139754</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU_IDX">Non conformities index for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU_IDX">NCC_REU_IDX</a></td><td>152.84</td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_MILESTONES_VOL">Number of milestones</a></td><td><a href="/documentation/metrics.html#PLAN_MILESTONES_VOL">PLAN_MILESTONES_VOL</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">Milestone success rate</a></td><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">PLAN_REVIEWS_SUCCESS_RATE</a></td><td>40</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">ITS information</a></td><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">PUB_ITS_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">SCM information</a></td><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">PUB_SCM_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_ANA">Number of violated rules for analysability</a></td><td><a href="/documentation/metrics.html#RKO_ANA">RKO_ANA</a></td><td>46</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_CHA">Number of violated rules for changeability</a></td><td><a href="/documentation/metrics.html#RKO_CHA">RKO_CHA</a></td><td>14</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REL">Number of violated rules for reliability</a></td><td><a href="/documentation/metrics.html#RKO_REL">RKO_REL</a></td><td>21</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REU">Number of violated rules for reusability</a></td><td><a href="/documentation/metrics.html#RKO_REU">RKO_REU</a></td><td>13</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_ANA">Adherence to analysability rules</a></td><td><a href="/documentation/metrics.html#ROKR_ANA">ROKR_ANA</a></td><td>26.984126984127</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_CHA">Adherence to changeability rules</a></td><td><a href="/documentation/metrics.html#ROKR_CHA">ROKR_CHA</a></td><td>26.3157894736842</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REL">Adherence to reliability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REL">ROKR_REL</a></td><td>55.3191489361702</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REU">Adherence to reusability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REU">ROKR_REU</a></td><td>27.7777777777778</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_ANA">Number of rules for analysability</a></td><td><a href="/documentation/metrics.html#RULES_ANA">RULES_ANA</a></td><td>63</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_CHA">Number of rules for changeability</a></td><td><a href="/documentation/metrics.html#RULES_CHA">RULES_CHA</a></td><td>19</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REL">Number of rules for reliability</a></td><td><a href="/documentation/metrics.html#RULES_REL">RULES_REL</a></td><td>47</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REU">Number of rules for reusability</a></td><td><a href="/documentation/metrics.html#RULES_REU">RULES_REU</a></td><td>18</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM_COMMITS_1M</a></td><td>112</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">SCM_COMMITTED_FILES_1M</a></td><td>301</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM_COMMITTERS_1M</a></td><td>18</td></tr>
<tr><td><a href="/documentation/metrics.html#SLOC">Source Lines Of Code</a></td><td><a href="/documentation/metrics.html#SLOC">SLOC</a></td><td>914354</td></tr>
<tr><td><a href="/documentation/metrics.html#TST_COV_LINES">Percentage of lines of code covered by tests</a></td><td><a href="/documentation/metrics.html#TST_COV_LINES">TST_COV_LINES</a></td><td>63.18</td></tr>
<tr><td><a href="/documentation/metrics.html#VG">Cyclomatic Complexity</a></td><td><a href="/documentation/metrics.html#VG">VG</a></td><td>225705</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane" id="practices"><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane" id="actions">...</div>
                </div>
              </div>
            </div>
          </div>
        </div>
