
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>Project gendoc</h2>

              <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Summary</a></li>
                  <li role="presentation"><a href="#pmi" role="tab" data-toggle="tab">PMI</a></li>
                  <li role="presentation" class="disabled"><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation"><a href="#attrs" role="tab" data-toggle="tab">Attributes</a></li>
                  <li role="presentation" class="disabled"><a href="#questions" role="tab" data-toggle="tab">Questions</a></li>
                  <li role="presentation" class="disabled"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation" class="disabled"><a href="#actions" role="tab" data-toggle="tab">Actions</a></li>
                  <li role="presentation"><a href="#log" role="tab" data-toggle="tab">Errors</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane active" id="home"><br />
                    <div class="row">
                      <div class="col-lg-8">
                        <div class="panel panel-default"><div class="panel-heading">Rating for main quality attributes</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 80%;">4 / 5</div></div></dd>
                            <dt>Ecosystem Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3 / 5</div></div></dd>
                            <dt>Process Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3 / 5</div></div></dd>
                            <dt>Product Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 40%;">2 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-4">
                        <div class="panel panel-default"><div class="panel-heading">Downloads</div><ul class="list-group"><li class="list-group-item">Project attributes: [ <a href="gendoc_attributes.json">JSON</a> ] [ <a href="gendoc_attributes.csv">CSV</a> ]</li><li class="list-group-item">Project questions: [ <a href="gendoc_questions.json">JSON</a> ] [ <a href="gendoc_questions.csv">CSV</a> ]</li><li class="list-group-item">Project metrics: [ <a href="gendoc_metrics.json">JSON</a> ] [ <a href="gendoc_metrics.csv">CSV</a> ]</li><li class="list-group-item">Project violations: [ <a href="gendoc_violations.json">JSON</a> ] [ <a href="gendoc_violations.csv">CSV</a> ]</li></ul></div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-lg-4">
                        <div class="panel panel-default"><div class="panel-heading">Rating for main quality attributes</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Activity</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #33CC00;width: 100%;">5 / 5</div></div></dd>
                            <dt>Diversity</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 80%;">4 / 5</div></div></dd>
                            <dt>Responsiveness</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3 / 5</div></div></dd>
                            <dt>Support</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 40%;">2 / 5</div></div></dd>
                            </dl>
                            <dt>Usage</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 40%;">2 / 5</div></div></dd>
                            </dl>
                            <dt>User feedback</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 80%;">4 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-4">
                        <div class="panel panel-default"><div class="panel-heading">Rating for main quality attributes</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Configuration Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #33CC00;width: 100%;">5 / 5</div></div></dd>
                            <dt>Change Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 80%;">4 / 5</div></div></dd>
                            <dt>Planning Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3 / 5</div></div></dd>
                            <dt>Test Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 40%;">2 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-4">
                        <div class="panel panel-default"><div class="panel-heading">Rating for main quality attributes</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 80%;">4 / 5</div></div></dd>
                            <dt>Ecosystem Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3 / 5</div></div></dd>
                            <dt>Process Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3 / 5</div></div></dd>
                            <dt>Product Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 40%;">2 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                    </div>
                    <h4>Main caracteristics</h4><p>Gendoc extracts data from EMF models and generates documents that fully respect the appearance of your document template.</p>
<p>The generation can be performed in a few steps:</p>
<table><tbody><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/1.png" /></td>
<td>
				Get or write a standard template document in OpenOffice Writer (.odt) or Microsoft Word (.docx) format,</td>
</tr><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/2.png" /></td>
<td>
				Add script sections to get dynamic content from models : each dynamic section of the template contains a script written in M2T Acceleo language,</td>
</tr><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/3.png" /></td>
<td>
				Reference the model as datasource,</td>
</tr><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/4.png" /></td>
<td>
				Launch the generation directly from the template</td>
</tr><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/5.png" /></td>
<td>
				The generation result fully respects the template document, with all dynamic sections filled with model content</td>
</tr></tbody></table><p><img src="http://www.eclipse.org/proposals/modeling.gendoc/gendoc_generation_details.png" style="height: 360px; width: 481px;" /></p>
<p>Styles defined in the template are kept after generation, both on static and dynamic parts.</p>
<p>Gendoc is currently used in several contexts (avionics, space, public services) to produce various kinds of documentation:</p>
<ul><li>
		Specification or design document from UML or SysML models</li>
<li>
		Requirement document from Req-IF models</li>
<li>
		Test plan from a model containing Test scenarii</li>
<li>
		Interface configuration document</li>
<li>
		Data structure description from specific EMF models</li>
</ul><h4>Project rating</h4><h4>Errors during the analysis</h4>
                    <ul class="list-group">
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find questions file [../../samples//gendoc/gendoc_attributes.json] for [gendoc].</li>
                    </ul>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="pmi"><br />
                    <dl class="dl-horizontal">
                      <dt>Description</dt>
                      <dd><p>Gendoc extracts data from EMF models and generates documents that fully respect the appearance of your document template.</p>
<p>The generation can be performed in a few steps:</p>
<table><tbody><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/1.png" /></td>
<td>
				Get or write a standard template document in OpenOffice Writer (.odt) or Microsoft Word (.docx) format,</td>
</tr><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/2.png" /></td>
<td>
				Add script sections to get dynamic content from models : each dynamic section of the template contains a script written in M2T Acceleo language,</td>
</tr><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/3.png" /></td>
<td>
				Reference the model as datasource,</td>
</tr><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/4.png" /></td>
<td>
				Launch the generation directly from the template</td>
</tr><tr><td>
				<img src="http://www.eclipse.org/proposals/modeling.gendoc/5.png" /></td>
<td>
				The generation result fully respects the template document, with all dynamic sections filled with model content</td>
</tr></tbody></table><p><img src="http://www.eclipse.org/proposals/modeling.gendoc/gendoc_generation_details.png" style="height: 360px; width: 481px;" /></p>
<p>Styles defined in the template are kept after generation, both on static and dynamic parts.</p>
<p>Gendoc is currently used in several contexts (avionics, space, public services) to produce various kinds of documentation:</p>
<ul><li>
		Specification or design document from UML or SysML models</li>
<li>
		Requirement document from Req-IF models</li>
<li>
		Test plan from a model containing Test scenarii</li>
<li>
		Interface configuration document</li>
<li>
		Data structure description from specific EMF models</li>
</ul></dd>
                      <dt>Web</dt>
                      <dd><a href=""></a></dd>
                      <dt>Wiki</dt>
                      <dd><a href=""></a></dd>
                      <dt>Downloads</dt>
                      <dd><a href=""></a></dd>
                      <dt>Documentation</dt>
                      <dd><a href=""></a></dd>
                      <dt>Getting Started</dt>
                      <dd><a href=""></a></dd>
                    </dl>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="qm">
                  </div>
                  <div role="tabpanel" class="tab-pane" id="attrs"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/attributes.html#QM_ACTIVITY">Activity</a></td><td><a href="/documentation/attributes.html#QM_ACTIVITY">QM_ACTIVITY</a></td><td>5</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ANA">Analysability</a></td><td><a href="/documentation/attributes.html#QM_ANA">QM_ANA</a></td><td>5</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_CHA">Changeability</a></td><td><a href="/documentation/attributes.html#QM_CHA">QM_CHA</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_DIVERSITY">Diversity</a></td><td><a href="/documentation/attributes.html#QM_DIVERSITY">QM_DIVERSITY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ECOSYSTEM">Ecosystem</a></td><td><a href="/documentation/attributes.html#QM_ECOSYSTEM">QM_ECOSYSTEM</a></td><td>3</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_FEEDBACK">User feedback</a></td><td><a href="/documentation/attributes.html#QM_FEEDBACK">QM_FEEDBACK</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ITS">Change Management</a></td><td><a href="/documentation/attributes.html#QM_ITS">QM_ITS</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PLAN">Planning Management</a></td><td><a href="/documentation/attributes.html#QM_PLAN">QM_PLAN</a></td><td>3</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PROCESS">Process</a></td><td><a href="/documentation/attributes.html#QM_PROCESS">QM_PROCESS</a></td><td>3</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PRODUCT">Product</a></td><td><a href="/documentation/attributes.html#QM_PRODUCT">QM_PRODUCT</a></td><td>2</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_QUALITY">Project Quality</a></td><td><a href="/documentation/attributes.html#QM_QUALITY">QM_QUALITY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_REL">Reliability</a></td><td><a href="/documentation/attributes.html#QM_REL">QM_REL</a></td><td>2</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_RESPONSIVENESS">Responsiveness</a></td><td><a href="/documentation/attributes.html#QM_RESPONSIVENESS">QM_RESPONSIVENESS</a></td><td>3</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_REU">Reusability</a></td><td><a href="/documentation/attributes.html#QM_REU">QM_REU</a></td><td>1</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_SCM">Configuration Management</a></td><td><a href="/documentation/attributes.html#QM_SCM">QM_SCM</a></td><td>5</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_SUPPORT">Support</a></td><td><a href="/documentation/attributes.html#QM_SUPPORT">QM_SUPPORT</a></td><td>2</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_TST">Test Management</a></td><td><a href="/documentation/attributes.html#QM_TST">QM_TST</a></td><td>2</td></tr>
<tr><td><a href="/documentation/attributes.html#QM_USAGE">Usage</a></td><td><a href="/documentation/attributes.html#QM_USAGE">QM_USAGE</a></td><td>2</td></tr>
</table>


                  </div>
                  <div role="tabpanel" class="tab-pane" id="questions"><br />
                  </div>
                  <div role="tabpanel" class="tab-pane" id="metrics"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS_AUTH_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>500</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">ITS_FIX_MED_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS_UPDATES_1M</a></td><td>1</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM_COMMITS_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">SCM_COMMITTED_FILES_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM_COMMITTERS_1M</a></td><td>0</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane" id="practices"><br /></div>
                  <div role="tabpanel" class="tab-pane" id="actions">...</div>
                  <div role="tabpanel" class="tab-pane" id="log"><br />
                    <ul class="list-group">
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find questions file [../../samples//gendoc/gendoc_attributes.json] for [gendoc].</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find violations file [../../samples//gendoc/gendoc_violations.json] for [gendoc].</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
