
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>Project papyrus</h2>

              <div class="tabbable">
                <ul class="nav nav-pills" role="tablist">
                  <!-- li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Summary</a></li -->
                  <li role="presentation" class="active"><a href="#pmi" role="tab" data-toggle="tab">PMI</a></li>
                  <li role="presentation"><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation" class="disabled"><a href="#attrs" role="tab" data-toggle="tab">Attributes</a></li>
                  <li role="presentation" class="disabled"><a href="#questions" role="tab" data-toggle="tab">Questions</a></li>
                  <li role="presentation"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation"><a href="#actions" role="tab" data-toggle="tab">Actions</a></li>
                  <li role="presentation"><a href="#log" role="tab" data-toggle="tab">Errors</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <!-- div role="tabpanel" class="tab-pane active" id="home"><br />...
                  </div -->
                  <div role="tabpanel" class="tab-pane active" id="pmi"><br />
                    <dl class="dl-horizontal">
                      <dt>Description</dt>
                      <dd><p>Papyrus is a component of the Model Development Tools (MDT) subproject aiming at providing an integrated, user-consumable environment for editing any kind of EMF model and particularly supporting UML and related modeling languages such as SysML and MARTE. Papyrus provides diagram editors for EMF-based modeling languages amongst them UML 2 and SysML and the glue required for integrating these editors (GMF-based or not) with other MBD and MDSD tools. It also offers a very advanced support of UML profiles that enables users to define editors for DSLs based on the UML 2 standard and its extension mechanisms. The main feature of Papyrus regarding this latter point is a set of very powerful customization mechanisms which can be leveraged to create user-defined Papyrus perspectives and give it the same look and feel as a native DSL editor.<br />
 <br />
For more details on Papyrus, see the <a href="http://www.eclipse.org/papyrus">home page</a> or the <a href="http://wiki.eclipse.org/MDT/Papyrus">Wiki</a>.</p>
</dd>
                      <dt>Web</dt>
                      <dd><a href="http://www.eclipse.org/papyrus">http://www.eclipse.org/papyrus</a></dd>
                      <dt>Wiki</dt>
                      <dd><a href="http://wiki.eclipse.org/MDT/Papyrus">http://wiki.eclipse.org/MDT/Papyrus</a></dd>
                      <dt>Downloads</dt>
                      <dd><a href="http://www.eclipse.org/modeling/mdt/papyrus/downloads/">http://www.eclipse.org/modeling/mdt/papyrus/downloads/</a></dd>
                      <dt>Documentation</dt>
                      <dd><a href="http://www.eclipse.org/modeling/mdt/papyrus/usersCorner/usersCornerIndex.php">http://www.eclipse.org/modeling/mdt/papyrus/usersCorner/usersCornerIndex.php</a></dd>
                      <dt>Getting Started</dt>
                      <dd><a href="http://www.eclipse.org/papyrus/updates/index.php">http://www.eclipse.org/papyrus/updates/index.php</a></dd>
                    </dl>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="qm">...</div>
                  <div role="tabpanel" class="tab-pane" id="attrs"><br />
                  </div>
                  <div role="tabpanel" class="tab-pane" id="questions"><br />
                  </div>
                  <div role="tabpanel" class="tab-pane" id="metrics"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/metrics.html#DL_REPO_1M">Number of downloads on the web site</a></td><td><a href="/documentation/metrics.html#DL_REPO_1M">DL_REPO_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">Number of downloads on update site</a></td><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">DL_UPDATE_SITE_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS_AUTH_1M</a></td><td>41</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>0.03</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">ITS_FIX_MED_1M</a></td><td>33.67</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS_UPDATES_1M</a></td><td>243</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_FAV">Number of favourites on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_FAV">MKT_FAV</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">Number of failed install on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">MKT_INSTALL_FAILED_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">Number of successfull installs on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">MKT_INSTALL_SUCCESS_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">Developer ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">MLS_DEV_RESP_RATIO_1M</a></td><td>2.64</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">Developer ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">MLS_DEV_SUBJ_1M</a></td><td>11</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">Developer ML posts</a></td><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">MLS_DEV_VOL_1M</a></td><td>40</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">User ML response time</a></td><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">MLS_USR_RESP_TIME_MED_1M</a></td><td>0.02</td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">Milestone success rate</a></td><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">PLAN_REVIEWS_SUCCESS_RATE</a></td><td>33</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">ITS information</a></td><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">PUB_ITS_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">SCM information</a></td><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">PUB_SCM_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM_COMMITS_1M</a></td><td>34</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">SCM_COMMITTED_FILES_1M</a></td><td>635</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM_COMMITTERS_1M</a></td><td>8</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane" id="practices"><br /></div>
                  <div role="tabpanel" class="tab-pane" id="actions">...</div>
                  <div role="tabpanel" class="tab-pane" id="log"><br />
                    <ul class="list-group">
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find attributes file [../../samples//papyrus/papyrus_attributes.json] for [papyrus].</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find questions file [../../samples//papyrus/papyrus_attributes.json] for [papyrus].</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find violations file [../../samples//papyrus/papyrus_violations.json] for [papyrus].</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
