
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>Project papyrus</h2>

              <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Summary</a></li>
                  <li role="presentation" class=""><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation"><a href="#attrs" role="tab" data-toggle="tab">Attributes</a></li>
                  <li role="presentation"><a href="#questions" role="tab" data-toggle="tab">Questions</a></li>
                  <li role="presentation"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation" class="disabled"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                    Download <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li role="presentation"><a href="papyrus_attributes.json">Attributes JSON</a></li>
                      <li role="presentation"><a href="papyrus_attributes.csv">Attributes CSV</a></li>
                      <li role="presentation"><a href="papyrus_questions.json">Questions JSON</a></li>
                      <li role="presentation"><a href="papyrus_questions.csv">Questions CSV</a></li>
                      <li role="presentation"><a href="papyrus_metrics.json">Metrics JSON</a></li>
                      <li role="presentation"><a href="papyrus_metrics.csv">Metrics CSV</a></li>
                      <!-- li role="presentation"><a href="papyrus_violations.csv">Violations JSON</a></li -->
                      <li role="presentation"><a href="papyrus_attributes.csv">Violations CSV</a></li>
                    </ul>
                  </li>
                  <li role="presentation"><a href="#log" role="tab" data-toggle="tab">Errors</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane fade in active" id="home"><br />
                    <div class="row">
                      <div class="col-sm-6">
                        <dl class="dl-vertical">
                        <dt>Description</dt>
                        <dd></dd>
                        </dl>
                      </div>
                      <div class="col-sm-6">
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-8">
                        <div class="panel panel-primary"><div class="panel-heading">Rating for main quality attributes</div>
                          <div class="panel-body">
                            <dl>
                  <dt>Overall Maturity <span class="pull-right">( 30 / 45 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="2.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 50%;">2.5 / 5</div>
                    </div>
                  </dd>
                  <dt>Ecosystem Quality <span class="pull-right">( 11 / 13 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="1.9" aria-valuemin="0" aria-valuemax="5"  style="background-color: #FFFF66;width: 38%;">1.9 / 5</div>
                    </div>
                  </dd>
                  <dt>Process Quality <span class="pull-right">( 8 / 12 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 64%;">3.2 / 5</div>
                    </div>
                  </dd>
                  <dt>Product Quality <span class="pull-right">( 11 / 20 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="2.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 50%;">2.5 / 5</div>
                    </div>
                  </dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Summary</div>
                        <ul class="list-group">
                          <li class="list-group-item"><span class="glyphicon glyphicon-globe"></span> Web <a href="http://www.eclipse.org/papyrus">http://www.eclipse.org/papyrus</a></li>
                          <li class="list-group-item"><span class="glyphicon glyphicon-globe"></span> Wiki <a href="http://wiki.eclipse.org/MDT/Papyrus">http://wiki.eclipse.org/MDT/Papyrus</a></li>
                          <li class="list-group-item"><span class="glyphicon glyphicon-download"></span> Downloads <a href="http://www.eclipse.org/modeling/mdt/papyrus/downloads/">http://www.eclipse.org/modeling/mdt/papyrus/downloads/</a></li>
                          <li class="list-group-item"><span class="glyphicon glyphicon-question-sign"></span> Documentation <a href="http://www.eclipse.org/modeling/mdt/papyrus/usersCorner/usersCornerIndex.php">http://www.eclipse.org/modeling/mdt/papyrus/usersCorner/usersCornerIndex.php</a></dd>
                          <li class="list-group-item"><span class="glyphicon glyphicon-question-sign"></span> Getting Started <a href="http://www.eclipse.org/papyrus/updates/index.php">http://www.eclipse.org/papyrus/updates/index.php</a></dd>
                        </ul>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Ecosystem quality</div>
                          <div class="panel-body">
                            <dl>
                  <dt>Activity <span class="pull-right">( 4 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="1.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #FFFF66;width: 20%;">1.0 / 5</div>
                    </div>
                  </dd>
                  <dt>Diversity <span class="pull-right">( 1 / 3 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="1.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #FFFF66;width: 20%;">1.0 / 5</div>
                    </div>
                  </dd>
                  <dt>Responsiveness <span class="pull-right">( 2 / 2 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="5.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #33CC00;width: 100%;">5.0 / 5</div>
                    </div>
                  </dd>
                  <dt>Support <span class="pull-right">( 4 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="2.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 50%;">2.5 / 5</div>
                    </div>
                  </dd></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Process quality</div>
                          <div class="panel-body">
                            <dl>
                  <dt>Configuration Management <span class="pull-right">( 3 / 3 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3.0 / 5</div>
                    </div>
                  </dd>
                  <dt>Change Management <span class="pull-right">( 3 / 3 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3.0 / 5</div>
                    </div>
                  </dd>
                  <dt>Planning Management <span class="pull-right">( 2 / 2 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 70%;">3.5 / 5</div>
                    </div>
                  </dd>
                  <dt>Test Management <span class="pull-right">( 0 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div>
                    </div>
                  </dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Product quality</div>
                          <div class="panel-body">
                            <dl>
                  <dt>Analysability <span class="pull-right">( 2 / 5 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="2.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 40%;">2.0 / 5</div>
                    </div>
                  </dd>
                  <dt>Changeability <span class="pull-right">( 2 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="2.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 50%;">2.5 / 5</div>
                    </div>
                  </dd>
                  <dt>Reliability <span class="pull-right">( 5 / 7 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 64%;">3.2 / 5</div>
                    </div>
                  </dd>
                  <dt>Reusability <span class="pull-right">( 2 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="2.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #CCF24D;width: 50%;">2.5 / 5</div>
                    </div>
                  </dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="qm">              <h3>The Quality model</h3>
            
            <p>The quality model shows the complete hierarchy tree, from <a href="/documentation/attributes.html">quality attributes</a> to <a href="/documentation/questions.html">measurement concepts</a> (questions) and <a href="/documentation/metrics.html">metrics</a>. Following Basili's Goal-Question-Metric approach [<a href="/documentation/references.html#Basili1994">Basili1994</a>], the quality attributes (the 3 first columns) are goals for our measurement, concepts (4th col) are mapped to questions, and metrics (right col) are the base measures.</p>
              <div class="row">
            <div class="col-lg-7">
        
<div id="tree"></div>

<script src="/js/d3/d3.min.js"></script>
<script>

var margin = {top: 20, right: 120, bottom: 20, left: 10},
    width = 1100 - margin.right - margin.left,
    height = 1024 - margin.top - margin.bottom;
    
var i = 0,
    duration = 750,
    root;

var tree = d3.layout.tree()
    .size([height, width]);

var diagonal = d3.svg.diagonal()
    .projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("div#tree").append("svg")
    .attr("width", width + margin.right + margin.left)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

//var mycolours = ["#fff", "#ff0000", "#cc3300", "#996600", "#669900", "#33CC00"];
var mycolours = ["#ebebeb", "#FFFF66", "#CCF24D", "#99E633", "#66D91A", "#33CC00"];

var myattrs = {};
var mymetrics = {};
var myconcepts = {};
var myvalues = new Object();

// Load file for attributes.
d3.json("../data/polarsys_attributes.json", function(error, attributes) {
  if (error) return console.warn(error);

  for(i=0;i<attributes.children.length;i++) {
    attr_mnemo = attributes.children[i]['mnemo'];
    myattrs[attr_mnemo] = attributes.children[i];
  }
});

// Load file for concepts.
d3.json("../data/polarsys_questions.json", function(error, concepts) {
  if (error) return console.warn(error);
  
  for(i=0;i<concepts.children.length;i++) {
    concept_name = concepts.children[i].mnemo;
    myconcepts[concept_name] = concepts.children[i];
  }
});

// Load file for metrics.
d3.json("../data/polarsys_metrics.json", function(error, metrics) {
  if (error) return console.warn(error);
  
  for(i=0;i<metrics.children.length;i++) {
    metric_name = metrics.children[i].mnemo;
    mymetrics[metric_name] = metrics.children[i];
  }
});

d3.json("papyrus_qm.json", function(error, qm) {
  if (error) return console.warn(error);

  root = qm;
  root.x0 = height / 2;
  root.y0 = 0;

  function collapse(d) {
    if (d.children) {
      d._children = d.children;
      d._children.forEach(collapse);
      d.children = null;
    }
  }

  update(root);
});

function update(source) {

  var tabs = [0, 100, 200, 400, 630, 700];

  // Compute the new tree layout.
  var nodes = tree.nodes(root).reverse(),
      links = tree.links(nodes);

  // Normalize for fixed-depth.
  nodes.forEach(function(d, i) { 
    d.y = tabs[d.depth];
  });

  // Update the nodes…
  var node = svg.selectAll("g.node")
      .data(nodes, function(d) { return d.id || (d.id = ++i); });

  // Enter any new nodes at the parent's previous position.
  var nodeEnter = node.enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
      .on("click", click);

  nodeEnter.append("circle")
      .attr("r", 1e-6)
      .style("fill", function(d) { 
        return d.ind ? mycolours[Math.floor(d.ind)] : "gray"; 
      })
      .style("stroke", function(d) {
	  return "black";
	  //return d.ind ? mycolours[d.ind] : "gray"; 
      });

  nodeEnter.append("text")
      .attr("x", function(d) { return d.children || d._children ? -20 : 20; })
      .attr("dy", function(d) { return d.children || d._children ? "-0.5em" : ".35em" })
      .attr("text-anchor", function(d) { return d.children || d.children ? "end" : "start"; })
      .attr("fill", function(d) { return d.active == "true" ? "black" : "gray";})
      .text(function(d) { 
        return d.value ? d.name + " (" + d.value + " / " + d.ind + ")" : d.name;
      })
      .style("fill-opacity", 1e-6);

  // Transition nodes to their new position.
  var nodeUpdate = node.transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; });

  nodeUpdate.select("circle")
      .attr("r", 7)
      .style("fill", function(d) { 
        return d.ind ? mycolours[Math.floor(d.ind)] : "lightgray"; 
      })
      .style("stroke", function(d) {
	  return "black";
      });

  nodeUpdate.select("text")
      .style("fill-opacity", 1);

  // Transition exiting nodes to the parent's new position. '
  var nodeExit = node.exit().transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
      .remove();

  nodeExit.select("circle")
      .attr("r", 1e-6);

  nodeExit.select("text")
      .style("fill-opacity", 1e-6);

  // Update the links…
  var link = svg.selectAll("path.link")
      .data(links, function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position. '
  link.enter().insert("path", "g")
      .attr("class", "link")
      .attr("d", function(d) {
        var o = {x: source.x0, y: source.y0};
        return diagonal({source: o, target: o});
      });

  // Transition links to their new position.
  link.transition()
      .duration(duration)
      .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position. '
  link.exit().transition()
      .duration(duration)
      .attr("d", function(d) {
        var o = {x: source.x, y: source.y};
        return diagonal({source: o, target: o});
      })
      .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
    d.x0 = d.x;
    d.y0 = d.y;
  });
}

// Toggle children on click.
function click(d) {

  var i = 0;
  var mynode;

  // find element in our json files (metrics, concepts, attributes of quality).
  if (typeof d.type == "undefined") {
    alert("No type defined on node.");
  } else {
    if (d.type == "metric") {
      mynode = d;
      mynode.description = mymetrics[d.mnemo]["desc"]; 
      mynode.name = mymetrics[d.mnemo]["name"]; 
//      mynode.ind = mymetrics[d.mnemo]["ind"];
//      mynode.value = mymetrics[d.mnemo]["value"];
      mynode.datasource = mymetrics[d.mnemo]["ds"]; 

      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
  
      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active.charAt(0).toUpperCase() + mynode.active.slice(1));

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Value:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(d.value + " ( " + d.ind + " )");

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Data source:")
      psource = ptitle.append('span');
      psource.classed("details", true);
      psource.text(mynode.datasource);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.html(mynode.description[desc_idx]);
      }
    } else if (d.type == "concept") {
      mynode = d;
      mynode.description = myconcepts[d.mnemo]["desc"]; 
      mynode.name = myconcepts[d.mnemo]["name"]; 
      mynode.question = myconcepts[d.mnemo]["question"]; 

      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
  
      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active);

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Value:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(d.ind);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Question:")
      var pdesc = mydiv.append('p');
      pdesc.classed("details", true);
      pdesc.text(mynode.question);
      
      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.html(mynode.description[desc_idx]);
      }
    } else if (d.type == "attribute") {
      mynode = d;
      mynode.description = myattrs[d.mnemo]["desc"]; 
      mynode.name = myattrs[d.mnemo]["name"]; 

      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
    
      var pactive = mydiv.append('p');
      ptitle = pactive.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = pactive.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active);

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Value:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(d.ind);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.text(mynode.description[desc_idx]);
      }
    
    }
  }
}

</script>
</div>
<div class="col-lg-5">
<div id="details-box-project"><p>Click on a node to get more details.</p></div>
</div> <!-- col -->
</div> <!-- row -->

                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="attrs"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="20%">Mnemo</th><th width="20%">Value (confidence)</th><th width="20%">Indicator</th></tr>
<tr><td><a href="/documentation/attributes.html#QM_ACTIVITY">Activity</a></td><td><a href="/documentation/attributes.html#QM_ACTIVITY">QM_ACTIVITY</a></td><td>1.0 ( 4 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ANA">Analysability</a></td><td><a href="/documentation/attributes.html#QM_ANA">QM_ANA</a></td><td>2.0 ( 2 / 5 metrics ) </td><td><span class="label label-scale" style="background-color: #CCF24D">2.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_CHA">Changeability</a></td><td><a href="/documentation/attributes.html#QM_CHA">QM_CHA</a></td><td>2.5 ( 2 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_DIVERSITY">Diversity</a></td><td><a href="/documentation/attributes.html#QM_DIVERSITY">QM_DIVERSITY</a></td><td>1.0 ( 1 / 3 metrics ) </td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ECOSYSTEM">Ecosystem</a></td><td><a href="/documentation/attributes.html#QM_ECOSYSTEM">QM_ECOSYSTEM</a></td><td>1.9 ( 11 / 13 metrics ) </td><td><span class="label label-scale" style="background-color: #FFFF66">1.9</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_FEEDBACK">User feedback</a></td><td><a href="/documentation/attributes.html#QM_FEEDBACK">QM_FEEDBACK</a></td><td>1.0 ( 0 / 0 metrics ) </td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ITS">Change Management</a></td><td><a href="/documentation/attributes.html#QM_ITS">QM_ITS</a></td><td>3.0 ( 3 / 3 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PLAN">Planning Management</a></td><td><a href="/documentation/attributes.html#QM_PLAN">QM_PLAN</a></td><td>3.5 ( 2 / 2 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PROCESS">Process</a></td><td><a href="/documentation/attributes.html#QM_PROCESS">QM_PROCESS</a></td><td>3.2 ( 8 / 12 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.2</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PRODUCT">Product</a></td><td><a href="/documentation/attributes.html#QM_PRODUCT">QM_PRODUCT</a></td><td>2.5 ( 11 / 20 metrics ) </td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_QUALITY">Project Quality</a></td><td><a href="/documentation/attributes.html#QM_QUALITY">QM_QUALITY</a></td><td>2.5 ( 30 / 45 metrics ) </td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_REL">Reliability</a></td><td><a href="/documentation/attributes.html#QM_REL">QM_REL</a></td><td>3.2 ( 5 / 7 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.2</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_RESPONSIVENESS">Responsiveness</a></td><td><a href="/documentation/attributes.html#QM_RESPONSIVENESS">QM_RESPONSIVENESS</a></td><td>5.0 ( 2 / 2 metrics ) </td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_REU">Reusability</a></td><td><a href="/documentation/attributes.html#QM_REU">QM_REU</a></td><td>2.5 ( 2 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_SCM">Configuration Management</a></td><td><a href="/documentation/attributes.html#QM_SCM">QM_SCM</a></td><td>3.0 ( 3 / 3 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_SUPPORT">Support</a></td><td><a href="/documentation/attributes.html#QM_SUPPORT">QM_SUPPORT</a></td><td>2.5 ( 4 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_USAGE">Usage</a></td><td><a href="/documentation/attributes.html#QM_USAGE">QM_USAGE</a></td><td>1.0 ( 0 / 0 metrics ) </td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
</table>


                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="questions"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="20%">Mnemo</th><th width="20%">Value</th><th width="20%">Indicator</th></tr>
<tr><td><a href="/documentation/questions.html#DOWNLOADS">Downloads</a></td><td><a href="/documentation/questions.html#DOWNLOADS">DOWNLOADS</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#INSTALL">Installations</a></td><td><a href="/documentation/questions.html#INSTALL">INSTALL</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#ITS_REL">ITS Reliability</a></td><td><a href="/documentation/questions.html#ITS_REL">ITS_REL</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#ITS_USAGE">ITS usage</a></td><td><a href="/documentation/questions.html#ITS_USAGE">ITS_USAGE</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MKT_FEEDBACK">Marketplace feedback</a></td><td><a href="/documentation/questions.html#MKT_FEEDBACK">MKT_FEEDBACK</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_ACTIVITY">Developer ML activity</a></td><td><a href="/documentation/questions.html#MLS_DEV_ACTIVITY">MLS_DEV_ACTIVITY</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_RESPONSIVENESS">Developer ML responsiveness</a></td><td><a href="/documentation/questions.html#MLS_DEV_RESPONSIVENESS">MLS_DEV_RESPONSIVENESS</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_SUPPORT">Developer ML support</a></td><td><a href="/documentation/questions.html#MLS_DEV_SUPPORT">MLS_DEV_SUPPORT</a></td><td>2.5</td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_ACTIVITY">User ML activity</a></td><td><a href="/documentation/questions.html#MLS_USR_ACTIVITY">MLS_USR_ACTIVITY</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_RESPONSIVENESS">User ML responsiveness</a></td><td><a href="/documentation/questions.html#MLS_USR_RESPONSIVENESS">MLS_USR_RESPONSIVENESS</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_SUPPORT">User ML support</a></td><td><a href="/documentation/questions.html#MLS_USR_SUPPORT">MLS_USR_SUPPORT</a></td><td>2.5</td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#PLAN_RELEASES">Milestones</a></td><td><a href="/documentation/questions.html#PLAN_RELEASES">PLAN_RELEASES</a></td><td>3.5</td><td><span class="label label-scale" style="background-color: #99E633">3.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#PRACTICES_ANA">Analysability practices</a></td><td><a href="/documentation/questions.html#PRACTICES_ANA">PRACTICES_ANA</a></td><td>2.0</td><td><span class="label label-scale" style="background-color: #CCF24D">2.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#PRACTICES_CHA">Changeability practices</a></td><td><a href="/documentation/questions.html#PRACTICES_CHA">PRACTICES_CHA</a></td><td>2.5</td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#PRACTICES_REL">Reliability practices</a></td><td><a href="/documentation/questions.html#PRACTICES_REL">PRACTICES_REL</a></td><td>2.5</td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#PRACTICES_REU">Reusability practices</a></td><td><a href="/documentation/questions.html#PRACTICES_REU">PRACTICES_REU</a></td><td>2.5</td><td><span class="label label-scale" style="background-color: #CCF24D">2.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#PUB_ITS_INFO">ITS information access</a></td><td><a href="/documentation/questions.html#PUB_ITS_INFO">PUB_ITS_INFO</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#PUB_SCM_INFO">SCM information access</a></td><td><a href="/documentation/questions.html#PUB_SCM_INFO">PUB_SCM_INFO</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#SCM_ACTIVITY">SCM activity</a></td><td><a href="/documentation/questions.html#SCM_ACTIVITY">SCM_ACTIVITY</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#SCM_DIVERSITY">SCM diversity</a></td><td><a href="/documentation/questions.html#SCM_DIVERSITY">SCM_DIVERSITY</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#SCM_USAGE">SCM usage</a></td><td><a href="/documentation/questions.html#SCM_USAGE">SCM_USAGE</a></td><td>1.0</td><td><span class="label label-scale" style="background-color: #FFFF66">1.0</span></td></tr>
</table>


                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="metrics"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="20%">Mnemo</th><th width="20%">Value</th><th width="20%">Indicator</th></tr>
<tr><td><a href="/documentation/metrics.html#DL_REPO_1M">Number of downloads on the web site</a></td><td><a href="/documentation/metrics.html#DL_REPO_1M">DL_REPO_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">Number of downloads on update site</a></td><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">DL_UPDATE_SITE_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS_AUTH_1M</a></td><td>0.013</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>0.03</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_OPEN">Number of open bugs</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_OPEN">ITS_BUGS_OPEN</a></td><td>1.15937429154</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">ITS_FIX_MED_1M</a></td><td>33.67</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS_UPDATES_1M</a></td><td>0.076</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_FAV">Number of favourites on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_FAV">MKT_FAV</a></td><td>0</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">Number of successfull installs on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">MKT_INSTALL_SUCCESS_1M</a></td><td>0</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">Developer ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">MLS_DEV_RESP_RATIO_1M</a></td><td>2.64</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_TIME_MED_1M">Developer ML response time</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_TIME_MED_1M">MLS_DEV_RESP_TIME_MED_1M</a></td><td>0.02</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">Developer ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">MLS_DEV_SUBJ_1M</a></td><td>0.0034</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">Developer ML posts</a></td><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">MLS_DEV_VOL_1M</a></td><td>0.0125</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_RESP_RATIO_1M">User ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_USR_RESP_RATIO_1M">MLS_USR_RESP_RATIO_1M</a></td><td>2.64</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">User ML response time</a></td><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">MLS_USR_RESP_TIME_MED_1M</a></td><td>0.02</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_SUBJ_1M">User ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_USR_SUBJ_1M">MLS_USR_SUBJ_1M</a></td><td>0.0034</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_VOL_1M">User ML posts</a></td><td><a href="/documentation/metrics.html#MLS_USR_VOL_1M">MLS_USR_VOL_1M</a></td><td>0.0125</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA">Number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA">NCC_ANA</a></td><td>29045</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA_IDX">Average number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA_IDX">NCC_ANA_IDX</a></td><td>9.11</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA">Number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA">NCC_CHA</a></td><td>4271</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA_IDX">Average number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA_IDX">NCC_CHA_IDX</a></td><td>1.34</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL">Number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL">NCC_REL</a></td><td>7350</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL_IDX">Average number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL_IDX">NCC_REL_IDX</a></td><td>2.3</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU">Number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU">NCC_REU</a></td><td>229594</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU_IDX">Average number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU_IDX">NCC_REU_IDX</a></td><td>71.99</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_MILESTONES_VOL">Number of milestones</a></td><td><a href="/documentation/metrics.html#PLAN_MILESTONES_VOL">PLAN_MILESTONES_VOL</a></td><td>21</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">Reviews success rate</a></td><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">PLAN_REVIEWS_SUCCESS_RATE</a></td><td>33</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">ITS information</a></td><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">PUB_ITS_INFO_PMI</a></td><td>5</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">SCM information</a></td><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">PUB_SCM_INFO_PMI</a></td><td>5</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_ANA">Number of violated rules for analysability</a></td><td><a href="/documentation/metrics.html#RKO_ANA">RKO_ANA</a></td><td>39</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_CHA">Number of violated rules for changeability</a></td><td><a href="/documentation/metrics.html#RKO_CHA">RKO_CHA</a></td><td>11</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REL">Number of violated rules for reliability</a></td><td><a href="/documentation/metrics.html#RKO_REL">RKO_REL</a></td><td>15</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REU">Number of violated rules for reusability</a></td><td><a href="/documentation/metrics.html#RKO_REU">RKO_REU</a></td><td>8</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_ANA">Adherence to analysability rules</a></td><td><a href="/documentation/metrics.html#ROKR_ANA">ROKR_ANA</a></td><td>38.0952380952381</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_CHA">Adherence to changeability rules</a></td><td><a href="/documentation/metrics.html#ROKR_CHA">ROKR_CHA</a></td><td>42.1052631578947</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REL">Adherence to reliability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REL">ROKR_REL</a></td><td>68.0851063829787</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REU">Adherence to reusability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REU">ROKR_REU</a></td><td>55.5555555555556</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_ANA">Number of rules for analysability</a></td><td><a href="/documentation/metrics.html#RULES_ANA">RULES_ANA</a></td><td>63</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_CHA">Number of rules for changeability</a></td><td><a href="/documentation/metrics.html#RULES_CHA">RULES_CHA</a></td><td>19</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REL">Number of rules for reliability</a></td><td><a href="/documentation/metrics.html#RULES_REL">RULES_REL</a></td><td>47</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REU">Number of rules for reusability</a></td><td><a href="/documentation/metrics.html#RULES_REU">RULES_REU</a></td><td>18</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM_COMMITS_1M</a></td><td>0.01066</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">SCM_COMMITTED_FILES_1M</a></td><td>0.199</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM_COMMITTERS_1M</a></td><td>0.0025</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
</table>

</div>
                  <div role="tabpanel" class="tab-pane fade" id="practices"><br /></div>
                  <div role="tabpanel" class="tab-pane fade" id="actions">...</div>
                  <div role="tabpanel" class="tab-pane fade" id="log"><br />
                    <ul class="list-group">
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [MLS_DEV_AUTH_1M] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [MLS_USR_AUTH_1M] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [LINE_COVERAGE] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [BRANCH_COVERAGE] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [TST_VOL_IDX] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [TEST_SUCCESS_DENSITY] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [NCLOC] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [FUNCTION_COMPLEXITY] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [COMMENT_LINES_DENSITY] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [FUNCTION_COMPLEXITY] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [DUPLICATED_LINES_DENSITY] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [FUNCTION_COMPLEXITY] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [SCM_STABILITY_1M] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [LINE_COVERAGE] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [COMMENT_LINES_DENSITY] is missing.</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find violations file [../../samples//papyrus/papyrus_violations.json] for [papyrus].</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
