
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>Project papyrus</h2>

              <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Summary</a></li>
                  <li role="presentation"><a href="#pmi" role="tab" data-toggle="tab">PMI</a></li>
                  <li role="presentation" class="disabled"><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation" class="disabled"><a href="#attrs" role="tab" data-toggle="tab">Attributes</a></li>
                  <li role="presentation"><a href="#questions" role="tab" data-toggle="tab">Questions</a></li>
                  <li role="presentation"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation" class="disabled"><a href="#actions" role="tab" data-toggle="tab">Actions</a></li>
                  <li role="presentation"><a href="#log" role="tab" data-toggle="tab">Errors</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane fade in active" id="home"><br />
                    <div class="row">
                      <div class="col-sm-8">
                        <div class="panel panel-primary"><div class="panel-heading">Rating for main quality attributes</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Ecosystem Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Process Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Product Quality</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Downloads</div><ul class="list-group"><li class="list-group-item">Project attributes: [ <a href="papyrus_attributes.json">JSON</a> ] [ <a href="papyrus_attributes.csv">CSV</a> ]</li><li class="list-group-item">Project questions: [ <a href="papyrus_questions.json">JSON</a> ] [ <a href="papyrus_questions.csv">CSV</a> ]</li><li class="list-group-item">Project metrics: [ <a href="papyrus_metrics.json">JSON</a> ] [ <a href="papyrus_metrics.csv">CSV</a> ]</li><li class="list-group-item">Project violations: [ <a href="papyrus_violations.json">JSON</a> ] [ <a href="papyrus_violations.csv">CSV</a> ]</li></ul></div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Ecosystem quality</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Activity</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Diversity</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Responsiveness</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Support</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                            <dt>Usage</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                            <dt>User feedback</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Process quality</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Configuration Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Change Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Planning Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Test Management</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Product quality</div>
                          <div class="panel-body">
                            <dl>
                            <dt>Analysability</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Changeability</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Reliability</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            <dt>Reusability</dt><dd><div class="progress"><div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #ebebeb;width: 0%;">0 / 5</div></div></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="pmi"><br />
                    <dl class="dl-horizontal">
                      <dt>Description</dt>
                      <dd><p>Papyrus is a component of the Model Development Tools (MDT) subproject aiming at providing an integrated, user-consumable environment for editing any kind of EMF model and particularly supporting UML and related modeling languages such as SysML and MARTE. Papyrus provides diagram editors for EMF-based modeling languages amongst them UML 2 and SysML and the glue required for integrating these editors (GMF-based or not) with other MBD and MDSD tools. It also offers a very advanced support of UML profiles that enables users to define editors for DSLs based on the UML 2 standard and its extension mechanisms. The main feature of Papyrus regarding this latter point is a set of very powerful customization mechanisms which can be leveraged to create user-defined Papyrus perspectives and give it the same look and feel as a native DSL editor.<br />
 <br />
For more details on Papyrus, see the <a href="http://www.eclipse.org/papyrus">home page</a> or the <a href="http://wiki.eclipse.org/MDT/Papyrus">Wiki</a>.</p>
</dd>
                      <dt>Web</dt>
                      <dd><a href="http://www.eclipse.org/papyrus">http://www.eclipse.org/papyrus</a></dd>
                      <dt>Wiki</dt>
                      <dd><a href="http://wiki.eclipse.org/MDT/Papyrus">http://wiki.eclipse.org/MDT/Papyrus</a></dd>
                      <dt>Downloads</dt>
                      <dd><a href="http://www.eclipse.org/modeling/mdt/papyrus/downloads/">http://www.eclipse.org/modeling/mdt/papyrus/downloads/</a></dd>
                      <dt>Documentation</dt>
                      <dd><a href="http://www.eclipse.org/modeling/mdt/papyrus/usersCorner/usersCornerIndex.php">http://www.eclipse.org/modeling/mdt/papyrus/usersCorner/usersCornerIndex.php</a></dd>
                      <dt>Getting Started</dt>
                      <dd><a href="http://www.eclipse.org/papyrus/updates/index.php">http://www.eclipse.org/papyrus/updates/index.php</a></dd>
                    </dl>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="qm">              <h3>The Quality model</h3>
            
            <p>The quality model shows the complete hierarchy tree, from <a href="/documentation/attributes.html">quality attributes</a> to <a href="/documentation/questions.html">measurement concepts</a> (questions) and <a href="/documentation/metrics.html">metrics</a>. Following Basili's Goal-Question-Metric approach [<a href="/documentation/references.html#Basili1994">Basili1994</a>], the quality attributes (the 3 first columns) are goals for our measurement, concepts (4th col) are mapped to questions, and metrics (right col) are the base measures.</p>
            
<div id="tree"></div>

<script src="/js/d3/d3.min.js"></script>
<script>

var margin = {top: 20, right: 120, bottom: 20, left: 10},
    width = 1100 - margin.right - margin.left,
    height = 1024 - margin.top - margin.bottom;
    
var i = 0,
    duration = 750,
    root;

var tree = d3.layout.tree()
    .size([height, width]);

var diagonal = d3.svg.diagonal()
    .projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("div#tree").append("svg")
    .attr("width", width + margin.right + margin.left)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

//var mycolours = ["#fff", "#ff0000", "#cc3300", "#996600", "#669900", "#33CC00"];
var mycolours = ["#ebebeb", "#FFFF66", "#CCF24D", "#99E633", "#66D91A", "#33CC00"];

var myattrs = {};
var mymetrics = {};
var myconcepts = {};
var myvalues = new Object();

// Load file for attributes.
d3.json("../data/polarsys_attributes.json", function(error, attributes) {
  if (error) return console.warn(error);

  for(i=0;i<attributes.children.length;i++) {
    attr_mnemo = attributes.children[i]['mnemo'];
    myattrs[attr_mnemo] = attributes.children[i];
  }
});

// Load file for concepts.
d3.json("../data/polarsys_questions.json", function(error, concepts) {
  if (error) return console.warn(error);
  
  for(i=0;i<concepts.children.length;i++) {
    concept_name = concepts.children[i].mnemo;
    myconcepts[concept_name] = concepts.children[i];
  }
});

// Load file for metrics.
d3.json("../data/polarsys_metrics.json", function(error, metrics) {
  if (error) return console.warn(error);
  
  for(i=0;i<metrics.children.length;i++) {
    metric_name = metrics.children[i].mnemo;
    mymetrics[metric_name] = metrics.children[i];
  }
});

d3.json("papyrus_qm.json", function(error, qm) {
  if (error) return console.warn(error);

//  alert("Length of myvalues: " + myvalues.length);
//  alert("myvalues: " + Object.keys(myvalues));

  root = qm;
  root.x0 = height / 2;
  root.y0 = 0;

  function collapse(d) {
    if (d.children) {
      d._children = d.children;
      d._children.forEach(collapse);
      d.children = null;
    }
  }

  function firstCollapse(d) {
    if (d.children) {
      d._children = d.children;
      for(i=0;i<d._children.length;i++) {
        d._children[i].children.forEach(collapse);
      }
    }
  }

  //root.children.forEach(firstCollapse);
  update(root);
});

function update(source) {

  var tabs = [0, 100, 200, 400, 630, 700];

  // Compute the new tree layout.
  var nodes = tree.nodes(root).reverse(),
      links = tree.links(nodes);

  // Normalize for fixed-depth.
  nodes.forEach(function(d, i) { 
    d.y = tabs[d.depth];
  });

  // Update the nodes…
  var node = svg.selectAll("g.node")
      .data(nodes, function(d) { return d.id || (d.id = ++i); });

  // Enter any new nodes at the parent's previous position.
  var nodeEnter = node.enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
      .on("click", click);

  nodeEnter.append("circle")
      .attr("r", 1e-6)
      .style("fill", function(d) { 
        return d.value ? mycolours[parseInt(d.value)] : "gray"; 
      })
      .style("stroke", function(d) {
	  return "black";
	  //return d.value ? mycolours[parseInt(d.value)] : "gray"; 
      });

  nodeEnter.append("text")
      .attr("x", function(d) { return d.children || d._children ? -20 : 20; })
      .attr("dy", function(d) { return d.children || d._children ? "-0.5em" : ".35em" })
      .attr("text-anchor", function(d) { return d.children || d.children ? "end" : "start"; })
      .attr("fill", function(d) { return d.active == "true" ? "black" : "gray";})
      .text(function(d) { 
        return d.value ? d.name + " (" + d.value + ")" : d.name;
      })
      .style("fill-opacity", 1e-6);

  // Transition nodes to their new position.
  var nodeUpdate = node.transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; });

  nodeUpdate.select("circle")
      .attr("r", 7)
      .style("fill", function(d) { 
        return d.value ? mycolours[parseInt(d.value)] : "gray"; 
      })
      .style("stroke", function(d) {
	  return "black";
	  //return d.value ? mycolours[parseInt(d.value)] : "gray"; 
      });

  nodeUpdate.select("text")
      .style("fill-opacity", 1);

  // Transition exiting nodes to the parent's new position.
  var nodeExit = node.exit().transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
      .remove();

  nodeExit.select("circle")
      .attr("r", 1e-6);

  nodeExit.select("text")
      .style("fill-opacity", 1e-6);

  // Update the links…
  var link = svg.selectAll("path.link")
      .data(links, function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position.
  link.enter().insert("path", "g")
      .attr("class", "link")
      .attr("d", function(d) {
        var o = {x: source.x0, y: source.y0};
        return diagonal({source: o, target: o});
      });

  // Transition links to their new position.
  link.transition()
      .duration(duration)
      .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position.
  link.exit().transition()
      .duration(duration)
      .attr("d", function(d) {
        var o = {x: source.x, y: source.y};
        return diagonal({source: o, target: o});
      })
      .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
    d.x0 = d.x;
    d.y0 = d.y;
  });
}

// Toggle children on click.
function click(d) {

  var i = 0;
  var mynode;

  // find element in our json files (metrics, concepts, attributes of quality).
  if (typeof d.type == "undefined") {
    alert("No type defined on node.");
  } else {
    if (d.type == "metric") {
      mynode = d;
      mynode.description = mymetrics[d.mnemo]["desc"]; 
      mynode.name = mymetrics[d.mnemo]["name"]; 
      mynode.datasource = mymetrics[d.mnemo]["ds"]; 

      var mydiv = d3.select("div#details-box");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
  
      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active.charAt(0).toUpperCase() + mynode.active.slice(1));

      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Data source:")
      psource = ptitle.append('span');
      psource.classed("details", true);
      psource.text(mynode.datasource);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.html(mynode.description[desc_idx]);
      }
    } else if (d.type == "concept") {
      mynode = d;
      mynode.description = myconcepts[d.mnemo]["desc"]; 
      mynode.name = myconcepts[d.mnemo]["name"]; 
      mynode.question = myconcepts[d.mnemo]["question"]; 

      var mydiv = d3.select("div#details-box");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
  
      p = mydiv.append('p');
      ptitle = p.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = p.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Question:")
      var pdesc = mydiv.append('p');
      pdesc.classed("details", true);
      pdesc.text(mynode.question);
      
      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.html(mynode.description[desc_idx]);
      }
    } else if (d.type == "attribute") {
      mynode = d;
      mynode.description = myattrs[d.mnemo]["desc"]; 
      mynode.name = myattrs[d.mnemo]["name"]; 

      var mydiv = d3.select("div#details-box");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      ptitle.text(d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")"); 
    
      var pactive = mydiv.append('p');
      ptitle = pactive.append('span');
      ptitle.classed("details-title", true); 
      ptitle.text("Active:")
      pactive = pactive.append('span');
      pactive.classed("details", true);
      pactive.text(mynode.active);

      pdesct = mydiv.append('p');
      pdesct.classed("details-title", true); 
      pdesct.text("Description:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.text(mynode.description[desc_idx]);
      }
    
    }
  }

  if (d.shiftKey) {
    alert("Shift key pressed!");
  }
}

</script>

<div id="details-box"><p>Click on a node to get more details.</p></div>


                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="attrs"><br />
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="questions"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/questions.html#CODE_CLONE">Code cloning</a></td><td><a href="/documentation/questions.html#CODE_CLONE">CODE_CLONE</a></td><td>1</td></tr>
<tr><td><a href="/documentation/questions.html#CPX">Code complexity</a></td><td><a href="/documentation/questions.html#CPX">CPX</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#INSTALL">Installations</a></td><td><a href="/documentation/questions.html#INSTALL">INSTALL</a></td><td>2</td></tr>
<tr><td><a href="/documentation/questions.html#MKT_FEEDBACK">Marketplace feedback</a></td><td><a href="/documentation/questions.html#MKT_FEEDBACK">MKT_FEEDBACK</a></td><td>3</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_ACTIVITY">Developer ML activity</a></td><td><a href="/documentation/questions.html#MLS_DEV_ACTIVITY">MLS_DEV_ACTIVITY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_DIVERSITY">Developer ML diversity</a></td><td><a href="/documentation/questions.html#MLS_DEV_DIVERSITY">MLS_DEV_DIVERSITY</a></td><td>3</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_RESPONSIVENESS">Developer ML responsiveness</a></td><td><a href="/documentation/questions.html#MLS_DEV_RESPONSIVENESS">MLS_DEV_RESPONSIVENESS</a></td><td>3</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_SUPPORT">Developer ML support</a></td><td><a href="/documentation/questions.html#MLS_DEV_SUPPORT">MLS_DEV_SUPPORT</a></td><td>3</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_ACTIVITY">User ML activity</a></td><td><a href="/documentation/questions.html#MLS_USR_ACTIVITY">MLS_USR_ACTIVITY</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_DIVERSITY">User ML diversity</a></td><td><a href="/documentation/questions.html#MLS_USR_DIVERSITY">MLS_USR_DIVERSITY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_RESPONSIVENESS">User ML responsiveness</a></td><td><a href="/documentation/questions.html#MLS_USR_RESPONSIVENESS">MLS_USR_RESPONSIVENESS</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_SUPPORT">User ML support</a></td><td><a href="/documentation/questions.html#MLS_USR_SUPPORT">MLS_USR_SUPPORT</a></td><td>4</td></tr>
<tr><td><a href="/documentation/questions.html#PUB_ITS_INFO">ITS information access</a></td><td><a href="/documentation/questions.html#PUB_ITS_INFO">PUB_ITS_INFO</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#PUB_SCM_INFO">SCM information access</a></td><td><a href="/documentation/questions.html#PUB_SCM_INFO">PUB_SCM_INFO</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#SCM_ACTIVITY">SCM activity</a></td><td><a href="/documentation/questions.html#SCM_ACTIVITY">SCM_ACTIVITY</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#SCM_DIVERSITY">SCM diversity</a></td><td><a href="/documentation/questions.html#SCM_DIVERSITY">SCM_DIVERSITY</a></td><td>5</td></tr>
<tr><td><a href="/documentation/questions.html#TST_COV">Test coverage</a></td><td><a href="/documentation/questions.html#TST_COV">TST_COV</a></td><td>4</td></tr>
</table>


                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="metrics"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/metrics.html#DL_REPO_1M">Number of downloads on the web site</a></td><td><a href="/documentation/metrics.html#DL_REPO_1M">DL_REPO_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">Number of downloads on update site</a></td><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">DL_UPDATE_SITE_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS_AUTH_1M</a></td><td>41</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>0.03</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">ITS_FIX_MED_1M</a></td><td>33.67</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS_UPDATES_1M</a></td><td>243</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_FAV">Number of favourites on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_FAV">MKT_FAV</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">Number of failed install on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">MKT_INSTALL_FAILED_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">Number of successfull installs on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">MKT_INSTALL_SUCCESS_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">Developer ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">MLS_DEV_RESP_RATIO_1M</a></td><td>2.64</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">Developer ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">MLS_DEV_SUBJ_1M</a></td><td>11</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">Developer ML posts</a></td><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">MLS_DEV_VOL_1M</a></td><td>40</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">User ML response time</a></td><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">MLS_USR_RESP_TIME_MED_1M</a></td><td>0.02</td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">Milestone success rate</a></td><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">PLAN_REVIEWS_SUCCESS_RATE</a></td><td>33</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">ITS information</a></td><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">PUB_ITS_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">SCM information</a></td><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">PUB_SCM_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM_COMMITS_1M</a></td><td>34</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">SCM_COMMITTED_FILES_1M</a></td><td>635</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM_COMMITTERS_1M</a></td><td>8</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane fade" id="practices"><br /></div>
                  <div role="tabpanel" class="tab-pane fade" id="actions">...</div>
                  <div role="tabpanel" class="tab-pane fade" id="log"><br />
                    <ul class="list-group">
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find attributes file [../../samples//papyrus/papyrus_attributes.json] for [papyrus].</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find violations file [../../samples//papyrus/papyrus_violations.json] for [papyrus].</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
