
        <div id="page-wrapper">
          <div class="row">
            <div class="col-lg-12">
              <h2>Project sirius</h2>

              <div class="tabbable">
                <ul class="nav nav-pills" role="tablist">
                  <!-- li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Summary</a></li -->
                  <li role="presentation" class="active"><a href="#pmi" role="tab" data-toggle="tab">PMI</a></li>
                  <li role="presentation" class="disabled"><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation" class="disabled"><a href="#attrs" role="tab" data-toggle="tab">Attributes</a></li>
                  <li role="presentation" class="disabled"><a href="#questions" role="tab" data-toggle="tab">Questions</a></li>
                  <li role="presentation"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation" class="disabled"><a href="#actions" role="tab" data-toggle="tab">Actions</a></li>
                  <li role="presentation"><a href="#log" role="tab" data-toggle="tab">Errors</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <!-- div role="tabpanel" class="tab-pane active" id="home"><br />...
                  </div -->
                  <div role="tabpanel" class="tab-pane active" id="pmi"><br />
                    <dl class="dl-horizontal">
                      <dt>Description</dt>
                      <dd><p>Sirius enables the specification of a modeling workbench in terms of <strong>graphical</strong>, <strong>table</strong> or <strong>tree</strong> editors with validation rules and actions using declarative descriptions.</p>
<p>All shape characteristics and behaviors can be easily configured with a <strong>minimum technical knowledge</strong>. This description is <strong>dynamically interpreted </strong>to materialize the workbench within the Eclipse IDE.<strong> No code generation</strong> is involved, the specifier of the workbench can have instant feedback while adapting the description.</p>
<p>Once completed, the modeling workbench can be deployed as a <strong>standard Eclipse plugin</strong>.</p>
<p>Thanks to this short feedback loop a workbench or its specialization can be created in a matter of hours.</p>
<p><a href="https://lh4.googleusercontent.com/-18UIHb--FDQ/Uht2vfYQqwI/AAAAAAAAMBw/fmGZ83aQGsI/s0/sirius-pan.png"><img alt="Graphical and Table editors made with Sirius" src="https://lh3.googleusercontent.com/-oWnvyr7hoFE/Uht0vwRViZI/AAAAAAAAMAo/lj7a_evd_jw/w600-h806-no/sirius-pan-small.png" style="width: 600px; height: 806px;" /></a></p>
</dd>
                      <dt>Web</dt>
                      <dd><a href="http://www.eclipse.org/sirius">http://www.eclipse.org/sirius</a></dd>
                      <dt>Wiki</dt>
                      <dd><a href="http://wiki.eclipse.org/Sirius">http://wiki.eclipse.org/Sirius</a></dd>
                      <dt>Downloads</dt>
                      <dd><a href="http://www.eclipse.org/sirius/download.html">http://www.eclipse.org/sirius/download.html</a></dd>
                      <dt>Documentation</dt>
                      <dd><a href="http://www.eclipse.org/sirius/doc">http://www.eclipse.org/sirius/doc</a></dd>
                      <dt>Getting Started</dt>
                      <dd><a href="http://wiki.eclipse.org/Sirius/Getting_Started">http://wiki.eclipse.org/Sirius/Getting_Started</a></dd>
                    </dl>
                  </div>
                  <div role="tabpanel" class="tab-pane" id="qm">...</div>
                  <div role="tabpanel" class="tab-pane" id="attrs"><br />
                  </div>
                  <div role="tabpanel" class="tab-pane" id="questions"><br />
                  </div>
                  <div role="tabpanel" class="tab-pane" id="metrics"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="50%">Name</th><th width="30%">Mnemo</th><th width="20%">Value</th></tr>
<tr><td><a href="/documentation/metrics.html#DL_REPO_1M">Number of downloads on the web site</a></td><td><a href="/documentation/metrics.html#DL_REPO_1M">DL_REPO_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">Number of downloads on update site</a></td><td><a href="/documentation/metrics.html#DL_UPDATE_SITE_1M">DL_UPDATE_SITE_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_1M">ITS_AUTH_1M</a></td><td>19</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>0.1</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_1M">ITS_FIX_MED_1M</a></td><td>18.16</td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_1M">ITS_UPDATES_1M</a></td><td>192</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_FAV">Number of favourites on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_FAV">MKT_FAV</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">Number of failed install on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_FAILED_1M">MKT_INSTALL_FAILED_1M</a></td><td>87</td></tr>
<tr><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">Number of successfull installs on the Marketplace</a></td><td><a href="/documentation/metrics.html#MKT_INSTALL_SUCCESS_1M">MKT_INSTALL_SUCCESS_1M</a></td><td>357</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">Developer ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_1M">MLS_DEV_RESP_RATIO_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">Developer ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_1M">MLS_DEV_SUBJ_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">Developer ML posts</a></td><td><a href="/documentation/metrics.html#MLS_DEV_VOL_1M">MLS_DEV_VOL_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">User ML response time</a></td><td><a href="/documentation/metrics.html#MLS_USR_RESP_TIME_MED_1M">MLS_USR_RESP_TIME_MED_1M</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA">Number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA">NCC_ANA</a></td><td>8965</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA">Number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA">NCC_CHA</a></td><td>1980</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL">Number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL">NCC_REL</a></td><td>4093</td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU">Number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU">NCC_REU</a></td><td>96110</td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">Milestone success rate</a></td><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">PLAN_REVIEWS_SUCCESS_RATE</a></td><td>0</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">ITS information</a></td><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">PUB_ITS_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">SCM information</a></td><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">PUB_SCM_INFO_PMI</a></td><td>5</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_ANA">Number of violated rules for analysability</a></td><td><a href="/documentation/metrics.html#RKO_ANA">RKO_ANA</a></td><td>33</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_CHA">Number of violated rules for changeability</a></td><td><a href="/documentation/metrics.html#RKO_CHA">RKO_CHA</a></td><td>10</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REL">Number of violated rules for reliability</a></td><td><a href="/documentation/metrics.html#RKO_REL">RKO_REL</a></td><td>13</td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REU">Number of violated rules for reusability</a></td><td><a href="/documentation/metrics.html#RKO_REU">RKO_REU</a></td><td>8</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_ANA">Adherence to analysability rules</a></td><td><a href="/documentation/metrics.html#ROKR_ANA">ROKR_ANA</a></td><td>47.6190476190476</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_CHA">Adherence to changeability rules</a></td><td><a href="/documentation/metrics.html#ROKR_CHA">ROKR_CHA</a></td><td>47.3684210526316</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REL">Adherence to reliability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REL">ROKR_REL</a></td><td>72.3404255319149</td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REU">Adherence to reusability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REU">ROKR_REU</a></td><td>55.5555555555556</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_ANA">Number of rules for analysability</a></td><td><a href="/documentation/metrics.html#RULES_ANA">RULES_ANA</a></td><td>63</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_CHA">Number of rules for changeability</a></td><td><a href="/documentation/metrics.html#RULES_CHA">RULES_CHA</a></td><td>19</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REL">Number of rules for reliability</a></td><td><a href="/documentation/metrics.html#RULES_REL">RULES_REL</a></td><td>47</td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REU">Number of rules for reusability</a></td><td><a href="/documentation/metrics.html#RULES_REU">RULES_REU</a></td><td>18</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_1M">SCM_COMMITS_1M</a></td><td>126</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_1M">SCM_COMMITTED_FILES_1M</a></td><td>2268</td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_1M">SCM_COMMITTERS_1M</a></td><td>9</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane" id="practices"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="40%">Mnemo</th><th width="20%">NCC</th></tr>
<tr><td><a href="/documentation/rules.html#UnusedFormalParameter">Unused Formal Parameter</a></td><td><a href="/documentation/rules.html#UnusedFormalParameter">UnusedFormalParameter</a></td><td>174</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidProtectedFieldInFinalClass">Avoid Protected Field In Final Class</a></td><td><a href="/documentation/rules.html#AvoidProtectedFieldInFinalClass">AvoidProtectedFieldInFinalClass</a></td><td>7</td></tr>
<tr><td><a href="/documentation/rules.html#RV_NEGATING_RESULT_OF_COMPARETO">RV: Negating the result of compareTo()/compare()</a></td><td><a href="/documentation/rules.html#RV_NEGATING_RESULT_OF_COMPARETO">RV_NEGATING_RESULT_OF_COMPARETO</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyCatchBlock">Empty Catch Block</a></td><td><a href="/documentation/rules.html#EmptyCatchBlock">EmptyCatchBlock</a></td><td>390</td></tr>
<tr><td><a href="/documentation/rules.html#IS2_INCONSISTENT_SYNC">IS: Inconsistent synchronization </a></td><td><a href="/documentation/rules.html#IS2_INCONSISTENT_SYNC">IS2_INCONSISTENT_SYNC</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#SimplifyConditional">Simplify Conditional</a></td><td><a href="/documentation/rules.html#SimplifyConditional">SimplifyConditional</a></td><td>12</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidProtectedMethodInFinalClassNotExtending">Avoid Protected Method In Final Class Not Extending</a></td><td><a href="/documentation/rules.html#AvoidProtectedMethodInFinalClassNotExtending">AvoidProtectedMethodInFinalClassNotExtending</a></td><td>27</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidReassigningParameters">Avoid Reassigning Parameters</a></td><td><a href="/documentation/rules.html#AvoidReassigningParameters">AvoidReassigningParameters</a></td><td>400</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidInstanceofChecksInCatchClause">Avoid Instanceof() Checks In Catch Clause</a></td><td><a href="/documentation/rules.html#AvoidInstanceofChecksInCatchClause">AvoidInstanceofChecksInCatchClause</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#SwitchDensity">Switch Density</a></td><td><a href="/documentation/rules.html#SwitchDensity">SwitchDensity</a></td><td>14</td></tr>
<tr><td><a href="/documentation/rules.html#GodClass">God Class</a></td><td><a href="/documentation/rules.html#GodClass">GodClass</a></td><td>478</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedModifier">Unused Modifier</a></td><td><a href="/documentation/rules.html#UnusedModifier">UnusedModifier</a></td><td>23</td></tr>
<tr><td><a href="/documentation/rules.html#CouplingBetweenObjects">Coupling Between Objects</a></td><td><a href="/documentation/rules.html#CouplingBetweenObjects">CouplingBetweenObjects</a></td><td>48</td></tr>
<tr><td><a href="/documentation/rules.html#UnnecessaryLocalBeforeReturn">Unnecessary Local Before Return</a></td><td><a href="/documentation/rules.html#UnnecessaryLocalBeforeReturn">UnnecessaryLocalBeforeReturn</a></td><td>522</td></tr>
<tr><td><a href="/documentation/rules.html#ConfusingTernary">Confusing Ternary</a></td><td><a href="/documentation/rules.html#ConfusingTernary">ConfusingTernary</a></td><td>1079</td></tr>
<tr><td><a href="/documentation/rules.html#PositionLiteralsFirstInComparisons">Position Literals First In Comparisons</a></td><td><a href="/documentation/rules.html#PositionLiteralsFirstInComparisons">PositionLiteralsFirstInComparisons</a></td><td>15</td></tr>
<tr><td><a href="/documentation/rules.html#CompareObjectsWithEquals">Compare Objects With Equals</a></td><td><a href="/documentation/rules.html#CompareObjectsWithEquals">CompareObjectsWithEquals</a></td><td>772</td></tr>
<tr><td><a href="/documentation/rules.html#MS_MUTABLE_ARRAY">MS: Field is a mutable array </a></td><td><a href="/documentation/rules.html#MS_MUTABLE_ARRAY">MS_MUTABLE_ARRAY</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#NonThreadSafeSingleton">Non Thread Safe Singleton</a></td><td><a href="/documentation/rules.html#NonThreadSafeSingleton">NonThreadSafeSingleton</a></td><td>19</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidSynchronizedAtMethodLevel">Avoid Synchronized At Method Level</a></td><td><a href="/documentation/rules.html#AvoidSynchronizedAtMethodLevel">AvoidSynchronizedAtMethodLevel</a></td><td>79</td></tr>
<tr><td><a href="/documentation/rules.html#ConstructorCallsOverridableMethod">Constructor Calls Overridable Method</a></td><td><a href="/documentation/rules.html#ConstructorCallsOverridableMethod">ConstructorCallsOverridableMethod</a></td><td>20</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedPrivateMethod">Unused Private Method</a></td><td><a href="/documentation/rules.html#UnusedPrivateMethod">UnusedPrivateMethod</a></td><td>514</td></tr>
<tr><td><a href="/documentation/rules.html#LogicInversion">Logic Inversion</a></td><td><a href="/documentation/rules.html#LogicInversion">LogicInversion</a></td><td>120</td></tr>
<tr><td><a href="/documentation/rules.html#UseLocaleWithCaseConversions">Use Locale With Case Conversions</a></td><td><a href="/documentation/rules.html#UseLocaleWithCaseConversions">UseLocaleWithCaseConversions</a></td><td>43</td></tr>
<tr><td><a href="/documentation/rules.html#RV_RETURN_VALUE_IGNORED_BAD_PRACTICE">RV: Method ignores exceptional return value </a></td><td><a href="/documentation/rules.html#RV_RETURN_VALUE_IGNORED_BAD_PRACTICE">RV_RETURN_VALUE_IGNORED_BAD_PRACTICE</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#ImmutableField">Immutable Field</a></td><td><a href="/documentation/rules.html#ImmutableField">ImmutableField</a></td><td>1339</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyWhileStmt">Empty While Stmt</a></td><td><a href="/documentation/rules.html#EmptyWhileStmt">EmptyWhileStmt</a></td><td>12</td></tr>
<tr><td><a href="/documentation/rules.html#EI_EXPOSE_REP2">EI2: May expose internal representation by incorporating reference to mutable object </a></td><td><a href="/documentation/rules.html#EI_EXPOSE_REP2">EI_EXPOSE_REP2</a></td><td>8</td></tr>
<tr><td><a href="/documentation/rules.html#PreserveStackTrace">Preserve Stack Trace</a></td><td><a href="/documentation/rules.html#PreserveStackTrace">PreserveStackTrace</a></td><td>19</td></tr>
<tr><td><a href="/documentation/rules.html#UseUtilityClass">UseUtilityClass</a></td><td><a href="/documentation/rules.html#UseUtilityClass">UseUtilityClass</a></td><td>15</td></tr>
<tr><td><a href="/documentation/rules.html#AbstractClassWithoutAnyMethod">Abstract Class Without Any Method</a></td><td><a href="/documentation/rules.html#AbstractClassWithoutAnyMethod">AbstractClassWithoutAnyMethod</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#SimplifyBooleanExpressions">Simplify Boolean Expressions</a></td><td><a href="/documentation/rules.html#SimplifyBooleanExpressions">SimplifyBooleanExpressions</a></td><td>13</td></tr>
<tr><td><a href="/documentation/rules.html#SwitchStmtsShouldHaveDefault">Switch Statements Should Have Default</a></td><td><a href="/documentation/rules.html#SwitchStmtsShouldHaveDefault">SwitchStmtsShouldHaveDefault</a></td><td>2268</td></tr>
<tr><td><a href="/documentation/rules.html#NonStaticInitializer">Non Static Initializer</a></td><td><a href="/documentation/rules.html#NonStaticInitializer">NonStaticInitializer</a></td><td>8</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidThreadGroup">Avoid ThreadGroup</a></td><td><a href="/documentation/rules.html#AvoidThreadGroup">AvoidThreadGroup</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#BooleanInstantiation">Boolean Instantiation</a></td><td><a href="/documentation/rules.html#BooleanInstantiation">BooleanInstantiation</a></td><td>3</td></tr>
<tr><td><a href="/documentation/rules.html#AccessorClassGeneration">Accessor Class Generation</a></td><td><a href="/documentation/rules.html#AccessorClassGeneration">AccessorClassGeneration</a></td><td>148</td></tr>
<tr><td><a href="/documentation/rules.html#MissingBreakInSwitch">Missing Break In Switch</a></td><td><a href="/documentation/rules.html#MissingBreakInSwitch">MissingBreakInSwitch</a></td><td>34</td></tr>
<tr><td><a href="/documentation/rules.html#OverrideBothEqualsAndHashcode">Override Both Equals And Hash code</a></td><td><a href="/documentation/rules.html#OverrideBothEqualsAndHashcode">OverrideBothEqualsAndHashcode</a></td><td>8</td></tr>
<tr><td><a href="/documentation/rules.html#ReturnEmptyArrayRatherThanNull">Return Empty Array Rather Than Null</a></td><td><a href="/documentation/rules.html#ReturnEmptyArrayRatherThanNull">ReturnEmptyArrayRatherThanNull</a></td><td>15</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyMethodInAbstractClassShouldBeAbstract">Empty Method In Abstract Class Should Be Abstract</a></td><td><a href="/documentation/rules.html#EmptyMethodInAbstractClassShouldBeAbstract">EmptyMethodInAbstractClassShouldBeAbstract</a></td><td>65</td></tr>
<tr><td><a href="/documentation/rules.html#ExcessiveImports">Excessive Imports</a></td><td><a href="/documentation/rules.html#ExcessiveImports">ExcessiveImports</a></td><td>438</td></tr>
<tr><td><a href="/documentation/rules.html#AssignmentToNonFinalStatic">Assignment To Non Final Static</a></td><td><a href="/documentation/rules.html#AssignmentToNonFinalStatic">AssignmentToNonFinalStatic</a></td><td>69</td></tr>
<tr><td><a href="/documentation/rules.html#FinalFieldCouldBeStatic">Final Field Could Be Static</a></td><td><a href="/documentation/rules.html#FinalFieldCouldBeStatic">FinalFieldCouldBeStatic</a></td><td>16</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedPrivateField">Unused Private Field</a></td><td><a href="/documentation/rules.html#UnusedPrivateField">UnusedPrivateField</a></td><td>30</td></tr>
<tr><td><a href="/documentation/rules.html#EI_EXPOSE_REP">EI: May expose internal representation by returning reference to mutable object </a></td><td><a href="/documentation/rules.html#EI_EXPOSE_REP">EI_EXPOSE_REP</a></td><td>4</td></tr>
<tr><td><a href="/documentation/rules.html#AbstractClassWithoutAbstractMethod">Abstract Class Without Abstract Method</a></td><td><a href="/documentation/rules.html#AbstractClassWithoutAbstractMethod">AbstractClassWithoutAbstractMethod</a></td><td>6</td></tr>
<tr><td><a href="/documentation/rules.html#SimpleDateFormatNeedsLocale">Simple Date Format Needs Locale</a></td><td><a href="/documentation/rules.html#SimpleDateFormatNeedsLocale">SimpleDateFormatNeedsLocale</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidConstantsInterface">Avoid Constants Interface</a></td><td><a href="/documentation/rules.html#AvoidConstantsInterface">AvoidConstantsInterface</a></td><td>72</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyStatementNotInLoop">Empty Statement Not In Loop</a></td><td><a href="/documentation/rules.html#EmptyStatementNotInLoop">EmptyStatementNotInLoop</a></td><td>3</td></tr>
<tr><td><a href="/documentation/rules.html#CollapsibleIfStatements">Collapsible If Statements</a></td><td><a href="/documentation/rules.html#CollapsibleIfStatements">CollapsibleIfStatements</a></td><td>487</td></tr>
<tr><td><a href="/documentation/rules.html#OptimizableToArrayCall">Optimizable toArray Call</a></td><td><a href="/documentation/rules.html#OptimizableToArrayCall">OptimizableToArrayCall</a></td><td>18</td></tr>
<tr><td><a href="/documentation/rules.html#SimplifyBooleanReturns">Simplify Boolean Returns</a></td><td><a href="/documentation/rules.html#SimplifyBooleanReturns">SimplifyBooleanReturns</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#LawOfDemeter">LawOfDemeter</a></td><td><a href="/documentation/rules.html#LawOfDemeter">LawOfDemeter</a></td><td>95444</td></tr>
<tr><td><a href="/documentation/rules.html#UncommentedEmptyMethod">Uncommented Empty Method</a></td><td><a href="/documentation/rules.html#UncommentedEmptyMethod">UncommentedEmptyMethod</a></td><td>168</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidDeeplyNestedIfStmts">Avoid Deeply Nested If Statements</a></td><td><a href="/documentation/rules.html#AvoidDeeplyNestedIfStmts">AvoidDeeplyNestedIfStmts</a></td><td>718</td></tr>
<tr><td><a href="/documentation/rules.html#FieldDeclarationsShouldBeAtStartOfClass">Field Declarations Should Be At Start Of Class</a></td><td><a href="/documentation/rules.html#FieldDeclarationsShouldBeAtStartOfClass">FieldDeclarationsShouldBeAtStartOfClass</a></td><td>1298</td></tr>
<tr><td><a href="/documentation/rules.html#SE_BAD_FIELD">Se: Non-transient non-serializable instance field in serializable class </a></td><td><a href="/documentation/rules.html#SE_BAD_FIELD">SE_BAD_FIELD</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#TooFewBranchesForASwitchStatement">Too Few Branches For A Switch Statement</a></td><td><a href="/documentation/rules.html#TooFewBranchesForASwitchStatement">TooFewBranchesForASwitchStatement</a></td><td>1711</td></tr>
<tr><td><a href="/documentation/rules.html#SE_COMPARATOR_SHOULD_BE_SERIALIZABLE">Se: Comparator doesn't implement Serializable </a></td><td><a href="/documentation/rules.html#SE_COMPARATOR_SHOULD_BE_SERIALIZABLE">SE_COMPARATOR_SHOULD_BE_SERIALIZABLE</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#DMI_INVOKING_TOSTRING_ON_ARRAY">USELESS_STRING: Invocation of toString on an array </a></td><td><a href="/documentation/rules.html#DMI_INVOKING_TOSTRING_ON_ARRAY">DMI_INVOKING_TOSTRING_ON_ARRAY</a></td><td>3</td></tr>
<tr><td><a href="/documentation/rules.html#DM_DEFAULT_ENCODING">Dm: Reliance on default encoding </a></td><td><a href="/documentation/rules.html#DM_DEFAULT_ENCODING">DM_DEFAULT_ENCODING</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyIfStmt">Empty If Stmt</a></td><td><a href="/documentation/rules.html#EmptyIfStmt">EmptyIfStmt</a></td><td>61</td></tr>
<tr><td><a href="/documentation/rules.html#MS_PKGPROTECT">MS: Field should be package protected </a></td><td><a href="/documentation/rules.html#MS_PKGPROTECT">MS_PKGPROTECT</a></td><td>47</td></tr>
<tr><td><a href="/documentation/rules.html#LooseCoupling">Loose Coupling</a></td><td><a href="/documentation/rules.html#LooseCoupling">LooseCoupling</a></td><td>87</td></tr>
<tr><td><a href="/documentation/rules.html#ClassWithOnlyPrivateConstructorsShouldBeFinal">Class With Only Private Constructors Should Be Final</a></td><td><a href="/documentation/rules.html#ClassWithOnlyPrivateConstructorsShouldBeFinal">ClassWithOnlyPrivateConstructorsShouldBeFinal</a></td><td>30</td></tr>
<tr><td><a href="/documentation/rules.html#CloseResource">Close Resource</a></td><td><a href="/documentation/rules.html#CloseResource">CloseResource</a></td><td>22</td></tr>
<tr><td><a href="/documentation/rules.html#UnusedLocalVariable">Unused Local Variable</a></td><td><a href="/documentation/rules.html#UnusedLocalVariable">UnusedLocalVariable</a></td><td>101</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidBranchingStatementAsLastInLoop">Avoid Branching Statement As Last In Loop</a></td><td><a href="/documentation/rules.html#AvoidBranchingStatementAsLastInLoop">AvoidBranchingStatementAsLastInLoop</a></td><td>5</td></tr>
<tr><td><a href="/documentation/rules.html#BC_UNCONFIRMED_CAST">BC: Unchecked/unconfirmed cast </a></td><td><a href="/documentation/rules.html#BC_UNCONFIRMED_CAST">BC_UNCONFIRMED_CAST</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#UseCollectionIsEmpty">Use Collection isEmpty</a></td><td><a href="/documentation/rules.html#UseCollectionIsEmpty">UseCollectionIsEmpty</a></td><td>347</td></tr>
<tr><td><a href="/documentation/rules.html#MS_SHOULD_BE_FINAL">MS: Field isn't final but should be </a></td><td><a href="/documentation/rules.html#MS_SHOULD_BE_FINAL">MS_SHOULD_BE_FINAL</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#SingularField">Singular Field</a></td><td><a href="/documentation/rules.html#SingularField">SingularField</a></td><td>242</td></tr>
<tr><td><a href="/documentation/rules.html#UncommentedEmptyConstructor">Uncommented Empty Constructor</a></td><td><a href="/documentation/rules.html#UncommentedEmptyConstructor">UncommentedEmptyConstructor</a></td><td>47</td></tr>
<tr><td><a href="/documentation/rules.html#EmptyFinallyBlock">Empty Finally Block</a></td><td><a href="/documentation/rules.html#EmptyFinallyBlock">EmptyFinallyBlock</a></td><td>3</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane" id="actions">...</div>
                  <div role="tabpanel" class="tab-pane" id="log"><br />
                    <ul class="list-group">
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find attributes file [../../samples//sirius/sirius_attributes.json] for [sirius].</li>
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Cannot find questions file [../../samples//sirius/sirius_attributes.json] for [sirius].</li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
