
              <h2>Project technology.ease</h2>

              <div class="tabbable">
                <ul class="nav nav-tabs" role="tablist">
                  <li role="presentation" class="active"><a href="#home" role="tab" data-toggle="tab">Summary</a></li>
                  <li role="presentation"><a href="#qm" role="tab" data-toggle="tab">QM</a></li>
                  <li role="presentation"><a href="#attrs" role="tab" data-toggle="tab">Attributes</a></li>
                  <li role="presentation"><a href="#questions" role="tab" data-toggle="tab">Questions</a></li>
                  <li role="presentation"><a href="#metrics" role="tab" data-toggle="tab">Metrics</a></li>
                  <li role="presentation"><a href="#practices" role="tab" data-toggle="tab">Practices</a></li>
                  <li role="presentation" class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                    Download <span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                      <li role="presentation"><a href="technology.ease_attributes.json">Attributes JSON</a></li>
                      <li role="presentation"><a href="technology.ease_attributes.csv">Attributes CSV</a></li>
                      <li role="presentation"><a href="technology.ease_questions.json">Questions JSON</a></li>
                      <li role="presentation"><a href="technology.ease_questions.csv">Questions CSV</a></li>
                      <li role="presentation"><a href="technology.ease_metrics.json">Metrics JSON</a></li>
                      <li role="presentation"><a href="technology.ease_metrics.csv">Metrics CSV</a></li>
                      <li role="presentation"><a href="technology.ease_pmd.zip">PMD results XML</a></li>
                      <li role="presentation"><a href="technology.ease_findbugs.zip">FindBugs results XML</a></li>
                    </ul>
                  </li>
                  <li role="presentation"><a href="#log" role="tab" data-toggle="tab">Errors</a></li>
                </ul>

                <!-- Tab panes -->
                <div class="tab-content">
                  <div role="tabpanel" class="tab-pane fade in active" id="home"><br />
                    <div class="row">
                      <div class="col-sm-6">
                        <dl class="dl-vertical">
                        <dt>Description</dt>
                        <dd></dd>
                        </dl>
                      </div>
                      <div class="col-sm-6">
                        <p class="text-right" style="font-weight: bold">Global rating: <span style="color: #DA7A08; font-size: 300%">3.8</span> / 5 &mdash; Completeness: 44 / 45</p><br />
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Rating for main quality attributes</div>
                          <div class="panel-body">
                            <dl>
                  <dt><a href="/documentation/attributes.html#QM_QUALITY">Overall Maturity</a> <span class="pull-right">( 44 / 45 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.8" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 76%;">3.8 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_ECOSYSTEM">Ecosystem Quality</a> <span class="pull-right">( 12 / 13 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.9" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 78%;">3.9 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_PROCESS">Process Quality</a> <span class="pull-right">( 12 / 12 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.4" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 68%;">3.4 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_PRODUCT">Product Quality</a> <span class="pull-right">( 20 / 20 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="4.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 80%;">4.0 / 5</div>
                    </div>
                  </dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">PMI Summary</div>
                        <ul class="list-group">
                          <li class="list-group-item"><span class="fa fa-dashboard"></span> &nbsp; Eclipse Dashboard <a href="http://dashboard.eclipse.org/project.html?project=technology.ease">Link to dashboard</a></dd>
                          <li class="list-group-item"><span class="fa fa-globe"></span> &nbsp; Web <a href="http://www.eclipse.org/ease">http://www.eclipse.org/ease</a></li>
                          <li class="list-group-item"><span class="fa fa-globe"></span> &nbsp; Wiki <a href="https://wiki.eclipse.org/EASE">https://wiki.eclipse.org/EASE</a></li>
                          <li class="list-group-item"><span class="fa fa-download"></span> &nbsp; Downloads <a href=""></a></li>
                          <li class="list-group-item"><span class="fa fa-question-circle"></span> &nbsp; Documentation <a href=""></a></dd>
                          <!-- li class="list-group-item"><span class="fa fa-question-circle"></span> &nbsp; Getting Started <a href=""></a></dd -->
                          <li class="list-group-item"><span class="fa fa-envelope"></span> &nbsp; Mailing lists [ <a href="https://dev.eclipse.org/mailman/listinfo/ease-dev">Developer ML</a> ] &nbsp; [ <a href="None">Usr not defined</a> ]</dd>
                        </ul>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Comments</div>
                        <ul class="list-group">
                          <li class="list-group-item">
                            <div class="pull-right">
	                      <a href="/comments/e/technology.ease/1432622852"><i class="fa fa-pencil"></i></a> &nbsp;
                              <a href="/comments/d/technology.ease/1432622852"><i class="fa fa-trash-o"></i></a>
	    </div>
                            <strong>BBaldassari</strong> on <strong></strong> (Thu May 21 12:33:05 2015)<br />trset alkj mklaa </li>
                          <li class="list-group-item">
                            <a href="/comments/w/technology.ease">
                            <div class="pull-right"><span class="fa fa-plus"></span></div>
                            Add a comment? (Authentication required)</a>
                          </li>
                        </ul>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Ecosystem quality</div>
                          <div class="panel-body">
                            <dl>
                  <dt><a href="/documentation/attributes.html#QM_ACTIVITY">Activity </a> <span class="pull-right">( 4 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="4.2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 84%;">4.2 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_DIVERSITY">Diversity </a> <span class="pull-right">( 3 / 3 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.7" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 74%;">3.7 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_RESPONSIVENESS">Responsiveness</a> <span class="pull-right">( 1 / 2 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="4.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 80%;">4.0 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_SUPPORT">Support</a> <span class="pull-right">( 4 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 70%;">3.5 / 5</div>
                    </div>
                  </dd></dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Process quality</div>
                          <div class="panel-body">
                            <dl>
                  <dt><a href="/documentation/attributes.html#QM_SCM">Configuration Management</a> <span class="pull-right">( 3 / 3 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="4.8" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 96%;">4.8 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_ITS">Change Management</a> <span class="pull-right">( 3 / 3 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="4.2" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 84%;">4.2 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_PLAN">Planning Management</a> <span class="pull-right">( 2 / 2 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="1.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #FFFF66;width: 30%;">1.5 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_TST">Test Management</a> <span class="pull-right">( 4 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 60%;">3.0 / 5</div>
                    </div>
                  </dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-4">
                        <div class="panel panel-primary"><div class="panel-heading">Product quality</div>
                          <div class="panel-body">
                            <dl>
                  <dt><a href="/documentation/attributes.html#QM_ANALYSABILITY">Analysability</a> <span class="pull-right">( 5 / 5 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.9" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 78%;">3.9 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_CHANGEABILITY">Changeability</a> <span class="pull-right">( 4 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="4.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 90%;">4.5 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_RELIABILITY">Reliability</a> <span class="pull-right">( 7 / 7 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="4.0" aria-valuemin="0" aria-valuemax="5"  style="background-color: #66D91A;width: 80%;">4.0 / 5</div>
                    </div>
                  </dd>
                  <dt><a href="/documentation/attributes.html#QM_REUSABILITY">Reusability</a> <span class="pull-right">( 4 / 4 metrics )</span></dt>
                  <dd>
                    <div class="progress">
                      <div class="progress-bar" role="progressbar" aria-valuenow="3.5" aria-valuemin="0" aria-valuemax="5"  style="background-color: #99E633;width: 70%;">3.5 / 5</div>
                    </div>
                  </dd>
                            </dl>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="qm">
              <h3>The Quality model</h3>
            
            <p>The quality model shows the complete hierarchy tree, from <a href="/documentation/attributes.html">quality attributes</a> to <a href="/documentation/questions.html">measurement concepts</a> (questions) and <a href="/documentation/metrics.html">metrics</a>. Following Basili's Goal-Question-Metric approach [<a href="/documentation/references.html#Basili1994">Basili1994</a>], the quality attributes (the 3 first columns) are goals for our measurement, concepts (4th col) are mapped to questions, and metrics (right col) are the base measures.</p>
              <div class="row">
            <div class="col-lg-7">
        
<div id="tree"></div>

<script src="/js/d3/d3.min.js"></script>
<script>

var margin = {top: 20, right: 120, bottom: 20, left: 10},
    width = 1100 - margin.right - margin.left,
    height = 1024 - margin.top - margin.bottom;
    
var i = 0,
    duration = 750,
    root;

var tree = d3.layout.tree()
    .size([height, width]);

var diagonal = d3.svg.diagonal()
    .projection(function(d) { return [d.y, d.x]; });

var svg = d3.select("div#tree").append("svg")
    .attr("width", width + margin.right + margin.left)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

//var mycolours = ["#fff", "#ff0000", "#cc3300", "#996600", "#669900", "#33CC00"];
var mycolours = ["#ebebeb", "#FFFF66", "#CCF24D", "#99E633", "#66D91A", "#33CC00"];

var myattrs = {};
var mymetrics = {};
var myconcepts = {};
var myvalues = new Object();

// Load file for attributes.
d3.json("../data/polarsys_attributes.json", function(error, attributes) {
  if (error) return console.warn(error);

  for(i=0;i<attributes.children.length;i++) {
    attr_mnemo = attributes.children[i]['mnemo'];
    myattrs[attr_mnemo] = attributes.children[i];
  }
});

// Load file for concepts.
d3.json("../data/polarsys_questions.json", function(error, concepts) {
  if (error) return console.warn(error);
  
  for(i=0;i<concepts.children.length;i++) {
    concept_name = concepts.children[i].mnemo;
    myconcepts[concept_name] = concepts.children[i];
  }
});

// Load file for metrics.
d3.json("../data/polarsys_metrics.json", function(error, metrics) {
  if (error) return console.warn(error);
  
  for(i=0;i<metrics.children.length;i++) {
    metric_name = metrics.children[i].mnemo;
    mymetrics[metric_name] = metrics.children[i];
  }
});

d3.json("technology.ease_qm.json", function(error, qm) {
  if (error) return console.warn(error);

  root = qm;
  root.x0 = height / 2;
  root.y0 = 0;

  function collapse(d) {
    if (d.children) {
      d._children = d.children;
      d._children.forEach(collapse);
      d.children = null;
    }
  }

  update(root);
});

function update(source) {

  var tabs = [0, 100, 200, 400, 630, 700];

  // Compute the new tree layout.
  var nodes = tree.nodes(root).reverse(),
      links = tree.links(nodes);

  // Normalize for fixed-depth.
  nodes.forEach(function(d, i) { 
    d.y = tabs[d.depth];
  });

  // Update the nodes…
  var node = svg.selectAll("g.node")
      .data(nodes, function(d) { return d.id || (d.id = ++i); });

  // Enter any new nodes at the parent's previous position.
  var nodeEnter = node.enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + source.y0 + "," + source.x0 + ")"; })
      .on("click", click);

  nodeEnter.append("circle")
      .attr("r", 1e-6)
      .style("fill", function(d) { 
        return d.ind ? mycolours[Math.floor(d.ind)] : "gray"; 
      })
      .style("stroke", function(d) {
	  return "black";
	  //return d.ind ? mycolours[d.ind] : "gray"; 
      });

  nodeEnter.append("text")
      .attr("x", function(d) { return d.children || d._children ? -15 : 20; })
      .attr("dy", function(d) { return d.children || d._children ? "-0.5em" : ".35em" })
      .attr("text-anchor", function(d) { return d.children || d.children ? "end" : "start"; })
      .attr("fill", function(d) { return d.active == "true" ? "black" : "gray";})
      .text(function(d) { 
        value = d.value ? d.value + " / " : "";
	ind = d.ind ? " (" + value + d.ind + ")" : "";
	return d.name + ind;
      })
      .style("fill-opacity", 1e-6);

  // Transition nodes to their new position.
  var nodeUpdate = node.transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + d.y + "," + d.x + ")"; });

  nodeUpdate.select("circle")
      .attr("r", 7)
      .style("fill", function(d) { 
        return d.ind ? mycolours[Math.floor(d.ind)] : "lightgray"; 
      })
      .style("stroke", function(d) {
	  return "black";
      });

  nodeUpdate.select("text")
      .style("fill-opacity", 1);

  // Transition exiting nodes to the parent's new position. '
  var nodeExit = node.exit().transition()
      .duration(duration)
      .attr("transform", function(d) { return "translate(" + source.y + "," + source.x + ")"; })
      .remove();

  nodeExit.select("circle")
      .attr("r", 1e-6);

  nodeExit.select("text")
      .style("fill-opacity", 1e-6);

  // Update the links…
  var link = svg.selectAll("path.link")
      .data(links, function(d) { return d.target.id; });

  // Enter any new links at the parent's previous position. '
  link.enter().insert("path", "g")
      .attr("class", "link")
      .attr("d", function(d) {
        var o = {x: source.x0, y: source.y0};
        return diagonal({source: o, target: o});
      });

  // Transition links to their new position.
  link.transition()
      .duration(duration)
      .attr("d", diagonal);

  // Transition exiting nodes to the parent's new position. '
  link.exit().transition()
      .duration(duration)
      .attr("d", function(d) {
        var o = {x: source.x, y: source.y};
        return diagonal({source: o, target: o});
      })
      .remove();

  // Stash the old positions for transition.
  nodes.forEach(function(d) {
    d.x0 = d.x;
    d.y0 = d.y;
  });
}

// Toggle children on click.
function click(d) {

  var i = 0;
  var mynode;

  // find element in our json files (metrics, concepts, attributes of quality).
  if (typeof d.type == "undefined") {
    alert("No type defined on node.");
  } else {
    if (d.type == "metric") {
      mynode = d;
      mynode.description = mymetrics[d.mnemo]["desc"]; 
      mynode.name = mymetrics[d.mnemo]["name"]; 
      mynode.datasource = mymetrics[d.mnemo]["ds"]; 
      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      var mytitlehtml = d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")";
      mytitlehtml += ' &nbsp; <a href="/documentation/metrics.html#' + mynode.mnemo + '">More info <i class="fa fa-external-link"></i></a>';
      ptitle.html(mytitlehtml); 
  
      p = mydiv.append('p');
      p.classed("details", true); 
      p.html('<div class="row"><div class="col-sm-6"><b>Active:</b> ' + mynode.active.charAt(0).toUpperCase() + mynode.active.slice(1) + ' &nbsp; </div><div class="col-sm-6"><b>Value:</b> ' + d.value + '</div></div>');

      p = mydiv.append('p');
      p.classed("details", true); 
      var mycolour = d.ind ? mycolours[Math.floor(d.ind)] : "gray";
      p.html('<div class="row"><div class="col-sm-6"><b>Data source</b>: ' + mynode.datasource + ' &nbsp; </div><div class="col-sm-6"><b>Computed indicator:</b> <span class="label label-scale" style="background-color: ' + mycolour + '"> ' + d.ind + " </span></div></div>");

      pdesct = mydiv.append('p');
      pdesct.classed("details", true); 
      pdesct.html("<b>Description</b>:")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.html(mynode.description[desc_idx]);
      }
    } else if (d.type == "concept") {
      mynode = d;
      mynode.description = myconcepts[d.mnemo]["desc"]; 
      mynode.name = myconcepts[d.mnemo]["name"]; 
      mynode.question = myconcepts[d.mnemo]["question"]; 

      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      mytitlehtml = d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")";
      mytitlehtml += ' &nbsp; <a href="/documentation/questions.html#' + mynode.mnemo + '">More info <i class="fa fa-external-link"></i></a>';
      ptitle.html(mytitlehtml); 
  
      p = mydiv.append('p');
      p.classed("details", true); 
      var mycolour = d.ind ? mycolours[Math.floor(d.ind)] : "gray";
      p.html('<div class="row"><div class="col-sm-6"><b>Active:</b> ' + mynode.active.charAt(0).toUpperCase() + mynode.active.slice(1) + ' &nbsp; </div><div class="col-sm-6"><b>Value:</b> <span class="label label-scale" style="background-color: ' + mycolour + '"> ' + d.ind + " </span></div></div>");

      pdesct = mydiv.append('p');
      pdesct.classed("details", true); 
      pdesct.html("<b>Question:</b><br />" + mynode.question);
      
      pdesct = mydiv.append('p');
      pdesct.classed("details", true); 
      pdesct.html("<b>Description:</b>")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.html(mynode.description[desc_idx]);
      }
    } else if (d.type == "attribute") {
      mynode = d;
      mynode.description = myattrs[d.mnemo]["desc"]; 
      mynode.name = myattrs[d.mnemo]["name"]; 

      var mydiv = d3.select("div#details-box-project");

      mydiv.text("");

      var ptitle = mydiv.append('p');
      ptitle.classed("title", true);
      mytitlehtml = d.type.charAt(0).toUpperCase() + d.type.slice(1) + ": " + mynode.name + " (" + mynode.mnemo + ")";
      mytitlehtml += ' &nbsp; <a href="/documentation/attributes.html#' + mynode.mnemo + '">More info <i class="fa fa-external-link"></i></a>';
      ptitle.html(mytitlehtml); 
  
      p = mydiv.append('p');
      p.classed("details", true); 
      var mycolour = d.ind ? mycolours[Math.floor(d.ind)] : "gray";
      p.html('<div class="row"><div class="col-sm-6"><b>Active:</b> ' + mynode.active.charAt(0).toUpperCase() + mynode.active.slice(1) + ' &nbsp; </div><div class="col-sm-6"><b>Value:</b> <span class="label label-scale" style="background-color: ' + mycolour + '"> ' + d.ind + ' </span></div></div>');      

      pdesct = mydiv.append('p');
      pdesct.classed("details", true); 
      pdesct.html("<b>Description:</b>")
      for (desc_idx = 0 ; desc_idx < mynode.description.length ; desc_idx++) {
          var pdesc = mydiv.append('p');
          pdesc.classed("details", true);
          pdesc.text(mynode.description[desc_idx]);
      }
    
    }
  }
}

</script>
</div>
<div class="col-lg-5">
<div id="details-box-project"><p>Click on a node to get more details.</p></div>
</div> <!-- col -->
</div> <!-- row -->

                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="attrs"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="20%">Mnemo</th><th width="20%">Value (confidence)</th><th width="20%">Indicator</th></tr>
<tr><td><a href="/documentation/attributes.html#QM_ACTIVITY">Activity</a></td><td><a href="/documentation/attributes.html#QM_ACTIVITY">QM_ACTIVITY</a></td><td>4.2 ( 4 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #66D91A">4.2</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ANA">Analysability</a></td><td><a href="/documentation/attributes.html#QM_ANA">QM_ANA</a></td><td>3.9 ( 5 / 5 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.9</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_CHA">Changeability</a></td><td><a href="/documentation/attributes.html#QM_CHA">QM_CHA</a></td><td>4.5 ( 4 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #66D91A">4.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_DIVERSITY">Diversity</a></td><td><a href="/documentation/attributes.html#QM_DIVERSITY">QM_DIVERSITY</a></td><td>3.7 ( 3 / 3 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.7</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ECOSYSTEM">Ecosystem</a></td><td><a href="/documentation/attributes.html#QM_ECOSYSTEM">QM_ECOSYSTEM</a></td><td>3.9 ( 12 / 13 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.9</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_ITS">Change Management</a></td><td><a href="/documentation/attributes.html#QM_ITS">QM_ITS</a></td><td>4.2 ( 3 / 3 metrics ) </td><td><span class="label label-scale" style="background-color: #66D91A">4.2</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PLAN">Planning Management</a></td><td><a href="/documentation/attributes.html#QM_PLAN">QM_PLAN</a></td><td>1.5 ( 2 / 2 metrics ) </td><td><span class="label label-scale" style="background-color: #FFFF66">1.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PROCESS">Process</a></td><td><a href="/documentation/attributes.html#QM_PROCESS">QM_PROCESS</a></td><td>3.4 ( 12 / 12 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.4</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_PRODUCT">Product</a></td><td><a href="/documentation/attributes.html#QM_PRODUCT">QM_PRODUCT</a></td><td>4.0 ( 20 / 20 metrics ) </td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_QUALITY">Project Maturity</a></td><td><a href="/documentation/attributes.html#QM_QUALITY">QM_QUALITY</a></td><td>3.8 ( 44 / 45 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.8</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_REL">Reliability</a></td><td><a href="/documentation/attributes.html#QM_REL">QM_REL</a></td><td>4.0 ( 7 / 7 metrics ) </td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_RESPONSIVENESS">Responsiveness</a></td><td><a href="/documentation/attributes.html#QM_RESPONSIVENESS">QM_RESPONSIVENESS</a></td><td>4.0 ( 1 / 2 metrics ) </td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_REU">Reusability</a></td><td><a href="/documentation/attributes.html#QM_REU">QM_REU</a></td><td>3.5 ( 4 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_SCM">Configuration Management</a></td><td><a href="/documentation/attributes.html#QM_SCM">QM_SCM</a></td><td>4.8 ( 3 / 3 metrics ) </td><td><span class="label label-scale" style="background-color: #66D91A">4.8</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_SUPPORT">Support</a></td><td><a href="/documentation/attributes.html#QM_SUPPORT">QM_SUPPORT</a></td><td>3.5 ( 4 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.5</span></td></tr>
<tr><td><a href="/documentation/attributes.html#QM_TST">Test Management</a></td><td><a href="/documentation/attributes.html#QM_TST">QM_TST</a></td><td>3.0 ( 4 / 4 metrics ) </td><td><span class="label label-scale" style="background-color: #99E633">3.0</span></td></tr>
</table>


                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="questions"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="20%">Mnemo</th><th width="20%">Value</th><th width="20%">Indicator</th></tr>
<tr><td><a href="/documentation/questions.html#CODE_CLONE">Code cloning</a></td><td><a href="/documentation/questions.html#CODE_CLONE">CODE_CLONE</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#CODE_DOC">Code documentation</a></td><td><a href="/documentation/questions.html#CODE_DOC">CODE_DOC</a></td><td>2.0</td><td><span class="label label-scale" style="background-color: #CCF24D">2.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#CODE_SIZE">Code size</a></td><td><a href="/documentation/questions.html#CODE_SIZE">CODE_SIZE</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#CPX">Code complexity</a></td><td><a href="/documentation/questions.html#CPX">CPX</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#ITS_REL">ITS Reliability</a></td><td><a href="/documentation/questions.html#ITS_REL">ITS_REL</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#ITS_USAGE">ITS usage</a></td><td><a href="/documentation/questions.html#ITS_USAGE">ITS_USAGE</a></td><td>3.5</td><td><span class="label label-scale" style="background-color: #99E633">3.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_ACTIVITY">Developer ML activity</a></td><td><a href="/documentation/questions.html#MLS_DEV_ACTIVITY">MLS_DEV_ACTIVITY</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_DIVERSITY">Developer ML diversity</a></td><td><a href="/documentation/questions.html#MLS_DEV_DIVERSITY">MLS_DEV_DIVERSITY</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_RESPONSIVENESS">Developer ML responsiveness</a></td><td><a href="/documentation/questions.html#MLS_DEV_RESPONSIVENESS">MLS_DEV_RESPONSIVENESS</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_DEV_SUPPORT">Developer ML support</a></td><td><a href="/documentation/questions.html#MLS_DEV_SUPPORT">MLS_DEV_SUPPORT</a></td><td>3.5</td><td><span class="label label-scale" style="background-color: #99E633">3.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_ACTIVITY">User ML activity</a></td><td><a href="/documentation/questions.html#MLS_USR_ACTIVITY">MLS_USR_ACTIVITY</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_DIVERSITY">User ML diversity</a></td><td><a href="/documentation/questions.html#MLS_USR_DIVERSITY">MLS_USR_DIVERSITY</a></td><td>3.0</td><td><span class="label label-scale" style="background-color: #99E633">3.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#MLS_USR_SUPPORT">User ML support</a></td><td><a href="/documentation/questions.html#MLS_USR_SUPPORT">MLS_USR_SUPPORT</a></td><td>3.5</td><td><span class="label label-scale" style="background-color: #99E633">3.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#PLAN_RELEASES">Milestones</a></td><td><a href="/documentation/questions.html#PLAN_RELEASES">PLAN_RELEASES</a></td><td>1.5</td><td><span class="label label-scale" style="background-color: #FFFF66">1.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#PRACTICES_ANA">Analysability practices</a></td><td><a href="/documentation/questions.html#PRACTICES_ANA">PRACTICES_ANA</a></td><td>4.5</td><td><span class="label label-scale" style="background-color: #66D91A">4.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#PRACTICES_CHA">Changeability practices</a></td><td><a href="/documentation/questions.html#PRACTICES_CHA">PRACTICES_CHA</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#PRACTICES_REL">Reliability practices</a></td><td><a href="/documentation/questions.html#PRACTICES_REL">PRACTICES_REL</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#PRACTICES_REU">Reusability practices</a></td><td><a href="/documentation/questions.html#PRACTICES_REU">PRACTICES_REU</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#PUBLIC_DATA">Public access points</a></td><td><a href="/documentation/questions.html#PUBLIC_DATA">PUBLIC_DATA</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#PUB_ITS_INFO">ITS information access</a></td><td><a href="/documentation/questions.html#PUB_ITS_INFO">PUB_ITS_INFO</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#PUB_SCM_INFO">SCM information access</a></td><td><a href="/documentation/questions.html#PUB_SCM_INFO">PUB_SCM_INFO</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#SCM_ACTIVITY">SCM activity</a></td><td><a href="/documentation/questions.html#SCM_ACTIVITY">SCM_ACTIVITY</a></td><td>4.5</td><td><span class="label label-scale" style="background-color: #66D91A">4.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#SCM_DIVERSITY">SCM diversity</a></td><td><a href="/documentation/questions.html#SCM_DIVERSITY">SCM_DIVERSITY</a></td><td>4.0</td><td><span class="label label-scale" style="background-color: #66D91A">4.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#SCM_STABILITY">SCM Stability</a></td><td><a href="/documentation/questions.html#SCM_STABILITY">SCM_STABILITY</a></td><td>2.0</td><td><span class="label label-scale" style="background-color: #CCF24D">2.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#SCM_USAGE">SCM usage</a></td><td><a href="/documentation/questions.html#SCM_USAGE">SCM_USAGE</a></td><td>4.5</td><td><span class="label label-scale" style="background-color: #66D91A">4.5</span></td></tr>
<tr><td><a href="/documentation/questions.html#TST_COV">Test coverage</a></td><td><a href="/documentation/questions.html#TST_COV">TST_COV</a></td><td>2.0</td><td><span class="label label-scale" style="background-color: #CCF24D">2.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#TST_SUCCESS">Test success density</a></td><td><a href="/documentation/questions.html#TST_SUCCESS">TST_SUCCESS</a></td><td>5.0</td><td><span class="label label-scale" style="background-color: #33CC00">5.0</span></td></tr>
<tr><td><a href="/documentation/questions.html#TST_VOL">Number of tests</a></td><td><a href="/documentation/questions.html#TST_VOL">TST_VOL</a></td><td>2.0</td><td><span class="label label-scale" style="background-color: #CCF24D">2.0</span></td></tr>
</table>


                  </div>
                  <div role="tabpanel" class="tab-pane fade" id="metrics"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="20%">Mnemo</th><th width="20%">Value</th><th width="20%">Indicator</th></tr>
<tr><td><a href="/documentation/metrics.html#BRANCH_COVERAGE">Percentage of branches covered by tests</a></td><td><a href="/documentation/metrics.html#BRANCH_COVERAGE">BRANCH_COVERAGE</a></td><td>9.6</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
<tr><td><a href="/documentation/metrics.html#COMMENT_LINES_DENSITY">Comment rate</a></td><td><a href="/documentation/metrics.html#COMMENT_LINES_DENSITY">COMMENT_LINES_DENSITY</a></td><td>14.5</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
<tr><td><a href="/documentation/metrics.html#DUPLICATED_LINES_DENSITY">Cloning density</a></td><td><a href="/documentation/metrics.html#DUPLICATED_LINES_DENSITY">DUPLICATED_LINES_DENSITY</a></td><td>0.8</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#FUNCTIONS">Number of functions</a></td><td><a href="/documentation/metrics.html#FUNCTIONS">FUNCTIONS</a></td><td>1839</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#FUNCTION_COMPLEXITY">Average Cyclomatic Complexity</a></td><td><a href="/documentation/metrics.html#FUNCTION_COMPLEXITY">FUNCTION_COMPLEXITY</a></td><td>2.8</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_AUTH_3M">ITS authors</a></td><td><a href="/documentation/metrics.html#ITS_AUTH_3M">ITS_AUTH_3M</a></td><td>6</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">Defect density</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_DENSITY">ITS_BUGS_DENSITY</a></td><td>0.82</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_BUGS_OPEN">Number of open bugs</a></td><td><a href="/documentation/metrics.html#ITS_BUGS_OPEN">ITS_BUGS_OPEN</a></td><td>32</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_FIX_MED_3M">Median time to fix bug</a></td><td><a href="/documentation/metrics.html#ITS_FIX_MED_3M">ITS_FIX_MED_3M</a></td><td>0.97</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ITS_UPDATES_3M">ITS updates</a></td><td><a href="/documentation/metrics.html#ITS_UPDATES_3M">ITS_UPDATES_3M</a></td><td>164</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#LINE_COVERAGE">Percentage of lines of code covered by tests</a></td><td><a href="/documentation/metrics.html#LINE_COVERAGE">LINE_COVERAGE</a></td><td>11.9</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_AUTH_3M">Developer ML authors</a></td><td><a href="/documentation/metrics.html#MLS_DEV_AUTH_3M">MLS_DEV_AUTH_3M</a></td><td>8</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_3M">Developer ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_RATIO_3M">MLS_DEV_RESP_RATIO_3M</a></td><td>3.54</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_RESP_TIME_MED_3M">Developer ML response time</a></td><td><a href="/documentation/metrics.html#MLS_DEV_RESP_TIME_MED_3M">MLS_DEV_RESP_TIME_MED_3M</a></td><td>0.11</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_3M">Developer ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_DEV_SUBJ_3M">MLS_DEV_SUBJ_3M</a></td><td>13</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_DEV_VOL_3M">Developer ML posts</a></td><td><a href="/documentation/metrics.html#MLS_DEV_VOL_3M">MLS_DEV_VOL_3M</a></td><td>59</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_AUTH_3M">User ML authors</a></td><td><a href="/documentation/metrics.html#MLS_USR_AUTH_3M">MLS_USR_AUTH_3M</a></td><td>5</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_RESP_RATIO_3M">User ML response ratio</a></td><td><a href="/documentation/metrics.html#MLS_USR_RESP_RATIO_3M">MLS_USR_RESP_RATIO_3M</a></td><td>2.85</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_SUBJ_3M">User ML subjects</a></td><td><a href="/documentation/metrics.html#MLS_USR_SUBJ_3M">MLS_USR_SUBJ_3M</a></td><td>13</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#MLS_USR_VOL_3M">User ML posts</a></td><td><a href="/documentation/metrics.html#MLS_USR_VOL_3M">MLS_USR_VOL_3M</a></td><td>50</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA">Number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA">NCC_ANA</a></td><td>124</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_ANA_IDX">Average number of non-conformities for analysability</a></td><td><a href="/documentation/metrics.html#NCC_ANA_IDX">NCC_ANA_IDX</a></td><td>0.00563738861611202</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA">Number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA">NCC_CHA</a></td><td>66</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_CHA_IDX">Average number of non-conformities for changeability</a></td><td><a href="/documentation/metrics.html#NCC_CHA_IDX">NCC_CHA_IDX</a></td><td>0.00300054555373704</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL">Number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL">NCC_REL</a></td><td>13</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REL_IDX">Average number of non-conformities for reliability</a></td><td><a href="/documentation/metrics.html#NCC_REL_IDX">NCC_REL_IDX</a></td><td>0.000591016548463357</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU">Number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU">NCC_REU</a></td><td>1</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCC_REU_IDX">Average number of non-conformities for reusability</a></td><td><a href="/documentation/metrics.html#NCC_REU_IDX">NCC_REU_IDX</a></td><td>4.54628114202582e-05</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#NCLOC">Source Lines Of Code</a></td><td><a href="/documentation/metrics.html#NCLOC">NCLOC</a></td><td>21996</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_MILESTONES_VOL">Number of milestones</a></td><td><a href="/documentation/metrics.html#PLAN_MILESTONES_VOL">PLAN_MILESTONES_VOL</a></td><td>0</td><td><span class="label label-scale" style="background-color: #FFFF66">1</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">Reviews success rate</a></td><td><a href="/documentation/metrics.html#PLAN_REVIEWS_SUCCESS_RATE">PLAN_REVIEWS_SUCCESS_RATE</a></td><td>33.3333333333333</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PUBLIC_API">Public API</a></td><td><a href="/documentation/metrics.html#PUBLIC_API">PUBLIC_API</a></td><td>1126</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">ITS information</a></td><td><a href="/documentation/metrics.html#PUB_ITS_INFO_PMI">PUB_ITS_INFO_PMI</a></td><td>5</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">SCM information</a></td><td><a href="/documentation/metrics.html#PUB_SCM_INFO_PMI">PUB_SCM_INFO_PMI</a></td><td>5</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_ANA">Number of violated rules for analysability</a></td><td><a href="/documentation/metrics.html#RKO_ANA">RKO_ANA</a></td><td>5</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_CHA">Number of violated rules for changeability</a></td><td><a href="/documentation/metrics.html#RKO_CHA">RKO_CHA</a></td><td>5</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REL">Number of violated rules for reliability</a></td><td><a href="/documentation/metrics.html#RKO_REL">RKO_REL</a></td><td>4</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RKO_REU">Number of violated rules for reusability</a></td><td><a href="/documentation/metrics.html#RKO_REU">RKO_REU</a></td><td>1</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_ANA">Adherence to analysability rules</a></td><td><a href="/documentation/metrics.html#ROKR_ANA">ROKR_ANA</a></td><td>58.3333333333333</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_CHA">Adherence to changeability rules</a></td><td><a href="/documentation/metrics.html#ROKR_CHA">ROKR_CHA</a></td><td>37.5</td><td><span class="label label-scale" style="background-color: #99E633">3</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REL">Adherence to reliability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REL">ROKR_REL</a></td><td>85.1851851851852</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#ROKR_REU">Adherence to reusability rules</a></td><td><a href="/documentation/metrics.html#ROKR_REU">ROKR_REU</a></td><td>75</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_ANA">Number of rules for analysability</a></td><td><a href="/documentation/metrics.html#RULES_ANA">RULES_ANA</a></td><td>12</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_CHA">Number of rules for changeability</a></td><td><a href="/documentation/metrics.html#RULES_CHA">RULES_CHA</a></td><td>8</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REL">Number of rules for reliability</a></td><td><a href="/documentation/metrics.html#RULES_REL">RULES_REL</a></td><td>27</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#RULES_REU">Number of rules for reusability</a></td><td><a href="/documentation/metrics.html#RULES_REU">RULES_REU</a></td><td>4</td><td><span class="label label-scale" style="background-color: lightgray"> Not Active </span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITS_3M">SCM Commits</a></td><td><a href="/documentation/metrics.html#SCM_COMMITS_3M">SCM_COMMITS_3M</a></td><td>146</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_3M">Files committed</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTED_FILES_3M">SCM_COMMITTED_FILES_3M</a></td><td>355</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_COMMITTERS_3M">SCM committers</a></td><td><a href="/documentation/metrics.html#SCM_COMMITTERS_3M">SCM_COMMITTERS_3M</a></td><td>4</td><td><span class="label label-scale" style="background-color: #66D91A">4</span></td></tr>
<tr><td><a href="/documentation/metrics.html#SCM_STABILITY_3M">File stability index</a></td><td><a href="/documentation/metrics.html#SCM_STABILITY_3M">SCM_STABILITY_3M</a></td><td>1.76</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
<tr><td><a href="/documentation/metrics.html#TEST_SUCCESS_DENSITY">Test success density</a></td><td><a href="/documentation/metrics.html#TEST_SUCCESS_DENSITY">TEST_SUCCESS_DENSITY</a></td><td>100</td><td><span class="label label-scale" style="background-color: #33CC00">5</span></td></tr>
<tr><td><a href="/documentation/metrics.html#TST_VOL_IDX">Number of tests relative to the code size</a></td><td><a href="/documentation/metrics.html#TST_VOL_IDX">TST_VOL_IDX</a></td><td>3.22785961083833</td><td><span class="label label-scale" style="background-color: #CCF24D">2</span></td></tr>
</table>

</div>
                  <div role="tabpanel" class="tab-pane fade" id="practices"><br /><table class="table table-striped table-condensed table-hover">
<tr><th width="40%">Name</th><th width="40%">Mnemo</th><th width="20%">NCC</th></tr>
<tr><td><a href="/documentation/rules.html#PreserveStackTrace">Preserve Stack Trace</a></td><td><a href="/documentation/rules.html#PreserveStackTrace">PreserveStackTrace</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#MissingBreakInSwitch">Missing Break In Switch</a></td><td><a href="/documentation/rules.html#MissingBreakInSwitch">MissingBreakInSwitch</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#ClassWithOnlyPrivateConstructorsShouldBeFinal">Class With Only Private Constructors Should Be Final</a></td><td><a href="/documentation/rules.html#ClassWithOnlyPrivateConstructorsShouldBeFinal">ClassWithOnlyPrivateConstructorsShouldBeFinal</a></td><td>7</td></tr>
<tr><td><a href="/documentation/rules.html#GodClass">God Class</a></td><td><a href="/documentation/rules.html#GodClass">GodClass</a></td><td>17</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidDeeplyNestedIfStmts">Avoid Deeply Nested If Statements</a></td><td><a href="/documentation/rules.html#AvoidDeeplyNestedIfStmts">AvoidDeeplyNestedIfStmts</a></td><td>29</td></tr>
<tr><td><a href="/documentation/rules.html#NonThreadSafeSingleton">Non Thread Safe Singleton</a></td><td><a href="/documentation/rules.html#NonThreadSafeSingleton">NonThreadSafeSingleton</a></td><td>2</td></tr>
<tr><td><a href="/documentation/rules.html#ConfusingTernary">Confusing Ternary</a></td><td><a href="/documentation/rules.html#ConfusingTernary">ConfusingTernary</a></td><td>69</td></tr>
<tr><td><a href="/documentation/rules.html#AvoidReassigningParameters">Avoid Reassigning Parameters</a></td><td><a href="/documentation/rules.html#AvoidReassigningParameters">AvoidReassigningParameters</a></td><td>17</td></tr>
<tr><td><a href="/documentation/rules.html#SwitchStmtsShouldHaveDefault">Switch Statements Should Have Default</a></td><td><a href="/documentation/rules.html#SwitchStmtsShouldHaveDefault">SwitchStmtsShouldHaveDefault</a></td><td>7</td></tr>
<tr><td><a href="/documentation/rules.html#OverrideBothEqualsAndHashcode">Override Both Equals And Hash code</a></td><td><a href="/documentation/rules.html#OverrideBothEqualsAndHashcode">OverrideBothEqualsAndHashcode</a></td><td>1</td></tr>
<tr><td><a href="/documentation/rules.html#ConstructorCallsOverridableMethod">Constructor Calls Overridable Method</a></td><td><a href="/documentation/rules.html#ConstructorCallsOverridableMethod">ConstructorCallsOverridableMethod</a></td><td>2</td></tr>
</table>
</div>
                  <div role="tabpanel" class="tab-pane fade" id="actions">...</div>
                  <div role="tabpanel" class="tab-pane fade" id="log"><br />
                    <ul class="list-group">
                      <li class="list-group-item"><span class="label label-danger">ERROR</span>  Metric [MLS_USR_RESP_TIME_MED_3M] is missing.</li>
                    </ul>
                  </div>
                </div>
              </div>
